import {codeTasks} from './tasks.mjs';
(() => {
 const tr=(a,b)=>window.realdevLocale==='en'?b:a,txt=x=>x?.[window.realdevLocale==='en'?'en':'tr']||'',safe=x=>esc(x??'');
 let selected='sum-positive',codeDraft={},runResult=null,running=false,worker=null,timer=null,executed=null,saveState='',lastId=null,newsData=null,githubData=null,historyData=null,newsLoading=false,gitLoading=false,historyLoading=false,newsError='',gitError='',activeSummary=null,labHint=false;
 const drafts=()=>codeDraft[selected]??(selected==='playground'?'console.log("Hello, developer!");':codeTasks.find(t=>t.id===selected).starter);
 const btn=(label,a,extra='',secondary=false)=>`<button class="${secondary?'secondary':'primary'}-button" data-live="${a}" ${extra}>${label}</button>`;
 const sourceLink=(url,label)=>{try{const u=new URL(url);if(u.protocol!=='https:')return '';return `<a href="${safe(u.href)}" target="_blank" rel="noopener noreferrer">${safe(label)} ↗</a>`;}catch{return '';}};
 const time=x=>x?new Date(x).toLocaleString(window.realdevLocale==='en'?'en-GB':'tr-TR'):tr('Henüz yok','Not yet');
 function shell(title,description,content){return `<div class="rd" translate="no"><h1>${title}</h1><p class="muted">${description}</p>${content}</div>`;}
 function draw(){render();document.getElementById('labNav').textContent=tr('Kod alanı','Code workspace');if(state.view==='lab'||state.view==='codehistory')document.getElementById('crumbCurrent').textContent=state.view==='lab'?tr('Kod alanı','Code workspace'):tr('Kod geçmişim','Code history');}
 async function api(path,body,method='POST'){const response=await fetch('/api/'+path,{method:body?method:'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(45000)});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'request_failed'),{status:response.status});return data;}
 function capture(){const input=document.getElementById('lab-code');if(input)codeDraft[selected]=input.value;}
 function stop(){clearTimeout(timer);timer=null;worker?.terminate();worker=null;running=false;}
 function format(x){try{return JSON.stringify(x);}catch{return String(x);}}
 function results(){if(!runResult)return '';return `<section class="rd-card" aria-live="polite"><h2>${tr('Çalıştırma sonucu','Execution result')}</h2>${runResult.error?`<div class="rd-notice rd-error">${safe(runResult.error)}</div>`:''}${runResult.total?`<h3>${runResult.passed}/${runResult.total} ${tr('test geçti','tests passed')}</h3>`:''}<pre>${safe((runResult.logs||[]).join('\n')||tr('Konsol çıktısı yok.','No console output.'))}</pre>${runResult.cases?.length?`<div class="rd-table"><table><thead><tr><th>${tr('Girdi','Input')}</th><th>${tr('Beklenen','Expected')}</th><th>${tr('Sonucun','Your result')}</th></tr></thead><tbody>${runResult.cases.map(c=>`<tr><td>${safe(format(c.input))}</td><td>${safe(format(c.expected))}</td><td>${c.pass?'✓':'×'} ${safe(c.error||format(c.actual))}</td></tr>`).join('')}</tbody></table></div>`:''}<p class="muted">${tr('Bu testler cihazındaki izole motorda çalıştırıldı. Kod denemesi olarak saklanır; sunucuda doğrulanmış beceri puanı verilmez.','These tests ran in the isolated engine on your device. They are saved as code practice, without a server-verified skill score.')}</p><div class="rd-actions">${btn(tr('Denememi hesabıma kaydet','Save practice to my account'),'save-run')}${btn(tr('Kod geçmişim','Code history'),'code-history','',true)}</div><p role="status">${safe(saveState)}</p></section>`;}
 function lab(){const q=codeTasks.find(t=>t.id===selected);return shell(tr('Kod alanı','Code workspace'),tr('Hatayı yeniden üret, çıktıyı oku, kodu düzelt ve test et.','Reproduce the error, read the output, fix the code and test it.'),`<div class="rd-actions">${btn(tr('Kod geçmişim','Code history'),'code-history','',true)}</div><section class="rd-card"><label class="rd-label" for="lab-task">${tr('Görev','Exercise')}</label><select id="lab-task">${codeTasks.map(t=>`<option value="${t.id}" ${selected===t.id?'selected':''}>${safe(txt(t.title))}</option>`).join('')}<option value="playground" ${selected==='playground'?'selected':''}>${tr('Serbest JavaScript','JavaScript playground')}</option></select><p style="margin-top:16px">${q?safe(txt(q.prompt)):tr('JavaScript yaz ve console.log ile sonucu gör.','Write JavaScript and inspect output with console.log.')}</p><label class="rd-label" for="lab-code">JavaScript</label><textarea id="lab-code" class="rd-code" style="min-height:260px" spellcheck="false" maxlength="12000">${safe(drafts())}</textarea><div class="rd-actions">${running?btn(tr('Durdur','Stop'),'stop'):btn(tr('Kodu çalıştır →','Run code →'),'run')}${btn(tr('Başlangıç kodunu geri yükle','Restore starter code'),'reset','',true)}${q?btn(tr('İpucu','Hint'),'lab-hint','',true):''}</div>${labHint&&q?`<div class="rd-notice">${safe(txt(q.hint))}</div>`:''}<p class="muted" style="margin-top:16px">${tr('JavaScript / QuickJS · 16 MB bellek · 350 ms yürütme bütçesi · ağ, dosya ve hesap verilerine erişim yok. Paket yükleme ve DOM desteklenmez.','JavaScript / QuickJS · 16 MB memory · 350 ms execution budget · no access to network, files or account data. Package installation and DOM are not supported.')}</p></section>${results()}`);}
 function diagnosticCards(){return '<div class="rd" translate="no"><section class="rd-card"><h2>'+tr('Git, API ve çalışma ortamı hataları','Git, API and runtime errors')+'</h2><div class="rd-actions">'+[['git-1','Git · non-fast-forward'],['cors-1','API · CORS'],['clr-1','C# · CLR']].map(([id,label])=>'<button class="secondary-button" data-rd="practice" data-task="'+id+'">'+label+'</button>').join('')+'</div></section></div>';}
 function errors(){return diagnosticCards()+shell(tr('Hata laboratuvarı','Error lab'),tr('Bozuk kodla başla, ilk hata mesajını bul ve testlerle düzelt.','Start with broken code, identify the first error and repair it using tests.'),`<div class="rd-grid">${codeTasks.map(q=>`<article class="rd-card"><span class="rd-tag">${q.topic}</span><h2>${safe(txt(q.title))}</h2><p>${safe(txt(q.prompt))}</p>${btn(tr('Hatayı incele →','Inspect error →'),'open-code',`data-id="${q.id}"`)}</article>`).join('')}</div>`);}
 async function loadNews(){if(newsLoading)return;newsLoading=true;newsError='';try{newsData=await api('news');}catch{newsError=tr('Haberler alınamadı. Yeniden deneyebilirsin.','Could not load news. Please retry.');}finally{newsLoading=false;if(state.view==='news')draw();}}
 function news(){if(!newsData&&!newsLoading&&!newsError)queueMicrotask(loadNews);return shell(tr('Güncel gelişmeler','Latest developments'),tr('Resmi kaynakların canlı RSS akışları. Önbellek en fazla 15 dakika; eski kayıtlar açıkça işaretlenir.','Live RSS feeds from official sources. Cache refreshes after 15 minutes; stale records are labeled.'),`<div class="rd-actions">${btn(newsLoading?tr('Yükleniyor…','Loading…'):tr('Haberleri yenile','Refresh news'),'refresh-news','',true)}</div>${newsError?`<div class="rd-notice rd-error">${newsError}</div>`:''}${newsData?`<section class="rd-card">${newsData.sources.map(s=>`<p><strong>${safe(s.name)}</strong> · ${s.error?tr('Kaynağa ulaşılamadı','Source unavailable'):tr('Güncel akış','Current feed')} ${s.stale?tr('· eski kayıt','· stale record'):''}<br><small>${tr('Son başarılı kontrol:','Last successful check:')} ${time(s.fetchedAt)}</small></p>`).join('')}</section>${newsData.items.map((n,i)=>`<article class="rd-card"><span class="rd-tag">${safe(n.source)}</span><span class="muted">${time(n.publishedAt)} ${n.stale?tr('· Eski kayıt','· Stale'):''}</span><h2>${safe(n.title)}</h2>${activeSummary===i?`<div class="rd-notice"><strong>${tr('Kaynağın kısa özeti','Source excerpt')}</strong><p>${safe(n.summary||tr('Kaynak bu haber için özet vermiyor.','This source provides no summary.'))}</p></div>`:''}<div class="rd-actions">${btn(activeSummary===i?tr('Özeti kapat','Hide excerpt'):tr('Haberi özetle','Summarize news'),'summary',`data-index="${i}"`,true)}${sourceLink(n.url,tr('Asıl kaynağa git','Read original source'))}</div></article>`).join('')||`<section class="rd-card">${tr('Henüz haber alınamadı; kaynak durumlarını kontrol et.','No news available yet; check source status.')}</section>`}`:`<p role="status">${tr('Haber akışları yükleniyor…','Loading feeds…')}</p>`}`);}
 async function loadGit(){if(gitLoading)return;gitLoading=true;gitError='';try{githubData=await api('github');}catch{gitError=tr('GitHub bilgileri alınamadı.','GitHub data could not be loaded.');}finally{gitLoading=false;if(state.view==='github')draw();}}
 function github(){if(!githubData&&!gitLoading&&!gitError)queueMicrotask(loadGit);const g=githubData;return shell(tr('GitHub çalışma alanım','My GitHub workspace'),tr('Herkese açık bir depoyu takip et: commitler, pull request’ler ve Actions çalışmaları.','Follow a public repository: commits, pull requests and Actions runs.'),`<section class="rd-card"><label class="rd-label" for="github-repo">${tr('Depo (sahip/ad)','Repository (owner/name)')}</label><input class="rd-search" id="github-repo" value="${safe(g?.selected||'melisau/RealDev')}" placeholder="melisau/RealDev"><div class="rd-actions">${btn(tr('Depoyu bağla','Connect repository'),'save-repo')}${btn(gitLoading?tr('Yükleniyor…','Loading…'):tr('Yenile','Refresh'),'refresh-github','',true)}</div><p class="muted">${tr('Bu bağlantı herkese açık verileri okur. Özel depo girişi, kod gönderme veya workflow başlatma yetkisi vermez.','This connection reads public data. It does not grant private repository access, code pushes or workflow execution.')}</p>${gitError?`<div class="rd-notice rd-error">${safe(gitError)}</div>`:''}</section>${g?.repository?`<section class="rd-card"><h2>${sourceLink(g.repository.url,g.repository.name)}</h2><p>${safe(g.repository.description||'')}</p><p>${tr('Varsayılan branch:','Default branch:')} ${safe(g.repository.branch)} · ${Object.keys(g.languages||{}).map(safe).join(' · ')}</p><p class="muted">${tr('Son kontrol:','Last checked:')} ${time(g.fetchedAt)} ${g.stale?tr('· Eski kayıt; yenileme başarısız','· Stale; refresh failed'):''}</p>${(g.errors||[]).map(e=>`<p>${safe(e.section)}: ${safe(e.error)}</p>`).join('')}</section><div class="rd-grid"><section class="rd-card"><h2>${tr('Son commitler','Recent commits')}</h2><ul class="rd-list">${g.commits.map(c=>`<li>${sourceLink(c.url,c.sha.slice(0,7))}<p>${safe(c.message)}</p></li>`).join('')||`<li>${tr('Commit kaydı yok.','No commits found.')}</li>`}</ul><h2>Pull requests</h2>${g.pulls.map(p=>`<p>${sourceLink(p.url,'#'+p.number+' '+p.title)}</p>`).join('')||`<p>${tr('Açık pull request yok.','No open pull requests.')}</p>`}</section><section class="rd-card"><h2>GitHub Actions</h2><ul class="rd-list">${g.runs.map(r=>`<li><h3>${sourceLink(r.url,r.name)}</h3><span class="rd-tag">${safe(r.conclusion||r.status)}</span>${['failure','timed_out'].includes(r.conclusion)?`<p>${tr('İlk başarısız job ve step’i aç; hata satırını bul, yerelde aynı komutu yeniden üret.','Open the first failed job and step, locate the error line and reproduce that command locally.')}</p>`:''}</li>`).join('')||`<li>${tr('Henüz Actions çalışması yok.','No Actions runs yet.')}</li>`}</ul></section></div>`:g?.error?`<div class="rd-notice rd-error">${safe(g.error)} · ${tr('Depo açık olmalı; GitHub istek sınırı da erişimi engelleyebilir.','The repository must be public; GitHub rate limits may also block access.')}</div>`:''}`);}
 async function history(){if(historyLoading)return;historyLoading=true;try{historyData=await api('code-runs');state.view='codehistory';}catch{saveState=tr('Geçmiş alınamadı.','Could not load history.');}finally{historyLoading=false;draw();}}
 function historyView(){return shell(tr('Kod denemelerim','My code practice'),tr('Hesabına kaydettiğin kodlar. Sonuçlar tarayıcıdaki çalışma ortamından gelir.','Code saved to your account. Results come from the browser execution environment.'),(historyData?.records||[]).map(r=>`<details><summary>${safe(txt(codeTasks.find(t=>t.id===r.task_id)?.title)||'JavaScript')} · ${time(r.created_at)}</summary><pre>${safe(r.code)}</pre>${btn(tr('Bu kodla devam et','Continue with this code'),'restore-run',`data-id="${r.id}"`,true)}</details>`).join('')||`<section class="rd-card">${tr('Kayıtlı kod denemesi yok.','No saved code practice.')}</section>`);}
 function run(){capture();stop();running=true;runResult=null;saveState='';lastId=crypto.randomUUID();const id=lastId;executed={id,code:drafts(),taskId:selected};worker=new Worker('/code-worker.js');timer=setTimeout(()=>{stop();runResult={error:tr('Çalıştırma süresi aşıldı.','Execution timed out.'),logs:[],cases:[]};draw();},5000);worker.onmessage=e=>{if(e.data.id!==id)return;clearTimeout(timer);runResult=e.data.result;stop();draw();};worker.onerror=()=>{clearTimeout(timer);stop();runResult={error:tr('Kod motoru başlatılamadı.','Code engine could not start.'),logs:[],cases:[]};draw();};worker.postMessage(executed);draw();}
 document.addEventListener('input',e=>{if(e.target.id==='lab-code')capture();});
 document.addEventListener('change',e=>{if(e.target.id==='lab-task'){capture();stop();selected=e.target.value;runResult=null;labHint=false;draw();}});
 document.addEventListener('click',async e=>{const el=e.target.closest('[data-live]');if(!el){if(e.target.closest('#languageToggle')){capture();setTimeout(()=>{if(['lab','errors','news','github','codehistory'].includes(state.view))draw();},0);}return;}e.preventDefault();e.stopImmediatePropagation();capture();const a=el.dataset.live;
  if(a==='run'){run();return;}if(a==='stop'){stop();runResult={error:tr('Durduruldu.','Stopped.'),logs:[],cases:[]};draw();return;}
  if(a==='open-code'){stop();selected=el.dataset.id;state.view='lab';runResult=null;labHint=false;draw();return;}
  if(a==='reset'){stop();codeDraft[selected]=selected==='playground'?'console.log("Hello, developer!");':codeTasks.find(t=>t.id===selected).starter;runResult=null;draw();return;}
  if(a==='lab-hint'){labHint=!labHint;draw();return;}if(a==='refresh-news'){await loadNews();return;}if(a==='summary'){activeSummary=activeSummary===Number(el.dataset.index)?null:Number(el.dataset.index);draw();return;}if(a==='refresh-github'){await loadGit();return;}if(a==='code-history'){await history();return;}
  if(a==='restore-run'){stop();const r=historyData.records.find(r=>r.id===el.dataset.id);selected=r.task_id;codeDraft[selected]=r.code;runResult=null;state.view='lab';draw();return;}
  if(a==='save-repo'){const repo=document.getElementById('github-repo').value.trim();el.disabled=true;try{githubData=await api('github',{repository:repo},'PUT');gitError='';}catch{gitError=tr('Depo doğrulanamadı. Açık depo adını ve GitHub erişimini kontrol et.','Could not verify repository. Check the public repository name and GitHub access.');}draw();return;}
  if(a==='save-run'&&runResult&&executed){el.disabled=true;try{await api('code-runs',{...executed,result:runResult});saveState=tr('Kod denemen hesabına kaydedildi.','Code practice saved to your account.');}catch{saveState=tr('Kaydedilemedi; kodun burada duruyor, tekrar deneyebilirsin.','Save failed; your code is still here. Please retry.');}draw();}
 },true);
 renderers.lab=lab;renderers.errors=errors;renderers.news=news;renderers.github=github;renderers.codehistory=historyView;
 window.addEventListener('pagehide',stop);setInterval(()=>{if(state.view==='news')loadNews();},300000);
 draw();
})();
