import test from 'node:test';import assert from 'node:assert/strict';
import {tasks,publicTask} from '../server/catalog.mjs';import {grade,evidence,route,expression} from '../server/assessment.mjs';
test('all choice keys grade consistently; public tasks do not expose keys',()=>{for(const t of tasks){assert.equal(publicTask(t).answer,undefined);assert.equal(publicTask(t).explain,undefined);if(t.kind!=='expression'){assert.equal(grade(t,t.answer).score,100);assert.equal(grade(t,(t.answer+1)%t.options.length).score,0);}}});
test('code exercise runs meaningful edge cases and accepts equivalent expressions',()=>{const t=tasks.find(t=>t.id==='predicate-1');assert.equal(grade(t,'n > 0 && n % 2 === 0').score,100);assert.equal(grade(t,'!(n <= 0) && !(n % 2)').score,100);const f=grade(t,'n % 2 === 0');assert.ok(f.cases.some(c=>c.input===0&&!c.pass));assert.ok(f.cases.some(c=>c.input<0&&!c.pass));assert.notEqual(f.score,100);});
test('sandbox rejects function calls, property access, loops, assignments and excess depth',()=>{for(const s of ['fetch("/api")','n.constructor','while(true){}','n=1','(()=>true)()','globalThis','n; true','('.repeat(50)+'n'+')'.repeat(50)+'; fetch(1)'])assert.throws(()=>expression(s));assert.equal(grade(tasks[7],'process.exit()').score,null);});
const record=(id,area,score,hinted=0,date='2026-10-01T12:00:00.000Z')=>({task_id:id,area,score,hinted,skipped:0,created_at:date});
test('repeating one question cannot manufacture multiple distinct evidence',()=>{const rows=[record('react-1','frontend',100),record('react-1','frontend',100)];let e=evidence(rows).find(x=>x.area==='frontend');assert.equal(e.distinct,1);assert.equal(e.status,'initial');rows.push(record('react-2','frontend',100,1));e=evidence(rows).find(x=>x.area==='frontend');assert.equal(e.status,'initial');rows.push(record('react-2','frontend',100,0,'2026-10-02T12:00:00Z'));assert.equal(evidence(rows).find(x=>x.area==='frontend').status,'supported');});
test('route respects time budget and goals and chooses an unseen transfer task',()=>{const rows=[record('react-1','frontend',0)];const r=route({goals:['frontend'],dailyMinutes:10},rows,new Date('2026-10-05'));assert.equal(r[0].area,'frontend');assert.equal(r[0].taskId,'react-2');assert.ok(r.filter(x=>x.today).reduce((s,x)=>s+x.minutes,0)<=10);});
test('successful areas are spaced, with no same-day automatic repetition',()=>{const rows=[record('react-1','frontend',100),record('react-2','frontend',100,0,'2026-10-05T12:00:00Z')];const r=route({goals:['frontend'],dailyMinutes:15},rows,new Date('2026-10-05T13:00:00Z')).find(x=>x.area==='frontend');assert.equal(r.reason,'scheduled');assert.equal(r.today,false);assert.equal(r.dueAt,'2026-10-12T12:00:00.000Z');});
