import test from 'node:test';import assert from 'node:assert/strict';
import {api} from '../server/api.mjs';import {localDb} from '../scripts/local-db.mjs';import {database} from '../server/db.mjs';
import {evaluateExplanation,summarize,transcribe,reserveAI} from '../server/ai.mjs';
import {practicalCodeTasks} from '../sandbox/practical-tasks.mjs';import {execute} from '../sandbox/runtime.mjs';import {newsFeed} from '../server/live.mjs';
import {eraseAccount} from '../server/account.mjs';import {evidence} from '../server/assessment.mjs';
const origin='https://realdev.test';
function client(DB,user='a',extra={}){return async(path,body,method='POST')=>{const r=await api(new Request(origin+'/api/'+path,{method:body===undefined?'GET':method,headers:{'oai-authenticated-user-id':user,Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),{DB,...extra});return {status:r.status,body:await r.json()};};}
test('export includes account-owned data; reset preserves profile; deletion isolates users and shared caches',async()=>{
 const DB=localDb(),a=client(DB),b=client(DB,'b');const prefs={displayName:'Çığ',technologies:'React',goals:['fullstack'],dailyMinutes:15};
 await a('profile',prefs,'PUT');await b('profile',{...prefs,displayName:'B'},'PUT');await a('runs',{id:'erase-run',kind:'practice',taskId:'react-1'});await a('hint',{runId:'erase-run',taskId:'react-1'});
 const r=await a('answer',{runId:'erase-run',taskId:'react-1',answer:1,explanation:'thinking',confidence:1,skipped:false});await a('library',{attemptId:r.body.attempt.id});await a('notes',{id:'erase-note',taskId:'react-1',text:'Why?'});
 await a('practice',{id:'erase-project',taskId:'project-api-validation',code:'function solve(x){return 1}',explanation:''});await database({DB}).write('INSERT INTO source_cache VALUES (?,?,?)','public-feed','{}','2026-10-05');
 const exported=(await a('account/export')).body;assert.equal(exported.data.accounts[0].display_name,'Çığ');assert.equal(exported.data.hints.length,1);assert.equal(exported.data.practice_submissions.length,1);assert.equal(exported.data.source_cache,undefined);assert.ok(Object.values(exported.data).flat().every(r=>!('user_id' in r)));assert.equal((await b('account/export')).body.data.attempts.length,0);
 assert.equal((await a('account/erase',{scope:'account',confirmation:'DELETE'})).status,400);assert.equal((await a('state')).body.notes.length,1);
 await a('account/erase',{scope:'learning',confirmation:'RESET LEARNING'});assert.equal((await a('state')).body.account.display_name,'Çığ');assert.equal((await a('state')).body.attempts.length,0);
 await a('account/erase',{scope:'account',confirmation:'DELETE REALDEV'});assert.equal((await a('state')).body.account,null);assert.equal((await b('state')).body.account.display_name,'B');assert.equal((await database({DB}).all('SELECT * FROM source_cache')).length,1);DB.close();
});
test('deletion batch rolls back every operation on database failure',async()=>{const DB=localDb(),db=database({DB}),a=client(DB);await a('profile',{displayName:'A',technologies:'',goals:['fullstack'],dailyMinutes:15},'PUT');await db.write('INSERT INTO notes VALUES (?,?,?,?,?,?,?)','n','a','react-1','Keep',0,'today','today');const faulty={...db,batch:queries=>db.batch([...queries,['INSERT INTO missing_table VALUES (?)',1]])};await assert.rejects(eraseAccount(faulty,'a','account'));assert.equal((await db.one('SELECT body FROM notes WHERE id=?','n')).body,'Keep');assert.ok(await db.one('SELECT user_id FROM accounts WHERE user_id=?','a'));DB.close();});
test('project submissions enforce ordered stages, ignore client grades and remain user-scoped',async()=>{
 const DB=localDb(),a=client(DB),b=client(DB,'b');const run={id:'p-one',taskId:'project-api-validation',code:'function solve(x){return {status:201,task:x}}',explanation:'claim',result:{passed:999}};
 const r=await a('practice',run);assert.equal(r.status,200);assert.notEqual(r.body.result.passed,r.body.result.total);assert.equal((await a('practice',{...run,id:'p-two',taskId:'project-api-idempotency'})).status,409);assert.equal((await b('practice',run)).status,404);assert.equal((await a('practice',{...run,code:'changed'})).status,409);
 assert.equal((await b('practice')).body.records.length,0);assert.equal((await a('practice')).body.projects.find(p=>p.id==='api-service').completedStages,0);assert.ok((await a('practice')).body.tasks.every(t=>!t.reference&&!t.tests));DB.close();
});
const solutions={
 'project-api-validation':'function solve(i){const p=i.priority===undefined?"normal":i.priority;if(typeof i.title!=="string"||!i.title.trim()||i.title.trim().length>80||!["low","normal","high"].includes(p))return {status:400,error:"invalid_task"};return {status:201,task:{title:i.title.trim(),priority:p}}}',
 'project-api-idempotency':'function solve(i){const r=i.records.find(r=>r.user===i.user&&r.key===i.key);if(!r)return {status:201,id:"new"};return r.payload.title===i.payload.title&&r.payload.priority===i.payload.priority?{status:200,id:r.id}:{status:409}}',
 'project-api-transfer':'function solve(i){const n=i.limit===undefined?2:i.limit;if(!Number.isInteger(n)||n<1||n>5)return {status:400};const all=i.orders.filter(r=>r.user===i.user&&r.id>(i.after??0)).sort((a,b)=>a.id-b.id);const items=all.slice(0,n);return {status:200,items,next:all.length>n?items.at(-1).id:null}}',
 'project-ui-reducer':'function solve({state:s,event:e}){if(e.type==="start")return {status:"loading",requestId:e.id,data:s.data,error:null};if(e.id!==s.requestId)return s;if(e.type==="success")return {status:"success",requestId:s.requestId,data:e.data,error:null};if(e.type==="failure")return {status:"error",requestId:s.requestId,data:s.data,error:e.error};return s}',
 'project-ui-debug':'function solve(events){let s={requestId:0,data:[],loading:false,error:null};for(const e of events){if(e.type==="start")s={...s,requestId:e.id,loading:true,error:null};else if(e.id===s.requestId){if(e.type==="success")s={...s,data:e.data,loading:false,error:null};if(e.type==="failure")s={...s,error:e.error,loading:false};}}return s}',
 'project-ui-transfer':'function solve({local,remote}){const m=new Map(remote.map(r=>[r.id,r]));for(const r of local){const old=m.get(r.id);if(!old||r.dirty||r.version>old.version)m.set(r.id,r)}return [...m.values()].sort((a,b)=>a.id-b.id)}',
 'project-data-ingest':'function solve({existing,events}){const seen=new Set(existing),out=[];for(const r of events)if(typeof r.id==="string"&&r.id.trim()&&typeof r.amount==="number"&&Number.isFinite(r.amount)&&r.amount>=0&&!seen.has(r.id)){seen.add(r.id);out.push({id:r.id,amount:r.amount})}return out}',
 'project-data-debug':'function solve(rows){const m=new Map();for(const r of rows){const k=r.group??"ungrouped",v=m.get(k)||{group:k,total:0,count:0};v.total+=r.amount;v.count++;m.set(k,v)}return [...m.values()].sort((a,b)=>a.group<b.group?-1:a.group>b.group?1:0)}',
 'project-data-transfer':'function solve({documents,limit}){const m=new Map();for(const d of documents)if(typeof d.id==="string"&&d.id.trim()&&typeof d.source==="string"&&d.source.trim()&&typeof d.score==="number"&&Number.isFinite(d.score)&&(!m.has(d.id)||d.score>m.get(d.id).score))m.set(d.id,d);return [...m.values()].sort((a,b)=>b.score-a.score||(a.id<b.id?-1:a.id>b.id?1:0)).slice(0,limit)}'
};
test('nine authored project tests reject buggy starters and accept working implementations',async()=>{for(const task of practicalCodeTasks){const bad=await execute(task.starter,task.id);assert.ok(bad.passed<bad.total||bad.error,task.id);const good=await execute(solutions[task.id],task.id);assert.equal(good.passed,task.tests.length,task.id);}});
test('a three-stage project resumes from server data and grants evidence by modality',async()=>{const DB=localDb(),a=client(DB);for(const id of ['project-api-validation','project-api-idempotency','project-api-transfer'])assert.equal((await a('practice',{id:id+'-run',taskId:id,code:solutions[id],explanation:'reason'})).status,200);const state=(await a('state')).body;assert.equal(state.projects.find(p=>p.id==='api-service').completed,true);const e=state.evidence.find(e=>e.area==='api');assert.deepEqual(e.modalities.sort(),['debug','project','transfer']);assert.equal(e.status,'initial');DB.close();});
function model(value){return async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(value)}]}],usage:{input_tokens:10,output_tokens:10}});};}
test('AI feedback requires exact learner quotes, rubric coverage and remains provisional',async()=>{
 const input={prompt:'Why?',reference:'Use parameters',criteria:[{id:'c1',text:'Explain parameters'}],answer:'I use parameterized queries.',language:'en'};
 const value={criteria:[{id:'c1',verdict:'supported',quote:'parameterized queries',reason:'Avoids injection'}],nextStep:'Test a malicious input.'};
 const env={OPENAI_API_KEY:'test-key',AI_FETCH:model(value)};const result=await evaluateExplanation(env,input);assert.equal(result.score,100);assert.equal(result.verification,'ai-provisional');
 await assert.rejects(evaluateExplanation({...env,AI_FETCH:model({...value,criteria:[{...value.criteria[0],quote:'invented learner phrase'}]})},input),/ai_ungrounded_response/);
 const rows=[{task_id:'review',area:'sql',score:100,verification:'ai-provisional',modality:'review',created_at:'2026-10-05'}];const e=evidence(rows).find(e=>e.area==='sql');assert.equal(e.independent,0);assert.equal(e.score,null);assert.equal(e.provisional,1);
});
test('AI summaries bind to source quotes and daily limits are atomic per user',async()=>{
 const item={title:'Release',summary:'A new feature is available.',url:'https://openai.com/news'};const env={OPENAI_API_KEY:'test',AI_FETCH:model({sentences:[{text:'Yeni özellik yayınlandı.',quote:'new feature is available'}]})};assert.equal((await summarize(env,item,'tr')).scope,'title-and-feed-excerpt');
 await assert.rejects(summarize({...env,AI_FETCH:model({sentences:[{text:'Invented',quote:'not in source'}]})},item,'en'),/ai_ungrounded_response/);
 const DB=localDb(),db=database({DB});await reserveAI(db,'a','text',{...env,AI_DAILY_LIMIT:1});await assert.rejects(reserveAI(db,'a','text',{...env,AI_DAILY_LIMIT:1}),/ai_daily_limit/);await reserveAI(db,'b','text',{...env,AI_DAILY_LIMIT:1});await assert.rejects(reserveAI(db,'a','audio',{}),/ai_not_configured/);DB.close();
});
test('audio validates MIME and size, transcribes with consent without storing recordings',async()=>{
 let calls=0;const env={OPENAI_API_KEY:'test',AI_FETCH:async(url,opts)=>{calls++;assert.ok(url.endsWith('/audio/transcriptions'));assert.ok(opts.body instanceof FormData);return Response.json({text:'API is a contract.'});}};
 const file=new File(['audio fixture'],'recording.webm',{type:'audio/webm'});assert.equal((await transcribe(env,file,'en')).audioStored,false);await assert.rejects(transcribe(env,new File(['bad'],'x',{type:'text/plain'}),'en'),/invalid_audio/);assert.equal(calls,1);
 const DB=localDb();const form=new FormData();form.set('file',file);form.set('language','en');const request=()=>new Request(origin+'/api/transcribe',{method:'POST',headers:{Origin:origin,'oai-authenticated-user-id':'a'},body:form});assert.equal((await api(request(),{DB,...env})).status,400);form.set('consent','yes');assert.equal((await api(request(),{DB,...env})).status,200);assert.equal((await client(DB)('account/export')).body.data.practice_submissions.length,0);DB.close();
});
test('manual news refresh honors cooldown; old cache is archived, recent fallback stays clearly stale',async()=>{const DB=localDb(),db=database({DB});let calls=0;const feed=async url=>{calls++;return new Response(`<rss><channel><item><title>Release</title><link>https://${new URL(url).hostname}/release</link><pubDate>Mon, 05 Oct 2026 10:00:00 GMT</pubDate><description>Source</description></item></channel></rss>`);};await newsFeed(db,feed);await newsFeed(db,feed,true);assert.equal(calls,4);await db.write("UPDATE source_health SET attempted_at='2000-01-01'");const r=await newsFeed(db,async()=>{throw Error('HTTP 429');},true);assert.equal(r.items.length,4);assert.ok(r.items.every(i=>i.stale));assert.ok(r.sources.every(s=>s.error==='HTTP 429'));DB.close();});
test('provider exhausted credit is distinct from temporary rate limits and never returns a fabricated score',async()=>{const input={prompt:'why',reference:'test',criteria:[{id:'c1',text:'test'}],answer:'learner',language:'en'};await assert.rejects(evaluateExplanation({OPENAI_API_KEY:'test',AI_FETCH:async()=>Response.json({error:{code:'credit_balance_exhausted',type:'insufficient_quota'}},{status:429})},input),/ai_billing_required/);await assert.rejects(evaluateExplanation({OPENAI_API_KEY:'test',AI_FETCH:async()=>Response.json({error:{code:'rate_limit_exceeded'}},{status:429})},input),/ai_provider_limit/);});
test('request size limits reject an oversized JSON body before parsing or storage',async()=>{const DB=localDb(),r=await api(new Request(origin+'/api/profile',{method:'PUT',headers:{Origin:origin,'Content-Type':'application/json','oai-authenticated-user-id':'a'},body:'x'.repeat(144001)}),{DB});assert.equal(r.status,413);assert.equal((await client(DB)('state')).body.account,null);DB.close();});
