import {roleInterviewTracks} from './interview-tracks.mjs';
import {depthProjects,depthTasks} from './depth-curriculum.mjs';
const L=(tr,en)=>({tr,en});
const src=(label,url)=>({label,url});
const pythonBase=`import json, sqlite3, sys
from http.server import BaseHTTPRequestHandler, HTTPServer

def database():
    db = sqlite3.connect(":memory:")
    db.execute("CREATE TABLE items (id INTEGER PRIMARY KEY, owner TEXT NOT NULL, name TEXT NOT NULL)")
    db.execute("CREATE TABLE stock (id INTEGER PRIMARY KEY, quantity INTEGER NOT NULL CHECK(quantity >= 0))")
    db.executemany("INSERT INTO stock VALUES (?,?)", [(1,10),(2,4)])
    db.commit()
    return db

def handle(db, request):
    # TODO: implement the stage contract. Never concatenate SQL input.
    return {"status": 501}

if __name__ == "__main__":
    db = database()
    if "--serve" in sys.argv:
        class Handler(BaseHTTPRequestHandler):
            def do_POST(self):
                try:
                    size = int(self.headers.get("Content-Length", "0"))
                    if size < 1 or size > 16384: raise ValueError("size")
                    request = json.loads(self.rfile.read(size))
                    response = handle(db, request)
                except (ValueError, TypeError): response = {"status": 400}
                payload = json.dumps(response).encode()
                self.send_response(response["status"])
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers(); self.wfile.write(payload)
        HTTPServer(("127.0.0.1", 8080), Handler).serve_forever()
    else:
        print(json.dumps([handle(db,r) for r in json.load(sys.stdin)]))
`;
const csharpBase=`using System;
using System.Collections.Generic;
public class Program {
 public static void Main() {
  var rows = Console.In.ReadToEnd().Split(new[]{'\\n'}, StringSplitOptions.RemoveEmptyEntries);
  // TODO: process each line according to the stage contract.
  Console.WriteLine("TODO");
 }
}`;
function task(id,project,language,area,modality,minutes,title,prompt,source,starter=language==='python'?pythonBase:csharpBase){return {id,project,language,area,modality,minutes,title:L(...title),prompt:L(...prompt),source,starter,suiteVersion:1};}
export const advancedProjects=[
 ...depthProjects,
 {id:'sqlite-api',title:L('Gerçek API + SQLite projesi','Real API + SQLite project'),minutes:150,brief:L('HTTP adaptörü ve gerçek SQLite veritabanıyla doğrulama, sahiplik ve atomik stok işlemleri. Yerelde HTTP çalıştırılır; sandbox aynı handler’ı JSON istekleriyle sınar.','Validation, ownership and atomic inventory operations with an HTTP adapter and real SQLite. Run HTTP locally; the sandbox tests the same handler with JSON requests.'),stages:['advanced-api-validation','advanced-api-ownership','advanced-api-transaction'],setup:L('Python 3 ile indirilen main.py dosyasını düzenle. python main.py --serve: yalnızca localhost:8080. POST JSON örneği: {"op":"create","owner":"alice","name":"book"}. Eğitim sunucusudur; dış ağa açma. Her test yeni bellek veritabanıyla başlar.','Edit downloaded main.py with Python 3. python main.py --serve binds localhost:8080 only. POST JSON example: {"op":"create","owner":"alice","name":"book"}. This training server is for local use. Each test starts with a fresh in-memory database.')},
 {id:'dotnet-service',title:L('.NET servis sözleşmesi ve hata ayıklama','.NET service contract and debugging'),minutes:135,brief:L('HTTP hata eşleme, atomik stok hareketi ve iptal/yeniden deneme durumları. Testler saf C# alan modelini çalıştırır; ASP.NET/EF Core dağıtımı ayrıca yerelde uygulanır.','HTTP error mapping, atomic stock changes and cancellation/retry states. Tests execute a plain C# domain model; implement ASP.NET/EF Core hosting separately locally.'),stages:['advanced-dotnet-contract','advanced-dotnet-stock','advanced-dotnet-retry'],setup:L('C# konsol modelini önce test et. Yerel ASP.NET Core projesinde MapPost ile modele bağla; ProblemDetails, CancellationToken ve EF Core transaction ekle. Kabul koşulları: 400/401/404/409 ayrımı, stok eksiye düşmemeli, iptal edilen istek yazmamalı. Mono testi ASP.NET veya EF entegrasyonunu doğrulamaz.','Test the C# console model first. Connect it through MapPost in a local ASP.NET Core project; add ProblemDetails, CancellationToken and an EF Core transaction. Acceptance: distinguish 400/401/404/409, no negative stock, cancelled requests must not write. Mono tests do not verify ASP.NET or EF integration.')},
 {id:'unity-lifecycle',title:L('Unity yaşam döngüsü, havuz ve kayıt','Unity lifecycle, pooling and saves'),minutes:140,brief:L('Çifte event aboneliği, havuzda stale state ve bozuk kayıt verisini incele. Testler motor bağımsız C# mantığını sınar; sahne/PlayMode doğrulaması yerel Unity projesindedir.','Investigate duplicate subscriptions, stale pooled state and corrupt saves. Tests check engine-independent C# logic; scene/PlayMode verification happens in a local Unity project.'),stages:['advanced-unity-events','advanced-unity-pool','advanced-unity-save'],setup:L('Unity’de OnEnable/OnDisable aboneliğini eşle, pool objesinin canını spawn’da sıfırla ve save migration yaz. PlayMode testi: enable-disable-enable → tek event; pool return/rent → temiz state; bozuk save → güvenli varsayılan. Konsol testleri FPS, sahne referansları veya Unity callback sırasını kanıtlamaz.','Pair OnEnable/OnDisable subscriptions in Unity, reset pooled health on spawn, and implement save migration. PlayMode checks: enable-disable-enable gives one event; return/rent clears state; corrupt saves use safe defaults. Console tests do not establish FPS, scene references or Unity callback ordering.')}
 ,{id:'data-service',title:L('Sürüm alan API ve olay deposu','Versioned API and event store'),minutes:165,brief:L('SQLite şema evrimi, sahipli sayfalama ve idempotent olay alımını ayrı testli görevlerle uygula. Her görev beklenen/gerçek sonucu karşılaştırır; görev sonunda inceleme ve başka alana aktarım yaparsın.','Implement SQLite schema evolution, owner-scoped pagination and idempotent event ingestion with separately tested tasks. Each task compares expected and actual results; finish with review and transfer.'),stages:['advanced-api-migration','advanced-api-pagination','advanced-event-transfer'],setup:L('Python 3 ve sqlite3 ile indirilen main.py üzerinde çalış. Eğitim runner’ı her testte temiz bellek SQLite veritabanı açar. Şema görevi migration’ı iki kez güvenle çalıştırmanı ister; sayfalama ve olay görevlerinde istek listesi JSON, yanıt listesi JSON’dur. Yerel HTTP adaptörü yalnızca 127.0.0.1:8080 adresine bağlanır. Eğitim kimliği olarak gelen owner alanını kullan; gerçek uygulamada bunu doğrulanmış oturumdan al.','Work in main.py with Python 3 and sqlite3. The training runner opens a fresh in-memory SQLite database for every test. The schema task requires a safely repeatable migration; pagination and event tasks use a JSON request list and JSON response list. The local HTTP adapter binds only to 127.0.0.1:8080. Treat owner as exercise identity; production must derive it from a verified session.')}
];
const py=src('Python · sqlite3','https://docs.python.org/3/library/sqlite3.html'),net=src('Microsoft · ASP.NET error handling','https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling'),unity=src('Unity · OnDisable','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/MonoBehaviour.OnDisable.html');
export const advancedTasks=[
 ...depthTasks,
 task('advanced-api-validation','sqlite-api','python','api','project',45,['API: doğrulama ve SQL parametreleri','API: validation and SQL parameters'],['handle(db,r) yaz. create: owner ve name boş olmayan string; trim sonrası name 1..80 karakter. Geçersiz→{status:400}. Başarılı INSERT parametreli SQL ile yapılır→{status:201,id:<id>}. list→{status:200,items:[{id,owner,name}]} id artan; bilinmeyen op→{status:404}. owner/name trim edilir. Liste bu aşamada herkese açıktır; sonraki aşamada sahiplik eklenir. Girdi JSON istek listesi, çıktı JSON yanıt listesi.','Implement handle(db,r). create requires nonempty string owner and a trimmed name of 1..80 characters. Invalid→{status:400}. Parameterized SQL INSERT→{status:201,id:<id>}. list→{status:200,items:[{id,owner,name}]} by ascending id; unknown op→{status:404}. Trim owner/name. Listing is unrestricted at this stage; ownership is added next. Input/output are JSON request/response lists.'],py),
 task('advanced-api-ownership','sqlite-api','python','api','debug',45,['API: başka kullanıcının verisini koru','API: protect another user’s data'],['Önceki create doğrulamasını koru. Her op için boş olmayan string owner şart, yoksa 401. list yalnızca aynı owner kayıtlarını döndürsün. delete: id pozitif integer (bool değil); yok/geçersiz/başkasına ait→404, sahiplik eşleşirse sil→204. Bilinmeyen op→404. Kullanıcı kimliği bu eğitim protokolünde owner alanıdır; gerçek uygulamada doğrulanmış token’dan alınmalıdır.','Keep create validation. Every op requires a nonempty string owner, otherwise 401. list returns only that owner’s rows. delete requires a positive integer id (not bool); absent/invalid/another owner’s id→404; owned deletion→204. Unknown op→404. The exercise represents identity as owner; production must derive it from a verified token.'],py),
 task('advanced-api-transaction','sqlite-api','python','sql','transfer',60,['SQLite: atomik stok transferi','SQLite: atomic inventory transfer'],['Bu aşamanın API’si farklıdır. stock→{status:200,stock:[[1,q1],[2,q2]]}. transfer: from/to pozitif farklı integer id, quantity pozitif integer; bool kabul edilmez. Geçersiz→400, id yok→404, yetersiz stok→409. Başarılı→204; tek transaction’da azalt/artır. Başlangıç stok 1=10,2=4. fail:true (test fault injection) ise ilk UPDATE sonrası hata simüle et, rollback→500. Hatalı transfer sonrası stock değişmemeli.','This stage has a different API. stock→{status:200,stock:[[1,q1],[2,q2]]}. transfer requires distinct positive integer from/to ids and a positive integer quantity; reject bool. Invalid→400, missing id→404, insufficient stock→409. Success→204; debit/credit in one transaction. Initial stock: 1=10,2=4. With fail:true (test fault injection), simulate failure after the first UPDATE, rollback→500. Failed transfers must not change stock.'],py),
 task('advanced-dotnet-contract','dotnet-service','csharp','dotnet','project',40,['C#: servis hata sözleşmesi','C#: service error contract'],['Her stdin satırı auth exists quantity. auth=0→401; quantity<=0→400; exists=0→404; quantity>10→409; aksi halde201. Öncelik bu sırada. Her satır için yalnızca status yazdır. Üretim HTTP katmanında auth sunucuda doğrulanır; bu saf model eğitim girdisidir.','Each stdin line: auth exists quantity. auth=0→401; quantity<=0→400; exists=0→404; quantity>10→409; otherwise201. Apply in this order. Print one status per line. Production HTTP authentication is server-verified; these flags are domain-model exercise inputs.'],net),
 task('advanced-dotnet-stock','dotnet-service','csharp','dotnet','debug',50,['C#: yarım kalan stok hareketini düzelt','C#: fix a partial stock movement'],['Stok a=10,b=4. Her satır quantity fail (fail 0/1). quantity<=0→400; quantity>a→409; fail=1→500 ve iki stok da değişmez; başarıda a’dan düş,b’ye ekle→204. Her satırdan sonra status a b yazdır. Hata sonrası sonraki isteği doğru işle. Modelde kopya üzerinde doğrula; EF Core uygulamasında transaction/rollback gerekir.','Initial stock a=10,b=4. Each line: quantity fail (0/1). quantity<=0→400; quantity>a→409; fail=1→500 with neither stock changed; success debits a and credits b→204. Print status a b after each line. Continue correctly after failure. Validate on a copy in this model; the EF Core implementation requires transaction/rollback.'],net),
 task('advanced-dotnet-retry','dotnet-service','csharp','dotnet','transfer',45,['C#: iptal ve tekrar deneme','C#: cancellation and retries'],['Tek tek satırlar: start, cancel, transient, retry, success. Başlangıç state=idle,attempt=0. start yalnızca idle/failed/cancelled durumunda→running,attempt=1. cancel yalnızca running/failed→cancelled. transient running→failed. retry failed ve attempt<3→running,attempt++; limitte failed kalır. success running→done. Diğer olaylar yok sayılır. Her satırdan sonra state attempt yazdır. cancelled/done duruma gelen geç success sonucu uygulanmaz.','Lines: start, cancel, transient, retry, success. Initial state=idle,attempt=0. start in idle/failed/cancelled→running,attempt=1. cancel in running/failed→cancelled. transient in running→failed. retry in failed with attempt<3→running,attempt++; remain failed at the limit. success in running→done. Ignore other events. Print state attempt after each line. Late success must not mutate cancelled/done states.'],net),
 task('advanced-unity-events','unity-lifecycle','csharp','unity','project',40,['Unity: çifte abonelik izini çöz','Unity: fix duplicate subscription traces'],['Satırlar enable/disable/event. Başlangıç disabled,hits=0. enable iki kez gelirse yalnızca bir aktif abonelik; disable kaldırır ve tekrar disable güvenlidir. event yalnızca enabled ise hits bir artar. Her satırdan sonra hits yazdır. Bu C# modelini OnEnable/OnDisable aboneliğine aktar.','Lines: enable/disable/event. Initially disabled,hits=0. Repeated enable creates only one subscription; disable removes it and repeated disable is safe. event adds one hit only while enabled. Print hits after each line. Transfer this C# model to OnEnable/OnDisable subscriptions.'],unity),
 task('advanced-unity-pool','unity-lifecycle','csharp','game','debug',50,['Unity: havuzda kalan canı sıfırla','Unity: reset stale health in a pool'],['Satırlar rent/return/damage N. Başlangıç inactive,health=0. rent yalnızca inactive ise active ve health=100; active iken tekrar rent state’i korur. return→inactive,health=0. damage yalnızca active iken ve N>=0 ise health=max(0,health-N); 0 olunca inactive. Her satır için health true/false (active, küçük harf) yazdır.','Lines: rent/return/damage N. Initially inactive,health=0. rent while inactive sets active,health=100; repeated rent while active preserves state. return sets inactive,health=0. damage only while active and N>=0 sets health=max(0,health-N); at 0 become inactive. Print health true/false (active, lowercase) per line.'],unity),
 task('advanced-unity-save','unity-lifecycle','csharp','game','transfer',50,['Unity: save migration ve bozuk veri','Unity: save migration and corrupt data'],['Her satır version health. version=1 ise health’i ikiyle çarp (eski ölçek); version=2 aynen al; desteklenmeyen sürüm, bozuk sayı veya satır→varsayılan100. Geçerli canı 0..100 arasında sınırla. Taşmayı önlemek için long parse/hesapla. Her satır bir integer çıktı. Bu model JSON serileştirme veya dosya yazma atomikliğini test etmez; yerelde bu kabul koşullarını da uygula.','Each line: version health. version=1 doubles health (legacy scale); version=2 uses it as-is; unsupported version, malformed number or line→default100. Clamp valid health to 0..100. Parse/calculate with long to avoid overflow. Print one integer per line. This model does not test JSON serialization or atomic file writes; add those acceptance checks locally.'],unity)
 ,task('advanced-api-migration','data-service','python','sql','project',55,['API/SQLite: geriye uyumlu not şeması migration’ı','API/SQLite: backward-compatible notes schema migration'],['handle(db,r) içinde migration, schema ve create_note işlemlerini uygula. migrate: notes(id INTEGER PRIMARY KEY, owner TEXT NOT NULL, topic TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner,topic)) tablosunu ve idx_notes_owner_created_at indeksini güvenle oluştur; birden çok kez çağrılabilir. schema: status 200, kolon adları sırayla [id,owner,topic,body,created_at], unique_owner_topic ve owner_created_index boolean alanları döndür. create_note: owner/topic/body trimlenmiş, boş olmayan string; topic en fazla 80, body en fazla 2000 karakter. Geçersiz→400; migration yoksa→503; aynı owner+topic ikinci kayıt→409; yeni kayıt→201 ve id. Tüm değerleri parametreli SQL ile işle; girdi JSON istek listesi, çıktı yanıt listesidir.','Implement migrate, schema and create_note in handle(db,r). migrate safely creates notes(id INTEGER PRIMARY KEY, owner TEXT NOT NULL, topic TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner,topic)) and index idx_notes_owner_created_at; it must be repeatable. schema returns status 200, columns in order [id,owner,topic,body,created_at], and boolean fields unique_owner_topic and owner_created_index. create_note requires trimmed nonempty string owner/topic/body; topic max 80 and body max 2000 characters. Invalid→400; missing migration→503; duplicate owner+topic→409; new row→201 and id. Use parameterized SQL for every value. Input/output are JSON request/response lists.'],src('SQLite · CREATE TABLE and ALTER TABLE','https://www.sqlite.org/lang_createtable.html'))
 ,task('advanced-api-pagination','data-service','python','api','debug',55,['API: kararlı ve sahipli sayfalama','API: stable owner-scoped pagination'],['notes migration şemasını bu görevde kur. seed_note ile verilen owner/topic/body kayıtlarını id artan sırada ekle; geçersiz seed→400. list_notes: owner boş olmayan string olmalı, yoksa 401. limit varsayılan 3, integer 1..5 olmalı (bool/string kabul edilmez), geçersizse 400. after yoksa 0; varsa pozitif integer ve bool olmamalı, aksi 400. Yalnızca owner’a ait id>after satırlarını id artan sırada al; limit+1 satır okuyup en fazla limit sonuç döndür. Yanıt {status:200,items:[{id,topic,body}],next:<son dönen id veya null>}; daha fazla satır yoksa next null. Log vakası: owner=ada, after=2, limit=2 çağrısı aynı sayfayı tekrar döndürüyor. Beklenen sayfalarda kayıt tekrarı olmamalı; sıralamayı eşsiz id ile sabitle ve after değerini offset gibi yorumlama. SQL girdilerini birleştirme.','Set up the notes schema in this task. seed_note inserts the supplied owner/topic/body rows in ascending id order; invalid seed→400. list_notes requires a nonempty string owner or returns 401. limit defaults to 3 and must be an integer 1..5 (reject bool/string); invalid→400. after defaults to 0; when supplied it must be a positive integer and not bool, else 400. Select only that owner’s rows with id>after in ascending id order; fetch limit+1 and return at most limit. Response: {status:200,items:[{id,topic,body}],next:<last returned id or null>}; next is null when there are no more rows. Incident log: owner=ada, after=2, limit=2 returns the same page again. Pages must not repeat rows; use unique id ordering and do not interpret after as an offset. Never concatenate SQL input.'],src('PostgreSQL · LIMIT and OFFSET','https://www.postgresql.org/docs/17/queries-limit.html'))
 ,task('advanced-event-transfer','data-service','python','data','transfer',55,['Olay API’si: idempotent batch ve aktarım','Event API: idempotent batch and transfer'],['migrate işlemi events(owner,event_id,topic,amount) tablosunu (owner,event_id) birincil anahtarı ve owner/topic indeksiyle güvenle oluşturur; migrate→204. ingest migrate öncesi→503. ingest isteği events dizisi alır. Her elemanda owner/event_id/topic boş olmayan string, amount sıfırdan büyük integer (bool değil) olmalı; tüm batch’i önce doğrula. Aynı owner+event_id ve aynı payload tekrar gelirse ikinci yazma yapmadan başarıya dahil et; farklı payload çatışması→409 ve batch’in hiçbir yazısı kalmasın. Geçersiz kayıt→400, bilinmeyen op→404. Başarılı ingest→202 ve {accepted:<yeni+aynı içerikle tekrarlanan benzersiz kayıt sayısı>}. totals owner için topic’e göre amount toplamını alfabetik sırada [{topic,amount}] döndürür; sahiplik filtresini her sorguda uygula. Transaction içinde parametreli SQL kullan. SQL benzeri metinler normal veri olarak saklanmalı.','Create events(owner,event_id,topic,amount) with a composite primary key (owner,event_id) and an owner/topic index. ingest receives an events array. Each entry needs nonempty string owner/event_id/topic and a positive integer amount (not bool); validate the full batch first. A replay with the same owner+event_id and identical payload counts as accepted without a second write; a different payload conflict→409 and the batch must leave no writes. Invalid entry→400; unknown op→404. Successful ingest→202 and {accepted:<count of new plus identical replay records>}. totals for an owner returns sums by topic, sorted alphabetically, as [{topic,amount}]; scope every query by owner. Use parameterized SQL inside a transaction. SQL-looking strings are ordinary data.'],src('AWS Builders’ Library · idempotent APIs','https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/'))
];
const step=(id,minutes,title,prompt,checks)=>({id,minutes,title:L(...title),prompt:L(...prompt),checks:checks.map(pair=>L(...pair))});
const common=[
 step('requirements',10,['İhtiyacı netleştir','Clarify requirements'],['Bir mobil oyun için kullanıcı profili, envanter ve liderlik tablosu API’si tasarla. Trafik, gecikme ve çevrimdışı davranış için hangi soruları sorarsın? Açık varsayımlar ve kabul kriterleri yaz.','Design profile, inventory and leaderboard APIs for a mobile game. What would you ask about traffic, latency and offline use? State assumptions and acceptance criteria.'],[['Ölçülebilir gereksinim ve en az bir bilinmeyen','Measurable requirements and at least one unknown'],['Başarı ile hata davranışını ayır','Distinguish success and failure behavior']]),
 step('design',15,['Tasarım ve veri modeli','Architecture and data model'],['İstek akışını, tabloları, unique/foreign-key kısıtlarını ve API sözleşmesini yaz. İki istemci aynı envanter öğesini alırsa ne olur? Transaction, yetkilendirme ve idempotency kararını gerekçelendir.','Describe request flow, tables, unique/foreign-key constraints and API contracts. What if two clients claim the same inventory item? Explain transaction, authorization and idempotency decisions.'],[['İndeks ve transaction sınırı','Index and transaction boundary'],['İstemciye güvenmeyen sahiplik denetimi','Ownership checks that do not trust client claims']]),
 step('debug',15,['Canlı hata incelemesi','Incident investigation'],['Log: POST /purchase 201; retry POST /purchase 201; player coins=-20; timeout after COMMIT. Teşhis hipotezlerini sırala. Hangi ek kanıtı toplarsın? En küçük düzeltme, migration ve regresyon testini yaz.','Log: POST /purchase 201; retry POST /purchase 201; player coins=-20; timeout after COMMIT. Order your hypotheses. What evidence is missing? Describe the smallest fix, migration and regression test.'],[['Hipotez ile kanıtı ayır','Separate hypotheses from evidence'],['Tekrar istek ve commit sonrası timeout testi','Test replay and timeout after commit']]),
 step('implementation',15,['Kod ve inceleme','Implementation and review'],['Seçtiğin dilde satın alma işleminin çekirdek kodunu yaz. Negatif tutar, yetersiz bakiye, duplicate key, cancelled request ve aynı kullanıcıdaki iki istek için testler ekle. AI kullanırsan değiştirdiğin satırların nedenini de açıkla.','Write the purchase core in your chosen language. Add tests for negative amounts, insufficient balance, duplicate keys, cancellation and concurrent requests. If you use AI, explain why you changed each relevant line.'],[['Başarı dışında en az dört hata testi','At least four failure tests besides success'],['Kod ile açıklama tutarlı','Explanation matches code']]),
 step('transfer',10,['Farklı projeye aktar','Transfer to another project'],['Aynı yaklaşımı Unity çevrimdışı ödül kuyruğu ve .NET API’ye aktar. Replay/çatışma politikası, event abonelik ömrü, local save migration ve sunucu otoritesini tartış. Nerede önceki çözüm yetersiz kalır?','Transfer the design to a Unity offline reward queue and .NET API. Discuss replay/conflicts, event lifetime, save migration and server authority. Where does the previous design fall short?'],[['En az iki aktarım farkı','At least two transfer differences'],['Motor/servis sınırlarını açıkla','Explain engine/service boundaries']]),
 step('reflection',10,['Mülakat öz değerlendirmesi','Interview reflection'],['En zayıf kalan iki cevabını seç. Her biri için kaynak, küçük deneme ve tekrar tarihi yaz. Hangi cevapta varsayım yaptın? Görüşmeciye soracağın iki soruyla bitir.','Choose your two weakest answers. For each, write a source, a small experiment and a review date. Which answer relied on assumptions? Finish with two questions for the interviewer.'],[['Kanıta bağlı eksik listesi','Evidence-linked gap list'],['Somut tekrar görevi','Concrete follow-up practice']])
];
export const interviewTracks=[{id:'fullstack-interview',title:L('Full stack · 75 dakikalık mülakat','Full stack · 75-minute interview'),minutes:75,steps:common},{id:'dotnet-interview',title:L('.NET backend · 75 dakikalık mülakat','.NET backend · 75-minute interview'),minutes:75,steps:common.map(s=>s.id==='transfer'?{...s,prompt:L('EF Core transaction, concurrency token ve CancellationToken ile çözümünü başka veri sağlayıcısına aktar. Hangi provider farkları entegrasyon testi ister? İptal commit sonrasında gelirse ne söylemelisin?','Transfer your solution to another provider with EF Core transactions, concurrency tokens and CancellationToken. Which provider differences need integration tests? What if cancellation arrives after commit?')}:s)},{id:'unity-interview',title:L('Unity mobil oyun · 75 dakikalık mülakat','Unity mobile game · 75-minute interview'),minutes:75,steps:common.map(s=>s.id==='debug'?{...s,prompt:L('enable-disable-enable-event izi iki kez ödül veriyor; havuzdan dönen nesne eski HP ile geliyor; uygulama pause sırasında save dosyası bozuluyor. Hipotez, profiler/log kanıtı, düzeltme ve EditMode/PlayMode testlerini yaz.','An enable-disable-enable-event trace grants two rewards; pooled objects retain old HP; pause corrupts the save file. Describe hypotheses, profiler/log evidence, fixes and EditMode/PlayMode tests.')}:s)}];
interviewTracks.push(...roleInterviewTracks);
export function advancedProgress(records){return advancedProjects.map(project=>{const stageResults=project.stages.map(id=>{const row=records.filter(r=>r.task_id===id).at(-1);let report;try{report=JSON.parse(row?.result||'null')?.report;}catch{}return {id,passed:report?.verification==='server-verified'&&report.total>0&&report.passed===report.total};});return {...project,stageResults,completedStages:stageResults.filter(s=>s.passed).length};});}
