// Original RealDev scenarios. References verify technical behavior; no external question bank was copied.
const bi = (tr, en) => ({tr, en});
const q = (id, area, topic, difficulty, format, title, prompt, code, options, explain, hint, source) =>
  ({id, area, topic, difficulty, format, title, prompt, code, options, explain, hint, source});
const rows = [
q('js-nullish','frontend',['JavaScript · varsayılan değer','JavaScript · default value'],'foundation','code-reading',
 ['Sıfır geçerli bir değer','Zero is a valid value'],
 ['Stok 0 olduğunda ekranda 10 yerine 0 görünmeli. Hangi ifade bu gereksinimi karşılar?','When stock is 0, the screen must show 0 rather than 10. Which expression meets this requirement?'],
 'const stock = 0;',
 [['stock ?? 10','stock ?? 10'],['stock || 10','stock || 10'],['stock && 10','stock && 10'],['stock ? stock : 10','stock ? stock : 10']],
 ['?? yalnızca null veya undefined için varsayılana geçer; 0 korunur. || ise 0 gibi falsy değerlerde de sağ tarafı seçer.','?? defaults only for null or undefined, preserving 0. || also uses its right operand for falsy values such as 0.'],
 ['Eksik değer ile sıfırı ayır.','Distinguish a missing value from zero.'],
 ['MDN · Nullish coalescing','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing']),
q('react-form-key','frontend',['React · key ve state','React · key and state'],'intermediate','scenario',
 ['Alıcı değişince taslağı sıfırla','Reset a draft when the recipient changes'],
 ['Aynı konumdaki Chat bileşeni local state tutuyor. Alıcı değişince taslak tamamen sıfırlanmalı. En doğrudan React çözümü hangisi?','Chat holds local state at the same tree position. Switching recipient must completely reset the draft. What is the most direct React solution?'],
 '<Chat recipient={recipient} />',
 [['Chat için key={recipient.id} kullan.','Give Chat key={recipient.id}.'],['Yalnızca recipient propunu değiştir; local state her prop değişiminde silinir.','Only change recipient; every prop change clears local state.'],['Her render’da rastgele key üret.','Generate a random key on every render.'],['Taslağı tüm alıcılar için aynı global değişkende tut.','Keep one global draft for every recipient.']],
 ['Alıcıya bağlı kararlı key değişince React yeni bileşen kimliği oluşturur ve local state sıfırlanır. Rastgele key ise aynı alıcıda da gereksiz sıfırlamaya neden olur.','Changing a stable recipient key creates a new component identity and resets local state. A random key also causes unwanted resets for the same recipient.'],
 ['Bileşenin kimliği ile prop değerini ayır.','Distinguish component identity from a prop value.'],
 ['React · Preserving state','https://react.dev/learn/preserving-and-resetting-state']),
q('react-stale-response','frontend',['React · effect yarış koşulu','React · effect race condition'],'intermediate','diagnosis',
 ['Eski arama sonucu yenisini eziyor','An old search response overwrites the new one'],
 ['Kullanıcı önce A sonra B arıyor. B yanıtı önce geliyor; ardından A ekranda B’yi eziyor. En uygun düzeltme hangisi?','A user searches A then B. B resolves first; A then overwrites B on screen. Which fix addresses this?'],
 'useEffect(() => {\n  fetch("/search?q=" + query).then(r => r.json()).then(setItems);\n}, [query]);',
 [['Cleanup ile eski isteği iptal et veya eski yanıtı yok say; yalnız güncel isteğin sonucunu uygula.','Cancel the old request or ignore its response during cleanup; apply only the current result.'],['Dependency dizisini boşalt.','Empty the dependency array.'],['Her yanıta aynı sabit gecikmeyi ekle.','Add the same fixed delay to every response.'],['setItems çağrısını render içine taşı.','Move setItems into render.']],
 ['İsteklerin başlama ve tamamlanma sırası farklı olabilir. Cleanup eski yanıtın state’i güncellemesini engellemelidir; HTTP hata kontrolü ayrıca yapılır.','Requests can finish out of order. Cleanup must prevent an obsolete response from updating state; HTTP errors also need separate handling.'],
 ['İlk başlayan istek mutlaka ilk bitmez.','The first request started need not finish first.'],
 ['React · Effect cleanup','https://react.dev/learn/synchronizing-with-effects']),
q('cs-using-dispose','dotnet',['C# · IDisposable using','C# · IDisposable using'],'foundation','code-reading',
 ['Exception sırasında dosya temizliği','File cleanup during an exception'],
 ['Dosya başarıyla açılıyor, ReadToEnd exception atıyor. using bloğu terk edilirken ne olur?','The file opens successfully, then ReadToEnd throws. What happens when execution leaves the using block?'],
 'using (var reader = File.OpenText(path))\n{\n    return reader.ReadToEnd();\n}',
 [['reader.Dispose çağrılır; exception otomatik olarak yutulmaz.','reader.Dispose is called; the exception is not automatically swallowed.'],['Dispose yalnız normal return durumunda çağrılır.','Dispose is called only for a normal return.'],['using exception’ı başarı sonucuna dönüştürür.','using converts the exception into success.'],['Dosyayı yalnız garbage collector kapatabilir.','Only the garbage collector can close the file.']],
 ['using, oluşturulan IDisposable kaynağını kapsam çıkışında temizler; exception yolu da buna dahildir. Hatanın yakalanması ayrı bir karardır.','using disposes an acquired IDisposable resource when its scope exits, including on an exception. Catching the exception is a separate decision.'],
 ['Kaynak temizliği ile hata yakalamayı karıştırma.','Separate resource cleanup from catching errors.'],
 ['Microsoft · using','https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using']),
q('cs-cancellation','dotnet',['.NET · CancellationToken iptal',' .NET · CancellationToken cancellation'],'intermediate','diagnosis',
 ['İptal edilen arama çalışmaya devam ediyor','A cancelled search keeps running'],
 ['CancellationTokenSource.Cancel çağrılıyor ama uzun döngü token’ı hiç okumuyor. İş neden durmuyor?','CancellationTokenSource.Cancel is called, but a long loop never reads its token. Why does the work continue?'],
 'while (hasMore) { ProcessNext(); }',
 [['İptal işbirliklidir; döngü token’ı kontrol etmeli ve iptal destekli alt çağrılara iletmelidir.','Cancellation is cooperative; check the token and pass it to cancellable child operations.'],['Cancel tüm thread’leri zorla sonlandırır; sorun yalnız logdadır.','Cancel forcibly terminates all threads; only the logs are wrong.'],['Token sadece UI metnini değiştirir.','A token only changes UI text.'],['İptal için her zaman process’i öldürmek gerekir.','Cancellation always requires killing the process.']],
 ['Cancel bir iptal isteği bildirir. Çalışan kod bu isteği gözlemlemeli; uygun noktalarda ThrowIfCancellationRequested veya iptal destekli API kullanmalıdır.','Cancel signals a request. Running code must observe it, using ThrowIfCancellationRequested at appropriate points or cancellation-aware APIs.'],
 ['İsteği göndermek ile işin isteği gözlemlemesi farklıdır.','Signalling a request differs from observing it.'],
 ['Microsoft · Cooperative cancellation','https://learn.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads']),
q('dotnet-scoped-worker','dotnet',['.NET · DI scoped singleton',' .NET · DI scoped singleton'],'intermediate','scenario',
 ['BackgroundService içinde scoped bağımlılık','A scoped dependency in BackgroundService'],
 ['Singleton BackgroundService her turda scoped DbContext kullanacak. Yaşam sürelerini nasıl yönetirsin?','A singleton BackgroundService needs a scoped DbContext per iteration. How should lifetimes be managed?'],
 '',
 [['IServiceScopeFactory ile her işlem için scope oluştur, DbContext’i oradan çöz ve scope’u temizle.','Create a scope per operation with IServiceScopeFactory, resolve DbContext there and dispose the scope.'],['DbContext’i singleton yapıp tüm işleri aynı instance ile yürüt.','Make DbContext singleton and share it across all work.'],['Scoped DbContext’i singleton constructor’ına doğrudan enjekte et.','Inject the scoped DbContext directly into the singleton constructor.'],['Scope doğrulamasını kapat; yaşam süresi sorunu çözülür.','Disable scope validation to solve the lifetime problem.']],
 ['Singleton içinde scoped servisi doğrudan tutmak kapsamı yanlış uzatır. Açık scope, işlemin bağımlılıklarını uygun yaşam süresinde oluşturur ve temizler.','Capturing a scoped service in a singleton extends its lifetime incorrectly. An explicit scope creates and disposes dependencies for the operation.'],
 ['Uzun yaşayan servis ile işlem başına kaynak aynı ömürde olmamalı.','A long-lived service and a per-operation resource need different lifetimes.'],
 ['Microsoft · DI scope validation','https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection/overview']),
q('git-shared-revert','git',['Git · revert ortak geçmiş','Git · revert shared history'],'foundation','scenario',
 ['Paylaşılan commit’i geri al','Undo a shared commit'],
 ['Main’deki normal, merge olmayan bir commit yayımlandı; ekip arkadaşların çekti. Geçmişi yeniden yazmadan etkisini nasıl geri alırsın?','A normal non-merge commit on main has been published and pulled by teammates. How do you undo its effect without rewriting history?'],
 '',
 [['git revert <commit> ile ters değişikliği yeni commit olarak kaydet.','Use git revert <commit> to record the inverse change in a new commit.'],['Main’i reset --hard yapıp force push et.','Reset main --hard and force push.'],['Remote branch’i sil.','Delete the remote branch.'],['git fetch komutu commit’in etkisini geri alır.','git fetch undoes the commit’s effect.']],
 ['revert önceki değişikliği tersine çeviren yeni commit üretir; paylaşılan commit geçmişte kalır. Çakışma olasılığı yine vardır.','revert creates a new commit reversing the change while retaining shared history. Conflicts can still require resolution.'],
 ['Bu senaryoda geçmişin korunması gerekiyor.','This scenario requires preserving history.'],
 ['Git · revert','https://git-scm.com/docs/git-revert']),
q('git-tracked-ignore','git',['Git · gitignore tracked dosya','Git · gitignore tracked file'],'foundation','diagnosis',
 ['gitignore neden dosyayı gizlemiyor?','Why does gitignore not hide this file?'],
 ['config.local daha önce commit edildi. .gitignore’a eklense de değişikliklerde görünüyor. Yerel dosyayı koruyarak takibi durdurmak için ne gerekir?','config.local was already committed. Adding it to .gitignore does not hide changes. How do you stop tracking it while retaining the local file?'],
 '',
 [['git rm --cached config.local yap, ignore kuralını ve index değişikliğini commit et.','Run git rm --cached config.local and commit the ignore rule and index change.'],['Yalnızca .gitignore satırını tekrarla.','Repeat the .gitignore entry.'],['git fetch çalıştır; tracked dosyayı untrack eder.','Run git fetch to untrack the file.'],['Dosyayı yeniden adlandır; eski geçmişteki sırlar da silinir.','Rename it; this also removes secrets from old history.']],
 ['Ignore kuralları zaten takip edilen dosyayı index’ten çıkarmaz. --cached yerel dosyayı korur. İçinde sır varsa geçmişten kaldırma ve sırrı yenileme ayrıca gerekir.','Ignore rules do not untrack an indexed file. --cached preserves the local file. Existing secrets require separate history remediation and rotation.'],
 ['Çalışma klasörü ile Git index’i farklıdır.','The working directory and Git index are distinct.'],
 ['Git · gitignore','https://git-scm.com/docs/gitignore']),
q('git-rebase-abort','git',['Git · rebase conflict abort','Git · rebase conflict abort'],'foundation','scenario',
 ['Devam eden rebase’i iptal et','Abort an in-progress rebase'],
 ['Temiz çalışma ağacından rebase başlattın ve conflict geldi. Bu denemeyi bırakıp rebase öncesi branch durumuna dönmek istiyorsun. Hangi komut?','You started a rebase from a clean working tree and hit conflicts. You want to abandon the attempt and restore the pre-rebase branch state. Which command?'],
 '',
 [['git rebase --abort','git rebase --abort'],['git rebase --continue','git rebase --continue'],['git rebase --skip','git rebase --skip'],['git fetch --all','git fetch --all']],
 ['--abort devam eden rebase’i bırakıp başlangıç durumuna döner. --continue çözülmüş adımı sürdürür; --skip mevcut patch’i atlar.','--abort stops the current rebase and restores its starting state. --continue resumes after resolution; --skip omits the current patch.'],
 ['İptal, devam ve mevcut adımı atlamak farklı niyetlerdir.','Abort, continue and skipping a step express different intentions.'],
 ['Git · rebase','https://git-scm.com/docs/git-rebase']),
q('sql-null-filter','sql',['SQL · NULL IS NULL','SQL · NULL IS NULL'],'foundation','code-reading',
 ['NULL karşılaştırması','Comparing NULL'],
 ['deleted_at alanı NULL olan aktif kayıtlar aranıyor. Hangisi doğru filtre?','Active records have a NULL deleted_at. Which filter finds them?'],
 '',
 [['WHERE deleted_at IS NULL','WHERE deleted_at IS NULL'],['WHERE deleted_at = NULL','WHERE deleted_at = NULL'],["WHERE deleted_at = 'NULL'","WHERE deleted_at = 'NULL'"],['WHERE deleted_at <> NULL','WHERE deleted_at <> NULL']],
 ['NULL için = veya <> karşılaştırması unknown üretir; WHERE yalnız true olan satırları tutar. Eksik değer kontrolü IS NULL ile yapılır.','Comparisons with NULL using = or <> produce unknown; WHERE retains only true rows. Use IS NULL to test for a missing value.'],
 ['NULL bir metin veya sıradan eşitlik değeri değildir.','NULL is neither text nor an ordinary equality value.'],
 ['PostgreSQL · Comparison predicates','https://www.postgresql.org/docs/current/functions-comparison.html']),
q('sql-left-join-filter','sql',['SQL · LEFT JOIN ON WHERE','SQL · LEFT JOIN ON WHERE'],'intermediate','diagnosis',
 ['Siparişi olmayan kullanıcı kayboluyor','Users without orders disappear'],
 ['Tüm kullanıcılar ve varsa paid siparişleri listelenmeli. Aşağıdaki sorgu siparişi olmayan kullanıcıları siliyor. Nasıl düzeltirsin?','List all users and any paid orders they have. This query drops users with no orders. How do you fix it?'],
 "SELECT u.id, o.id\nFROM users u LEFT JOIN orders o ON o.user_id=u.id\nWHERE o.status='paid';",
 [["o.status='paid' koşulunu JOIN’in ON kısmına taşı.","Move o.status='paid' into the JOIN ON condition."],['LEFT JOIN yerine INNER JOIN kullan.','Replace LEFT JOIN with INNER JOIN.'],['WHERE koşulunu HAVING’e aynen taşı.','Move the unchanged WHERE condition to HAVING.'],['DISTINCT ekle; eksik kullanıcıları geri getirir.','Add DISTINCT to restore missing users.']],
 ['WHERE sağ taraftaki NULL satırları eler. Paid filtresini ON içinde kullanmak eşleşen siparişleri sınırlar ve eşleşmeyen sol kullanıcıları korur.','WHERE eliminates NULL-extended rows. Filtering paid orders in ON restricts matches while preserving unmatched users from the left side.'],
 ['Eşleşme filtresi ile sonuç filtresinin uygulandığı sırayı düşün.','Consider when join matching and final filtering occur.'],
 ['PostgreSQL · Table expressions','https://www.postgresql.org/docs/current/queries-table-expressions.html']),
q('sql-stable-page','sql',['SQL · pagination ORDER BY','SQL · pagination ORDER BY'],'intermediate','scenario',
 ['Sabit veride kararlı sayfalama','Stable pagination on unchanged data'],
 ['Veri değişmiyor; created_at değerleri tekrar edebiliyor ve id benzersiz. LIMIT/OFFSET sayfalarının sırası nasıl belirlenmeli?','Data is unchanged; created_at can tie and id is unique. How should LIMIT/OFFSET pages be ordered?'],
 '',
 [['ORDER BY created_at, id ile benzersiz bir sıra oluştur.','Use ORDER BY created_at, id for a unique ordering.'],['Sıralama olmadan LIMIT kullan.','Use LIMIT without ordering.'],['Yalnız created_at kullan; eşitlikler her zaman aynı sırada gelir.','Use only created_at; ties always arrive in the same order.'],['Daha büyük OFFSET, sıralamayı kararlı hale getirir.','A larger OFFSET makes ordering stable.']],
 ['LIMIT/OFFSET için benzersiz ORDER BY kararlı seçim sağlar. Bu cevap sabit veri varsayar; eşzamanlı ekleme/silme ayrı bir sayfalama problemidir.','A unique ORDER BY makes LIMIT/OFFSET selection stable. This assumes unchanged data; concurrent inserts or deletes introduce separate pagination concerns.'],
 ['Sıralama anahtarları eşit olduğunda hangi alan bağı çözer?','Which field breaks ties in the ordering?'],
 ['PostgreSQL · LIMIT/OFFSET','https://www.postgresql.org/docs/current/queries-limit.html']),
q('unity-local-position','unity',['Unity · localPosition world space','Unity · localPosition world space'],'foundation','code-reading',
 ['Parent ile dünya konumu','World position with a parent'],
 ['Parent dünya x=10 konumunda; dönüşü yok ve scale=(1,1,1). Child localPosition.x=2 ise child dünya x kaçtır?','The parent is at world x=10, with no rotation and scale=(1,1,1). If child localPosition.x=2, what is the child world x?'],
 '',
 [['12','12'],['2','2'],['10','10'],['20','20']],
 ['localPosition parent’a göredir. Verilen dönüş ve ölçek varsayımıyla dünya x=10+2=12 olur. Döndürme veya ölçekleme bu hesabı değiştirir.','localPosition is relative to the parent. Under the stated rotation and scale assumptions, world x is 10+2=12. Rotation or scaling changes that calculation.'],
 ['Önce yerel ve dünya koordinatını ayır.','First distinguish local and world coordinates.'],
 ['Unity 6 · Transform.localPosition','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Transform-localPosition.html']),
q('unity-event-unsubscribe','unity',['Unity · OnEnable OnDisable event','Unity · OnEnable OnDisable event'],'intermediate','diagnosis',
 ['Panel her açılışta iki kez güncelleniyor','A panel updates twice after reopening'],
 ['Panel OnEnable içinde global event’e abone oluyor, OnDisable içinde ayrılmıyor. Tekrar açılınca aynı handler çoğalıyor. Ne yaparsın?','A panel subscribes to a global event in OnEnable and never unsubscribes in OnDisable. Reopening duplicates its handler. What do you do?'],
 'void OnEnable() { Score.Changed += Refresh; }',
 [['OnDisable içinde aynı handler ile aboneliği kaldır; aç-kapat-aç akışını test et.','Unsubscribe the same handler in OnDisable; test enable-disable-enable.'],['OnEnable içinde ikinci bir abonelik daha ekle.','Add another subscription in OnEnable.'],['Refresh metodunu static yap; abonelikler otomatik silinir.','Make Refresh static; subscriptions will disappear automatically.'],['Paneli sadece görünmez yap; abonelik ömrü önemsizdir.','Only hide the panel; subscription lifetime does not matter.']],
 ['Aboneliği panelin etkin yaşam döngüsüyle eşleştirmek çoğalmayı önler. Aynı handler referansı kullanılmalı; etkin olmayan panelin gereksiz çağrı alması da engellenir.','Pairing subscription lifetime with the enabled panel avoids duplicates. Remove the same handler reference, also preventing needless calls to a disabled panel.'],
 ['Her abone olma yolunun bir ayrılma yolu var mı?','Does each subscription path have a matching unsubscribe path?'],
 ['Unity 6 · OnDisable','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/MonoBehaviour.OnDisable.html']),
q('unity-serialized-field','unity',['Unity · SerializeField Inspector','Unity · SerializeField Inspector'],'foundation','scenario',
 ['Private alanı Inspector’da düzenle','Edit a private field in the Inspector'],
 ['MonoBehaviour içindeki private int maxHealth Inspector’dan ayarlanabilmeli, diğer scriptlere public açılmamalı. Ne kullanırsın?','A private int maxHealth in a MonoBehaviour must be editable in the Inspector without becoming public to other scripts. What do you use?'],
 '',
 [['[SerializeField] private int maxHealth = 100;','[SerializeField] private int maxHealth = 100;'],['private static int maxHealth = 100;','private static int maxHealth = 100;'],['private const int maxHealth = 100;','private const int maxHealth = 100;'],['Yalnız bir public getter ekle; tüm property’ler otomatik serialize edilir.','Only add a public getter; all properties are automatically serialized.']],
 ['SerializeField, desteklenen private instance alanını Unity serialization sistemine dahil eder. Static ve const alanlar bu amaçla serialize edilmez; property’ler genel olarak alan gibi davranmaz.','SerializeField includes a supported private instance field in Unity serialization. Static and const fields are not serialized this way; properties generally do not behave like fields.'],
 ['C# erişim düzeyi ile Unity serialization ayrı özelliklerdir.','C# visibility and Unity serialization are separate concerns.'],
 ['Unity 6 · SerializeField','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/SerializeField.html']),
q('k8s-requests-limits','devops',['Kubernetes · requests limits','Kubernetes · requests limits'],'intermediate','scenario',
 ['Pod hangi düğüme yerleşir?','Which node can host the Pod?'],
 ['Container için memory request=256Mi ve limit=512Mi. Scheduler temel kaynak yerleştirmesinde hangi değeri kullanır?','A container has memory request=256Mi and limit=512Mi. Which value does the scheduler use for basic resource placement?'],
 '',
 [['Request olan 256Mi; limit çalışma sırasında uygulanan üst sınırdır.','The 256Mi request; the limit is enforced during execution.'],['Her zaman 512Mi limit.','Always the 512Mi limit.'],['Container’ın henüz ölçülmemiş gelecek kullanımı.','The container’s unmeasured future usage.'],['Image dosyasının disk boyutu.','The image’s disk size.']],
 ['Scheduler yerleştirmeyi kaynak request değerleriyle değerlendirir. Memory limit’i aşmak OOM sonlandırmasına yol açabilir; request bir kullanım tavanı değildir.','The scheduler considers resource requests for placement. Exceeding a memory limit can cause OOM termination; a request is not a usage cap.'],
 ['Kaynak talebi ile kullanım sınırını ayır.','Separate requested resources from enforced limits.'],
 ['Kubernetes · Resource management','https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/']),
q('ci-lockfile','devops',['CI · npm ci lockfile','CI · npm ci lockfile'],'foundation','diagnosis',
 ['CI’da lockfile uyuşmazlığı','A lockfile mismatch in CI'],
 ['package.json değişti; package-lock.json güncellenmedi. CI npm ci ile hata veriyor. Doğru yaklaşım hangisi?','package.json changed but package-lock.json did not. CI fails at npm ci. What is the right response?'],
 '',
 [['Bağımlılık değişikliğini incele; lockfile’ı geliştirme ortamında güncelleyip ikisini birlikte commit et.','Review the dependency change, update the lockfile in development and commit both files.'],['CI’da lockfile’ı her çalışmada sil.','Delete the lockfile on every CI run.'],['npm ci lockfile’ı sessizce güncellemelidir; hatayı yok say.','npm ci should silently update the lockfile; ignore the error.'],['Node_modules klasörünü elle kopyala; lockfile gereksizdir.','Copy node_modules manually; no lockfile is needed.']],
 ['npm ci manifest ile lockfile tutarlı değilse durur ve lockfile’ı değiştirmez. Bağımlılık çözümünü önceden kaydetmek CI kurulumunu tekrar üretilebilir kılar.','npm ci fails on a manifest/lockfile mismatch and does not rewrite the lockfile. Recording resolution beforehand makes CI installation reproducible.'],
 ['CI mevcut bağımlılık kararını uygulasın; yeni karar üretmesin.','CI should apply the recorded dependency decision.'],
 ['npm · npm ci','https://docs.npmjs.com/cli/v11/commands/npm-ci/']),
q('docker-localhost','devops',['Docker · localhost container ağı','Docker · localhost container network'],'foundation','diagnosis',
 ['Container içindeki localhost','Localhost inside a container'],
 ['Varsayılan ayrı ağdaki web container’ı 127.0.0.1:5432 ile ayrı database container’ına bağlanamıyor. localhost burada nereyi gösterir?','A web container on a default isolated network cannot reach a separate database container at 127.0.0.1:5432. What does localhost refer to here?'],
 '',
 [['Web container’ının kendi ağ alanını; ortak kullanıcı tanımlı ağda database servis adını kullan.','The web container’s own network namespace; use the database service name on a shared user-defined network.'],['Her zaman Docker host’unu.','Always the Docker host.'],['Aynı bilgisayardaki bütün container’ları.','All containers on the same computer.'],['Her zaman internetteki production veritabanını.','Always the production database on the internet.']],
 ['Ayrı ağ namespace’lerinde loopback paylaşılmaz. Ortak kullanıcı tanımlı ağda servis/container adı ve doğru portla bağlan; localhost’u herkese açık yayınlamak çözüm değildir.','Separate network namespaces do not share loopback. Connect using the service/container name and port on a shared user-defined network; public exposure is not required.'],
 ['İstek hangi ağ alanından çıkıyor?','Which network namespace sends the request?'],
 ['Docker · Networking','https://docs.docker.com/engine/network/']),
q('http-401-403','api',['HTTP · 401 403 yetki','HTTP · 401 403 authorization'],'foundation','scenario',
 ['Kimlik ile yetkiyi ayır','Separate authentication and authorization'],
 ['API token’ı geçerli ve kullanıcı tanınıyor; fakat yönetici işlemi için rolü yetersiz. Standart anlamıyla hangi durum kodu uygun?','The API token is valid and the user is identified, but lacks the role for an admin operation. Which status fits its standard meaning?'],
 '',
 [['403 Forbidden','403 Forbidden'],['401 Unauthorized; kullanıcı tanınsa da her rol hatası 401’dir.','401 Unauthorized; every role failure is 401 even for an identified user.'],['200 OK; hata body içinde gizlenmeli.','200 OK; hide the error in the body.'],['301 Moved Permanently','301 Moved Permanently']],
 ['401 geçerli kimlik doğrulama eksikliğini belirtir. Bu senaryoda kimlik geçerli, erişim reddediliyor: 403. Yetki denetimi sunucuda yapılmalıdır.','401 indicates missing valid authentication. Here identity is valid but access is denied: 403. Authorization must be checked on the server.'],
 ['Kullanıcı kim ve bu işlemi yapabilir mi soruları farklıdır.','Who is the user, and may they perform this action, are different questions.'],
 ['MDN · HTTP status codes','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status']),
q('http-private-cache','api',['HTTP · Cache-Control private no-store','HTTP · Cache-Control private no-store'],'intermediate','scenario',
 ['Hesap sayfasını cache’ten koru','Keep account responses out of caches'],
 ['Hassas hesap yanıtı tarayıcı veya ortak cache’te saklanmamalı. Hangi Cache-Control direktifi bu saklamayı yasaklar?','A sensitive account response must not be stored by browser or shared caches. Which Cache-Control directive prohibits storage?'],
 '',
 [['no-store','no-store'],['public, max-age=86400','public, max-age=86400'],['private; bu tek başına tarayıcıda saklamayı da yasaklar.','private; this alone also prohibits browser storage.'],['no-cache; bu direktif saklamayı bütünüyle yasaklar.','no-cache; this directive prohibits all storage.']],
 ['no-store cache saklamasını yasaklar. private yalnız ortak cache’i dışlar; no-cache saklanan yanıtın yeniden kullanılmadan doğrulanmasını ister. Bunlar yetkilendirmenin yerine geçmez.','no-store prohibits cache storage. private excludes shared caches; no-cache requires validation before reuse. None of these replaces authorization.'],
 ['Saklamamak ile kullanmadan önce doğrulamak aynı şey değildir.','Not storing differs from validating before reuse.'],
 ['MDN · Cache-Control','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control']),
q('http-retry-after','api',['HTTP · 429 Retry-After','HTTP · 429 Retry-After'],'foundation','code-reading',
 ['İstek sınırına saygılı yeniden deneme','A rate-limit-aware retry'],
 ['Yanıt 429 ve Retry-After: 30. Değer saniye biçiminde. Aynı isteği otomatik deneyecek istemci nasıl davranmalı?','The response is 429 with Retry-After: 30, in seconds form. How should a client automatically retrying the same request behave?'],
 'HTTP/1.1 429 Too Many Requests\nRetry-After: 30',
 [['En az 30 saniye bekle, deneme sayısını sınırla ve isteğin yeniden denemeye uygunluğunu kontrol et.','Wait at least 30 seconds, bound retry attempts and check whether retrying the operation is safe.'],['30 eşzamanlı istek gönder.','Send 30 concurrent requests.'],['30 milisaniye sonra sınırsız tekrarla.','Retry indefinitely after 30 milliseconds.'],['429’u başarılı yanıt say.','Treat 429 as success.']],
 ['Bu biçimde Retry-After bekleme süresini saniye olarak verir. Sınırı yok sayan yoğun retry yükü artırır; yan etki üreten işlemlerde tekrar güvenliği ayrıca gerekir.','In this form Retry-After gives seconds to wait. Aggressive retries increase load; operations with side effects also require retry-safety checks.'],
 ['Başlıkta sayı bir istek adedi değil, bekleme süresi.','The header value is a delay, not a request count.'],
 ['MDN · Retry-After','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Retry-After']),
q('test-regression','testing',['Test · regresyon beklenen gerçek','Testing · regression expected actual'],'foundation','diagnosis',
 ['Hata düzeltmesini kanıtlayan test','A test that proves the bug fix'],
 ['İndirim fonksiyonu %0 indirimde toplamı yanlışlıkla sıfırlıyor. Düzeltmeden önce hangi regresyon testi en doğrudan kanıt üretir?','A discount function incorrectly zeroes the total for a 0% discount. Before fixing it, which regression test gives direct evidence?'],
 '',
 [['ApplyDiscount(80, 0) sonucunu 80 bekleyen, önce kırmızı sonra yeşil olan test.','A test expecting ApplyDiscount(80, 0) to return 80, failing before and passing after the fix.'],['Fonksiyonun exception atmadığını kontrol etmek yeterli.','Only check that the function does not throw.'],['Testte beklenen değeri mevcut yanlış çıktıdan hesapla.','Calculate the expected value from the current incorrect output.'],['Yalnız %20 indirim durumunu test et.','Test only a 20% discount.']],
 ['Regresyon testi hatayı tetikleyen girdiye ve sözleşmeden gelen bağımsız beklenen değere ihtiyaç duyar. Yalnız exception olmaması iş sonucunun doğruluğunu kanıtlamaz.','A regression test needs the triggering input and an independently specified expected value. Absence of exceptions does not establish a correct business result.'],
 ['Hangi girdi hatayı tekrar üretir, doğru sonuç hangi sözleşmeden gelir?','Which input reproduces the bug, and what contract determines the correct result?'],
 ['Microsoft · Unit testing practices','https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices']),
q('test-expiry-clock','testing',['Test · TimeProvider sahte saat','Testing · TimeProvider fake clock'],'intermediate','scenario',
 ['Süre dolumu testini hızlandır','Make expiration tests fast'],
 ['Token 5 dakika sonra geçersiz oluyor. Test gerçek hayatta 5 dakika bekliyor ve bazen hata veriyor. En uygun tasarım hangisi?','A token expires after 5 minutes. The test waits 5 real minutes and sometimes fails. Which design is appropriate?'],
 '',
 [['Saati TimeProvider gibi enjekte edilebilir bir kaynaktan al; testte zamanı kontrollü ilerlet.','Use an injectable clock such as TimeProvider and advance controlled time in tests.'],['Beklemeyi 6 dakikaya çıkar.','Increase the wait to 6 minutes.'],['Production timeout’unu yalnız test geçsin diye kaldır.','Remove production expiration just to pass the test.'],['Sonucu yalnız bugünün tarihiyle karşılaştır.','Compare the result only to today’s date.']],
 ['Kontrollü saat testin duvar saatine ve uzun beklemeye bağımlılığını kaldırır. Süre dolumundan hemen önce ve sınırda davranış ayrıca doğrulanabilir.','A controlled clock removes reliance on wall-clock timing and long waits. Test behavior immediately before expiration and at the boundary.'],
 ['Testin kontrol edemediği dış bağımlılık burada zaman.','Time is the external dependency the test cannot currently control.'],
 ['Microsoft · TimeProvider','https://learn.microsoft.com/en-us/dotnet/standard/datetime/timeprovider-overview']),
q('test-data-boundaries','testing',['Test · sınır değeri DataRow','Testing · boundary value DataRow'],'foundation','scenario',
 ['Kabul aralığını veriyle test et','Test an accepted range with data'],
 ['Ürün adedi yalnız 1 ile 100 arasında, iki sınır dahil kabul ediliyor. Hangi girdi grubu iki sınırı ve hemen dışını kapsar?','An item count is accepted only from 1 through 100 inclusive. Which inputs cover both boundaries and their immediate outside values?'],
 '',
 [['0, 1, 100, 101','0, 1, 100, 101'],['10, 20, 30, 40','10, 20, 30, 40'],['Yalnız 50','Only 50'],['Yalnız 1 ve 100; dış değer testine gerek yok.','Only 1 and 100; outside values need no tests.']],
 ['0 ve 101 reddedilmeli; 1 ve 100 kabul edilmeli. Veri güdümlü testte her girdinin beklenen sonucu ayrıca verilir; daha fazla davranış için ek vakalar gerekir.','Reject 0 and 101; accept 1 and 100. Provide the expected outcome per data-driven case; other behaviors still need additional cases.'],
 ['Her sınırın içinde ve bir adım dışında ne olmalı?','What should happen at each boundary and one step outside?'],
 ['Microsoft · MSTest data-driven tests','https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-writing-tests']),
q('structure-binary-search','structures',['Veri yapıları · binary search bisect','Data structures · binary search bisect'],'foundation','code-reading',
 ['İkili aramanın önkoşulu','The precondition for binary search'],
 ['bisect_left, sıralanmamış [9, 1, 5] üzerinde doğru yerleştirme konumu bulmak için kullanılacak. Önce ne sağlanmalı?','bisect_left is being used to find an insertion point in unsorted [9, 1, 5]. What must be established first?'],
 'items = [9, 1, 5]\npos = bisect_left(items, 4)',
 [['Liste aramanın kullandığı aynı sıralama kuralına göre sıralanmış olmalı.','The list must be sorted using the same ordering as the search.'],['Listenin uzunluğu tek sayı olmalı.','The list length must be odd.'],['Bütün sayılar pozitif olmalı.','All numbers must be positive.'],['bisect_left önce listeyi kendisi sıralar.','bisect_left sorts the list first.']],
 ['Bisection sıralı bir dizi varsayar; bisect_left listeyi sıralamaz. Bu önkoşul olmadan sonuç doğru sıralı yerleşim anlamına gelmez.','Bisection assumes a sorted sequence; bisect_left does not sort it. Without that precondition, the result is not a valid sorted insertion point.'],
 ['Yarıları eleyebilmek için hangi düzen gerekiyor?','What ordering permits discarding half the search space?'],
 ['Python · bisect','https://docs.python.org/3/library/bisect.html']),
q('structure-deque-ends','structures',['Veri yapıları · deque çift uç','Data structures · deque both ends'],'foundation','scenario',
 ['Her iki uçtan işleme','Processing both ends'],
 ['İşler çoğunlukla sona ekleniyor, baştan alınıyor; bazen acil işi başa eklemek gerekiyor. Python’da hangi yapı bu uç işlemleri için uygundur?','Jobs are appended at the right and removed from the left; urgent jobs sometimes need insertion at the left. Which Python structure suits these end operations?'],
 '',
 [['collections.deque','collections.deque'],['Yalnız pop() sunan stack arayüzü.','A stack interface exposing only pop().'],['Sırasız set; her zaman ekleme sırasını garanti eder.','An unordered set; it always guarantees insertion order.'],['Tek bir int sayaç.','A single int counter.']],
 ['deque append, appendleft ve popleft gibi iki uç işlemlerini destekler. Bu modelde aradan rastgele erişim değil, uçlardan ekleme/çıkarma önemlidir.','deque supports operations such as append, appendleft and popleft. This model needs end insertion/removal rather than arbitrary middle access.'],
 ['İki uçtan ekleme ve çıkarma ihtiyacını birlikte düşün.','Consider insertion and removal at both ends.'],
 ['Python · deque','https://docs.python.org/3/library/collections.html#collections.deque']),
q('structure-set-duplicates','structures',['Veri yapıları · set benzersizlik','Data structures · set uniqueness'],'foundation','code-reading',
 ['Tekrarları çıkarınca ne kalır?','What remains after deduplication?'],
 ['Bu set hakkında hangi ifade doğrudur?','Which statement about this set is correct?'],
 'ids = set([4, 4, 9])',
 [['İki farklı eleman içerir; iterasyon sırası bu kullanımla garanti edilmez.','It contains two distinct elements; this use does not guarantee iteration order.'],['Üç eleman içerir; tekrarlar korunur.','It contains three elements, retaining duplicates.'],['Her zaman önce 4 sonra 9 döner.','It always iterates 4 then 9.'],['Tekrar olduğu için exception atar.','It throws because a duplicate exists.']],
 ['Set tekrar eden eşit değerleri tek elemanda toplar ve sıralı bir dizi sözleşmesi sunmaz. Sıra gerekiyorsa onu ayrıca modelle.','A set keeps one instance of equal repeated values and does not provide an ordered-sequence contract. Model ordering separately when required.'],
 ['Benzersizlik ve sıralama ayrı gereksinimlerdir.','Uniqueness and ordering are separate requirements.'],
 ['Python · set','https://docs.python.org/3/builtins/stdtypes.html#set-types-set-frozenset']),
q('ai-preprocess-leakage','ai',['AI · veri sızıntısı train test leakage','AI · preprocessing train test leakage'],'intermediate','diagnosis',
 ['Test verisi eğitime sızıyor','Test information leaks into training'],
 ['StandardScaler tüm veri üzerinde fit ediliyor, sonra train/test ayrılıyor. Ölçümü düzeltmek için ne yapılmalı?','StandardScaler is fitted on the full dataset before the train/test split. How should this evaluation be corrected?'],
 '',
 [['Önce ayır; scaler’ı yalnız train üzerinde fit et, aynı scaler ile test’i transform et.','Split first; fit the scaler only on train, then transform test with that fitted scaler.'],['Test verisine ayrı scaler fit et; iki ölçek birbirinden bağımsız olsun.','Fit a separate scaler on test so the scales are independent.'],['Test etiketlerini de train’e ekle.','Add the test labels to train.'],['Test skorunu daha fazla ondalıkla göster.','Display the test score with more decimals.']],
 ['Tüm veriyle fit, test dağılımından öğrenerek değerlendirmeyi kirletir. Train’de öğrenilen dönüşüm test’e değiştirilmeden uygulanmalıdır.','Fitting on all data learns from the test distribution and contaminates evaluation. Apply the transformation learned on train unchanged to test.'],
 ['Fit hangi veriden bilgi öğreniyor?','Which data does fit learn from?'],
 ['scikit-learn · Data leakage','https://scikit-learn.org/1.9/common_pitfalls.html']),
q('ai-schema-business-rule','ai',['AI · structured outputs şema doğrulama','AI · structured outputs schema validation'],'intermediate','scenario',
 ['Şemaya uymak yeterli mi?','Is matching the schema enough?'],
 ['Model şemaya uygun {amount: -50} üretiyor; uygulamada tutar pozitif olmalı. Kaydetmeden önce ne gerekir?','The model produces schema-shaped {amount: -50}, but the application requires a positive amount. What is needed before saving?'],
 '',
 [['İş kuralını sunucuda doğrula; ret veya eksik yanıt durumunu da ele al.','Validate the business rule on the server and handle refusal or incomplete responses.'],['Şemaya uyan her çıktı iş kuralına da uyar.','Every schema-shaped output also meets business rules.'],['Model güven skoru yüksekse doğrulamayı atla.','Skip validation when model confidence is high.'],['Eksi işaretini istemcide gizle.','Hide the minus sign in the client.']],
 ['Yapısal uygunluk her alanın iş açısından geçerli olduğunu kanıtlamaz. Şema kısıtlarına ek olarak domain doğrulaması ve başarısız yanıt akışı gerekir.','Structural conformance does not establish domain validity. Domain checks and failure handling are needed alongside schema constraints.'],
 ['Veri biçimi ile iş anlamını ayır.','Distinguish data shape from business meaning.'],
 ['OpenAI · Structured outputs','https://developers.openai.com/api/docs/guides/structured-outputs']),
q('ai-context-budget','ai',['AI · context window token bütçesi','AI · context window token budget'],'foundation','scenario',
 ['Bağlam penceresi doluyor','The context window is filling up'],
 ['Sohbet geçmişi ve retrieval belgeleri büyüdükçe istek context sınırına ulaşıyor. Hangi yaklaşım uygundur?','Conversation history and retrieved documents grow until a request reaches the context limit. Which approach is suitable?'],
 '',
 [['Girdi ve çıktı bütçesini birlikte planla; ilgili belgeleri seç, eski bağlamı kontrollü özetle veya azalt.','Budget input and output together; select relevant documents and deliberately summarize or reduce older context.'],['Daha uzun bir HTTP timeout context kapasitesini artırır.','A longer HTTP timeout increases context capacity.'],['Bütün belgeleri her istekte çoğalt.','Duplicate every document on every request.'],['Context sınırı yalnız yanıt karakterlerini sayar.','The context limit counts only answer characters.']],
 ['Bağlam bütçesi yalnız geçmiş mesajlar değildir; çıktı ve modele göre reasoning token’ları da yer kaplar. Azaltma sırasında gerekli talimat ve kanıtları koru.','The context budget includes more than history: output and, depending on the model, reasoning tokens also consume space. Preserve necessary instructions and evidence when reducing context.'],
 ['Gönderilen içerik ile üretilecek yanıta birlikte yer ayır.','Reserve room for both submitted content and the generated response.'],
 ['OpenAI · Conversation state','https://developers.openai.com/api/docs/guides/conversation-state']),
q('airflow-fixed-partition','data',['Veri mühendisliği · Airflow data interval backfill','Data engineering · Airflow data interval backfill'],'intermediate','diagnosis',
 ['Backfill yanlış günü okuyor','A backfill reads the wrong day'],
 ['Geçen ayın günlük Airflow görevi bugün yeniden çalıştırılıyor. Kaynak bölümünü now() ile seçtiği için bugünü okuyor. Ne değişmeli?','Last month’s daily Airflow task is rerun today. It selects its source partition with now() and reads today instead. What should change?'],
 '',
 [['İşlenecek partition’ı run’ın data interval değerinden üret; aynı run yeniden aynı dönemi okusun.','Derive the partition from the run’s data interval so reruns read the same period.'],['Her çalıştırmada en yeni partition’ı seç.','Always select the newest partition.'],['Backfill’i kapat; veri sorunu çözülür.','Disable backfills to fix the data.'],['Log tarihini eski güne çevir ama sorguyu değiştirme.','Change the log date but leave the query unchanged.']],
 ['Duvar saati tekrar çalıştırmada değişir. Run’ın veri aralığı işlenecek dönemi sabitler; tarih dilimi ve sınırlar da açık belirlenmelidir.','Wall-clock time changes between reruns. The run’s data interval identifies the intended period; timezone and interval boundaries also need explicit definitions.'],
 ['Çalıştırılma zamanı ile işlenen veri dönemi aynı olmayabilir.','Execution time may differ from the period being processed.'],
 ['Apache Airflow · Best practices','https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html']),
q('beam-late-events','data',['Veri mühendisliği · event time watermark late data','Data engineering · event time watermark late data'],'intermediate','scenario',
 ['Geç gelen olay hangi pencereye ait?','Which window owns a late event?'],
 ['Olay zamanı 10:02, sisteme gelişi 10:08. Beş dakikalık event-time pencerelerinde toplam tutuluyor. En doğru politika hangisi?','An event occurred at 10:02 but arrives at 10:08. Totals use five-minute event-time windows. Which policy is appropriate?'],
 '',
 [['10:00–10:05 penceresine ait olduğunu koru; allowed lateness ve güncelleme/atılma politikasını açık tanımla.','Preserve its 10:00–10:05 window and explicitly define allowed lateness and update/drop policy.'],['Olay zamanını sessizce 10:08 yap.','Silently change event time to 10:08.'],['Watermark bütün olayların ulaştığının kesin kanıtıdır.','A watermark proves every event has arrived.'],['Geç olayları saymadan her zaman doğru toplam garanti et.','Guarantee exact totals while never counting late events.']],
 ['Event time olayın ait olduğu dönemi belirler. Watermark bir ilerleme tahminidir; geç veri için saklama, tetikleme ve sonuç düzeltme kararı gerekir.','Event time identifies the event’s period. A watermark estimates progress; late data requires decisions about retention, triggering and corrected results.'],
 ['Olayın oluştuğu an ile işlendiği anı ayır.','Separate occurrence time from processing time.'],
 ['Apache Beam · Late data','https://beam.apache.org/documentation/programming-guide/#watermarks-and-late-data']),
q('avro-reader-default','data',['Veri mühendisliği · Avro schema evolution default','Data engineering · Avro schema evolution default'],'intermediate','scenario',
 ['Eski kayıt yeni alanı içermiyor','An old record lacks a new field'],
 ['Eski Avro writer şemasında country yok. Yeni reader şemasında country:string eklendi. Eski kayıtları okumak için bu yeni alan nasıl tanımlanmalı?','An old Avro writer schema has no country. The new reader adds country:string. How should this new field be defined to read old records?'],
 '',
 [['Reader alanına türüyle uyumlu default değer ekle; eski kayıt uyumluluğunu test et.','Give the reader field a type-compatible default and test old-record compatibility.'],['Reader’a zorunlu alan eklemek her zaman otomatik uyumludur.','Adding a required reader field is always compatible.'],['Default, yeni writer’ın alanı yazmasını her durumda gereksiz kılar.','A default always lets new writers omit the field.'],['Eski kayıtların byte dizisine elle metin ekle.','Append text manually to the old record bytes.']],
 ['Reader’da olup writer’da olmayan alan çözülürken reader default’u kullanılır; yoksa uyumluluk hatası olabilir. Default, encoding sırasında alanı isteğe bağlı yapmaz.','A reader default resolves a reader field absent from the writer; without one resolution can fail. A default does not make the field optional during encoding.'],
 ['Okuma sırasında eksik alanın değeri nereden gelecek?','Where will the missing field’s value come from during reading?'],
 ['Apache Avro 1.12 · Schema resolution','https://avro.apache.org/docs/1.12.0/specification/#schema-resolution']),
q('android-lifecycle-flow','mobile',['Android · StateFlow repeatOnLifecycle','Android · StateFlow repeatOnLifecycle'],'intermediate','diagnosis',
 ['Gizli ekranda Flow güncellemesi','Flow updates a hidden screen'],
 ['Activity UI’si StateFlow’u doğrudan launch içinde collect ediyor; ekran durunca toplama sürüyor. Görünür UI için önerilen yaklaşım hangisi?','An Activity collects StateFlow directly in launch and keeps collecting when stopped. What is the recommended visible-UI approach?'],
 '',
 [['lifecycleScope içinde repeatOnLifecycle(STARTED) ile collect et.','Collect inside repeatOnLifecycle(STARTED) in lifecycleScope.'],['GlobalScope kullan; UI yaşam süresinden tamamen ayır.','Use GlobalScope to detach it from UI lifetime.'],['Her collect öncesi Thread.sleep çağır.','Call Thread.sleep before each collection.'],['Flow’u process boyunca aynı Activity referansında tut.','Keep the Flow tied to the same Activity reference for the whole process.']],
 ['repeatOnLifecycle, STARTED durumunda toplar ve daha düşük durumda toplama coroutine’ini iptal eder. UI tekrar başlarsa yeniden toplama başlatılır.','repeatOnLifecycle collects while STARTED and cancels the collection coroutine below that state. Collection restarts when the UI starts again.'],
 ['UI’nin görünürlüğü ile veri kaynağının ömrü aynı değildir.','UI visibility and the data source lifetime differ.'],
 ['Android · StateFlow lifecycle','https://developer.android.com/kotlin/flow/stateflow-and-sharedflow']),
q('android-work-constraint','mobile',['Android · WorkManager network constraint','Android · WorkManager network constraint'],'foundation','scenario',
 ['Bağlantı gelince dosya yükle','Upload a file when connectivity returns'],
 ['Uygulama kapansa da ertelenebilir dosya yükleme planı saklanmalı; ağ yokken çalışmamalı. Hangi araç uygundur?','A deferrable file upload must remain scheduled after the app closes and wait for network connectivity. Which tool fits?'],
 '',
 [['Network constraint içeren WorkManager işi; tam saniyede çalışacağını varsayma.','A WorkManager request with a network constraint; do not assume exact execution time.'],['Activity içinde Timer; process bitse de kesin çalışır.','An Activity Timer; it certainly survives process death.'],['UI thread’de ağ gelene kadar busy loop.','A busy loop on the UI thread until connectivity returns.'],['Her ekranda yeni sınırsız thread aç.','Create unlimited new threads on each screen.']],
 ['WorkManager kalıcı, ertelenebilir işleri constraints ile planlar. Çalışma zamanı sistem ve kısıtlara bağlıdır; tam zamanlı alarm veya sonsuz çalışma garantisi değildir.','WorkManager schedules persistent deferrable work with constraints. Timing depends on the system and constraints; it is not an exact alarm or an unlimited-execution guarantee.'],
 ['Ertelenebilir kalıcı iş ile ekrana bağlı kısa işlem farklıdır.','Persistent deferrable work differs from a short screen-bound operation.'],
 ['Android · Work requests','https://developer.android.com/develop/background-work/background-tasks/persistent/getting-started/define-work']),
q('mobile-icon-accessibility','mobile',['Mobil · erişilebilirlik contentDescription','Mobile · accessibility contentDescription'],'foundation','scenario',
 ['Simgeli düğmeyi ekran okuyucuya anlat','Describe an icon button to a screen reader'],
 ['Yalnız çöp kutusu simgesi olan sil düğmesi ekran okuyucuda isimsiz geliyor. Ne eklersin?','A delete button contains only a trash icon and has no name in the screen reader. What should be added?'],
 '',
 [['Yerelleştirilmiş, eylemi açıklayan erişilebilir etiket: örneğin Kaydı sil.','A localized accessible action label, such as Delete record.'],['Yalnız rengini kırmızıya çevir.','Only change its color to red.'],['İkon dosyasının adını otomatik etiket kabul et.','Treat the icon filename as its label.'],['Düğmeyi erişilebilirlik ağacından gizle.','Hide the button from the accessibility tree.']],
 ['Etkileşimli görsel kontrolün anlamlı erişilebilir adı olmalıdır. Renk ve dosya adı yeterli değildir; dekoratif görsellerle eylem düğmelerini ayrı değerlendir.','An interactive visual control needs a meaningful accessible name. Color and filenames are insufficient; distinguish decorative imagery from actionable buttons.'],
 ['Görseli göremeyen kullanıcı hangi işlemi başlatacağını bilmeli.','A user who cannot see the icon must know which action it performs.'],
 ['Android · Accessibility principles','https://developer.android.com/guide/topics/ui/accessibility/principles']),
q('game-server-authority','game',['Oyun · multiplayer server authority','Game · multiplayer server authority'],'intermediate','scenario',
 ['İstemci kendi ödülünü belirliyor','A client chooses its own reward'],
 ['Çok oyunculu oyunda istemci coins=9999 diye mesaj gönderiyor. Sunucu hangi sınırı uygulamalı?','In a multiplayer game a client sends coins=9999. What boundary should the server enforce?'],
 '',
 [['İstemciden eylem isteği al; kimliği, yetkiyi ve oyun kuralını doğrulayıp ödülü sunucuda hesapla.','Accept an action request, validate identity, authority and game rules, then compute rewards on the server.'],['Mesaj güvenilir RPC ile geldiği için sayıyı doğrudan kabul et.','Accept the number because it arrived via reliable RPC.'],['İstemci UI’sinde maksimum değeri gizlemek yeterli.','Hiding the maximum value in client UI is enough.'],['Bütün client’ları her state’in otoritesi yap.','Make every client authoritative for every state.']],
 ['Ağ mesajının ulaşması içeriğin doğru olduğunu kanıtlamaz. Otorite sınırı ve sunucu kontrolleri gerekir; güvenilir taşıma hileyi önlemez.','Message delivery does not establish trustworthy contents. Authority boundaries and server checks are needed; reliable transport does not prevent cheating.'],
 ['Transport güvenilirliği ile iş verisinin güvenilirliği farklıdır.','Transport reliability differs from trusting business data.'],
 ['Godot · Multiplayer authority','https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html']),
q('game-fast-collision','game',['Oyun · Unity CCD tunneling','Game · Unity CCD tunneling'],'intermediate','diagnosis',
 ['Hızlı mermi duvardan geçiyor','A fast projectile tunnels through a wall'],
 ['3D Rigidbody mermi bir fizik adımında ince duvarın ötesine geçiyor; discrete detection çarpışmayı kaçırıyor. En anlamlı inceleme hangisi?','A 3D Rigidbody projectile crosses a thin wall within one physics step and discrete detection misses it. What is a useful next investigation?'],
 '',
 [['Uygun continuous collision detection modunu collider ve hareket türüne göre dene; doğruluğu ve maliyeti ölç.','Try a suitable continuous collision detection mode for the collider and motion; measure correctness and cost.'],['Yalnız render FPS’ini artır; fizik örneklemesi kesin çözülür.','Only raise rendering FPS; physics sampling is guaranteed fixed.'],['Collider’ı kaldır.','Remove the collider.'],['Bütün nesnelerde en pahalı modu ölçmeden aç.','Enable the most expensive mode on every object without measuring.']],
 ['CCD adımlar arasındaki çarpışmaları yakalamaya yardımcı olabilir. Modların desteklediği hareket/collider türleri ve maliyeti farklıdır; tüm kaçırmaları koşulsuz çözmez.','CCD can help detect collisions between steps. Modes differ in supported motion/collider types and cost; they do not unconditionally solve every missed collision.'],
 ['Görüntü karesi ile fizik adımı ayrı saatlerdir.','Rendering frames and physics steps run on different clocks.'],
 ['Unity 6 · Continuous collision','https://docs.unity3d.com/6000.0/Documentation/Manual/ContinuousCollisionDetection.html']),
q('game-rng-replay','game',['Oyun · random seed replay','Game · random seed replay'],'foundation','scenario',
 ['Rastgele hatayı yeniden üret','Reproduce a randomness-dependent bug'],
 ['Aynı engine sürümünde aynı random çağrı sırasını kullanarak loot hatasını yeniden üretmek istiyorsun. Ne kaydetmelisin?','You want to reproduce a loot bug with the same engine version and random call sequence. What should you record?'],
 '',
 [['RNG seed’ini ve gerekirse state/çağrı sırasını kaydet; tüm oyunun deterministik olduğunu varsayma.','Record the RNG seed and, as needed, state/call order; do not assume the entire game is deterministic.'],['Her denemede yeni randomize çağır.','Call randomize with fresh randomness on every attempt.'],['Yalnız ekran çözünürlüğünü kaydet.','Record only the screen resolution.'],['Seed tek başına her engine sürümünde aynı fizik sonucunu garanti eder.','A seed alone guarantees identical physics across every engine version.']],
 ['Aynı RNG seed’i aynı çağrı sırasıyla rastgele diziyi tekrar üretmeye yardımcı olur. Fizik, thread sırası ve sürüm farklılıkları ayrı determinism kaynaklarıdır.','The same RNG seed and call order help reproduce a random sequence. Physics, thread ordering and version changes are separate sources of nondeterminism.'],
 ['Rastgele sayı dizisinin tekrarı, tüm simülasyonun tekrarı değildir.','Replaying random numbers is not the same as replaying the whole simulation.'],
 ['Godot · RandomNumberGenerator','https://docs.godotengine.org/en/stable/classes/class_randomnumbergenerator.html'])
];

export function createBankTasks() {
  return rows.map((row, index) => {
    // Correct choices occupy all four positions, rather than teaching a fixed answer position.
    const answer = index % 4;
    const options = row.options.map((_, i) => bi(...row.options[(i - answer + 4) % 4]));
    return {
      id: 'bank-' + row.id + '-20261008', area: row.area, version: '2026-10-08.1',
      kind: 'multiple-choice', minutes: row.difficulty === 'foundation' ? 2 : 3,
      topic: bi(...row.topic), tags: row.topic, difficulty: row.difficulty, format: row.format,
      title: bi(...row.title), prompt: bi(...row.prompt), code: row.code,
      options, answer, explain: bi(...row.explain), hint: bi(...row.hint),
      checks: [
        bi('Sonucumu sorudaki belirleyici kanıtla ilişkilendirdim.', 'I linked my conclusion to decisive evidence in the question.'),
        bi('Yanlış seçeneklerden birinin neden çalışmadığını açıkladım.', 'I explained why one incorrect option would not work.')
      ],
      source: {label: row.source[0], url: row.source[1], checkedAt: '2026-10-08',
        note: 'Original RealDev scenario based on primary technical documentation; no source exercise text was copied.'}
    };
  });
}
