// Versioned tasks: changing a task's meaning requires a new id/version.
export const VERSION = '2026-10-05.1';
const L = (tr,en) => ({tr,en});
export const areas = {
 frontend:L('JavaScript / React','JavaScript / React'), dotnet:L('C# / .NET','C# / .NET'),
 git:L('Git ve ekip çalışması','Git collaboration'), sql:L('SQL ve veri modeli','SQL and data modeling'),
 unity:L('Unity / C#','Unity / C#'), devops:L('DevOps temelleri','DevOps foundations'),
 api:L('API / HTTP','API / HTTP'), testing:L('Test ve doğrulama','Testing and verification'), structures:L('Veri yapıları','Data structures')
};
const refs = {
 react:['React Docs','https://react.dev/learn/queueing-a-series-of-state-updates'],
 dotnet:['Microsoft Learn','https://learn.microsoft.com/en-us/dotnet/standard/clr'],
 git:['Git Documentation','https://git-scm.com/docs/git-fetch'],
 sql:['PostgreSQL Documentation','https://www.postgresql.org/docs/current/ddl.html'],
 unity:['Unity Documentation','https://docs.unity3d.com/ScriptReference/Time-deltaTime.html'],
 devops:['Kubernetes Documentation','https://kubernetes.io/docs/concepts/workloads/pods/probes/'],
 api:['MDN','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS'],
 testing:['MDN · Array.filter','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter'],
 structures:['Python Documentation · Data Structures','https://docs.python.org/3/tutorial/datastructures.html']
};
function task(id,area,title,prompt,code,options,answer,explain,hint,checks,ref=area){
 return {id,area,version:VERSION,minutes:area==='testing'?4:2,title,prompt,code,options,answer,explain,hint,checks,source:{label:refs[ref][0],url:refs[ref][1],checkedAt:'2026-10-05'}};
}
export const tasks = [
 task('react-1','frontend',L('Render içindeki değer','Value within a render'),L('count başlangıçta 0. Tek tıklamadan sonra ekranda kaç görünür?','count starts at 0. What appears after one click?'),'onClick={() => {\n  setCount(count + 1);\n  setCount(count + 1);\n}}', [L('1','1'),L('2','2'),L('0','0')],0,L('İki çağrı da aynı render’daki 0 değerini kullanır ve 1 yazar. Güncelleyici fonksiyonlar önceki kuyruk sonucunu kullanabilir.','Both calls use 0 from the same render and replace it with 1. Updater functions can use the previous queued result.'),L('Olay işleyicisindeki count hemen değişir mi?','Does count change inside this event handler?'),[L('Render anındaki değeri ayırdım.','I identified the render snapshot.'),L('Değer ataması ile güncelleyici fonksiyonu ayırdım.','I distinguished replacement from an updater.')],'react'),
 task('clr-1','dotnet',L('CLR’nin sorumluluğu','CLR responsibilities'),L('Managed .NET uygulamasında CLR hangi işi yapar?','What does the CLR do in a managed .NET application?'),'', [L('SQL tablolarını otomatik tasarlar.','Automatically designs SQL tables.'),L('Managed kodun yürütülmesini ve bellek yönetimi gibi hizmetleri sağlar.','Runs managed code and provides services such as memory management.'),L('Yalnızca kaynak kod editörüdür.','It is only a source editor.')],1,L('CLR, managed yürütme ortamıdır; garbage collection gibi çalışma zamanı hizmetleri verir. Editör veya veritabanı tasarımcısı değildir.','The CLR is a managed execution environment with services such as garbage collection. It is not an editor or database designer.'),L('Derleme ile çalışma zamanı hizmetlerini ayır.','Separate compilation from runtime services.'),[L('Runtime ile editörü ayırdım.','I separated the runtime from the editor.'),L('Bir runtime hizmeti örneği verdim.','I gave an example of a runtime service.')]),
 task('git-1','git',L('Reddedilen push','Rejected push'),L('Uzak branch’te yeni commit var. İlk güvenli inceleme adımı hangisi?','The remote branch has new commits. What is a safe first investigation?'),'! [rejected] main -> main (non-fast-forward)',[L('git push --force','git push --force'),L('git status, git fetch; ardından commit farkını incelemek','git status, git fetch; then inspect the commit difference'),L('Yerel .git klasörünü silmek','Delete the local .git directory')],1,L('Fetch uzak referansları günceller; çalışma dosyalarını birleştirmez. Farkı inceleyip ekip akışına uygun merge/rebase planlanır. Körlemesine force push geçmişi değiştirebilir.','Fetch updates remote references without merging working files. Inspect the difference before choosing the team’s merge/rebase flow. Blind force pushing can rewrite history.'),L('Önce geçmişi değiştirmeyen bilgi toplama adımlarını düşün.','Start with information gathering that does not rewrite history.'),[L('Fetch ile merge farkını söyledim.','I explained fetch versus merge.'),L('Force push riskini açıkladım.','I explained the risk of force pushing.')]),
 task('ddl-1','sql',L('Şema mı, veri mi?','Schema or data?'),L('Mevcut tabloya sütun eklemek için hangisini kullanırsın?','Which statement adds a column to an existing table?'),'', [L('UPDATE users SET age = 0','UPDATE users SET age = 0'),L('SELECT age FROM users','SELECT age FROM users'),L('ALTER TABLE users ADD COLUMN age integer','ALTER TABLE users ADD COLUMN age integer')],2,L('ALTER TABLE tablo yapısını değiştirir. UPDATE satır değerlerini değiştirir; SELECT sorgular. Sütun eklemek şema değişikliğidir.','ALTER TABLE changes structure. UPDATE changes row values; SELECT queries them. Adding a column is a schema change.'),L('İçerik değişikliği ile yapı değişikliğini ayır.','Distinguish changing data from changing structure.'),[L('DDL ile veri güncellemesini ayırdım.','I distinguished DDL from updating data.'),L('Şema değişikliğine örnek verdim.','I gave a schema change example.')]),
 task('unity-1','unity',L('Kare hızından bağımsız hareket','Frame independent movement'),L('Update içinde speed saniyede birim ifade ediyor. Hangi satır uygundur?','Inside Update, speed means units per second. Which line fits?'),'', [L('transform.Translate(Vector3.right * speed);','transform.Translate(Vector3.right * speed);'),L('transform.Translate(Vector3.right * speed * Time.deltaTime);','transform.Translate(Vector3.right * speed * Time.deltaTime);'),L('transform.Translate(Vector3.right / Time.deltaTime);','transform.Translate(Vector3.right / Time.deltaTime);')],1,L('Time.deltaTime önceki kareden geçen süreyi saniye olarak verir. Hız ile çarpmak kare başına mesafeyi üretir; sabit mesafe eklemek FPS’e bağlı hareket oluşturur.','Time.deltaTime gives elapsed seconds since the previous frame. Multiplying speed by it yields distance for the frame; adding a fixed distance makes movement depend on FPS.'),L('Birim analizi: birim/saniye × saniye.','Units: units/second × seconds.'),[L('Hız ve mesafeyi ayırdım.','I distinguished speed and distance.'),L('FPS değişiminin etkisini açıkladım.','I explained what a change in FPS does.')]),
 task('probe-1','devops',L('Trafiğe hazır mı?','Ready for traffic?'),L('Pod çalışıyor ama henüz istek karşılamaya hazır değil. Hangi probe trafiği kontrol eder?','A pod is running but is not ready to serve requests. Which probe controls traffic?'),'', [L('Readiness','Readiness'),L('Liveness','Liveness'),L('Hiçbiri; pod çalışıyorsa hazırdır.','None; a running pod must be ready.')],0,L('Readiness başarısızsa pod uygun Service uç noktalarından çıkarılır. Liveness başarısızlığı yeniden başlatmaya yol açabilir. Çalışıyor olmak hazır olmak değildir.','A failed readiness probe removes a pod from matching Service endpoints. A failed liveness probe can cause a restart. Running does not imply ready.'),L('Yeniden başlatma ile trafik kabulünü ayır.','Separate restarting from accepting traffic.'),[L('Readiness ile liveness ayrımını yaptım.','I distinguished readiness and liveness.'),L('Çalışan podun neden hazır olmayabileceğini söyledim.','I explained why a running pod may not be ready.')]),
 task('cors-1','api',L('Tarayıcı ve API','Browser and API'),L('İstek terminalde başarılı, tarayıcıda CORS hatası var. Önce neyi incelersin?','The request works in a terminal but has a CORS error in the browser. What do you inspect first?'),'', [L('Veritabanını silip yeniden oluştururum.','Drop and recreate the database.'),L('Her yerde tarayıcı güvenliğini kapatırım.','Disable browser security everywhere.'),L('Origin, preflight ve API’nin CORS yanıt başlıklarını incelerim.','Inspect Origin, preflight and the API’s CORS response headers.')],2,L('CORS tarayıcının originler arası erişim denetimidir. Terminal başarısı tek başına tarayıcı erişimini kanıtlamaz; istek ve izin başlıklarını karşılaştır.','CORS is browser cross-origin access control. Terminal success alone does not prove browser access; compare request and permission headers.'),L('Terminal istemcisi ile tarayıcının güvenlik kuralları aynı mı?','Do terminal clients and browsers enforce the same security rules?'),[L('Tarayıcı erişimi ile sunucu yanıtını ayırdım.','I separated browser access from server response.'),L('İncelenecek somut başlıkları belirttim.','I named concrete headers to inspect.')]),
 {...task('predicate-1','testing',L('Küçük bir kod yaz','Write a small piece of code'),L('Yalnızca pozitif çift sayıları tutan koşulu yaz. Boşluğa gelecek ifadeyi gir; n sayıdır.','Write the condition that keeps only positive even numbers. Enter the expression for the blank; n is a number.'),'numbers.filter(n => /* senin ifaden / your expression */)',[],null,L('Koşul hem pozitifliği hem çift olmayı sağlamalı. Sıfır, negatif çift ve pozitif tek değerleri de test et. Örnek: n > 0 && n % 2 === 0.','The condition must check positivity and evenness. Include zero, negative even and positive odd values. Example: n > 0 && n % 2 === 0.'),L('İki koşulu && ile birleştirebilirsin. Sıfır pozitif değildir.','Combine two conditions with &&. Zero is not positive.'),[L('Sıfır ve negatif değerleri düşündüm.','I considered zero and negative values.'),L('Tek ve çift sayıları ayrı test ettim.','I tested odd and even numbers separately.')]),kind:'expression',rule:'positive-even'},
 task('react-2','frontend',L('Yeni örneğe aktar','Apply to a new example'),L('n başlangıçta 2. Tek olaydan sonraki değer kaç?','n starts at 2. What is the value after one event?'),'setN(n + 3);\nsetN(v => v * 2);',[L('7','7'),L('10','10'),L('4','4')],1,L('İlk adım 5 ile değiştirir; güncelleyici sıradaki 5’i ikiyle çarpar: 10.','The first step replaces with 5; the updater doubles that queued value: 10.'),L('Kuyruktaki işlemleri sırayla uygula.','Apply queued operations in order.'),[L('Ara değeri açıkça yazdım.','I wrote the intermediate value.'),L('Güncelleyicinin girdisini belirttim.','I identified the updater input.')],'react'),
 task('clr-2','dotnet',L('Runtime sınırları','Runtime boundaries'),L('Garbage collector olması hangi sonucu garanti eder?','What does having a garbage collector guarantee?'),'', [L('Uygulamada hiç kaynak sızıntısı olamaz.','No resource leaks are possible.'),L('Managed bellek geri kazanımı otomatik yönetilir; dosya gibi kaynaklar ayrıca yönetilmelidir.','Managed memory reclamation is automatic; resources such as files still need management.'),L('Hiç test gerekmez.','No testing is needed.')],1,L('Managed bellek yönetimi tüm kaynakların otomatik ve anında kapatıldığı anlamına gelmez. Dosya ve bağlantı gibi kaynaklarda uygun yaşam döngüsü gerekir.','Managed memory management does not mean every resource closes automatically and immediately. Files and connections need appropriate lifecycle management.'),L('Bellek ile dosya tanıtıcısı aynı kaynak mı?','Are memory and file handles the same resource?'),[L('Managed bellek kapsamını belirttim.','I described the managed memory scope.'),L('Bellek dışı kaynak örneği verdim.','I gave a non-memory resource example.')]),
 task('git-2','git',L('Fetch sonrasında','After fetch'),L('git fetch origin başarılı. Çalışma dosyaların birleşti mi?','git fetch origin succeeded. Have your working files been merged?'),'', [L('Hayır; uzak referanslar güncellendi, birleştirme ayrı adımdır.','No; remote references were updated, merging is separate.'),L('Evet; tüm çatışmalar otomatik çözüldü.','Yes; all conflicts were resolved automatically.'),L('Evet; tüm yerel commitler silindi.','Yes; all local commits were deleted.')],0,L('Fetch nesneleri ve referansları indirir. Fetch sonrası geçmişi incelemek gerekir; merge/rebase ayrı işlemdir.','Fetch downloads objects and references. Inspect history afterward; merge/rebase is a separate operation.'),L('Fetch ve pull aynı komut değil.','Fetch and pull are different commands.'),[L('Çalışma ağacı etkisini açıkladım.','I explained the working tree effect.'),L('Sonraki inceleme adımını söyledim.','I named the next inspection step.')]),
 task('ddl-2','sql',L('Şema değişikliğini tanı','Recognize a schema change'),L('Hangisi tablonun yapısını kaldırır?','Which statement removes the table structure?'),'', [L('DELETE FROM sessions','DELETE FROM sessions'),L('SELECT * FROM sessions','SELECT * FROM sessions'),L('DROP TABLE sessions','DROP TABLE sessions')],2,L('DROP TABLE tabloyu kaldırır. DELETE satırları siler, tablo yapısını korur. Gerçek veride yıkıcı işlemler öncesi bağımlılık ve yedekleri kontrol et.','DROP TABLE removes the table. DELETE removes rows while preserving its structure. Check dependencies and backups before destructive operations on real data.'),L('Satır silmek ile tabloyu kaldırmak farklıdır.','Deleting rows and removing a table differ.'),[L('Tablo ve kayıt ayrımını yaptım.','I distinguished a table from its records.'),L('İşlemin etkisini açıkladım.','I explained the operation’s effect.')]),
 task('unity-2','unity',L('Mesafeyi hesapla','Calculate distance'),L('speed = 6 ve deltaTime = 0.02. Bu karede ne kadar ilerler?','speed = 6 and deltaTime = 0.02. How far does it move this frame?'),'distance = speed * Time.deltaTime;',[L('0.12 birim','0.12 units'),L('6 birim','6 units'),L('300 birim','300 units')],0,L('6 birim/saniye × 0.02 saniye = 0.12 birim. deltaTime hız değil, geçen süredir.','6 units/second × 0.02 seconds = 0.12 units. deltaTime is elapsed time, not speed.'),L('Çarpımdaki birimleri takip et.','Track the units in the multiplication.'),[L('Birimleri yazdım.','I wrote the units.'),L('Kare başına mesafeyi hesapladım.','I calculated per-frame distance.')]),
 task('probe-2','devops',L('Yanlış yeniden başlatma','Unnecessary restart'),L('Geçici dış bağımlılık sorunu var, uygulama süreci sağlıklı. Yalnızca trafiği durdurmak için neyi başarısız sayarsın?','A dependency is temporarily unavailable while the process is healthy. To pause traffic only, which probe should fail?'),'', [L('Liveness','Liveness'),L('Readiness','Readiness'),L('İkisi her zaman aynı olmalı.','Both must always be identical.')],1,L('Hazır olmama durumunu readiness ile ifade etmek yeniden başlatma döngülerini önlemeye yardımcı olur. Liveness sürecin toparlanamadığı durumlar için düşünülmelidir.','Representing unavailability with readiness helps avoid restart loops. Liveness should reflect conditions the process cannot recover from.'),L('Trafik dışı kalma ile process restart farklı sonuçlardır.','Leaving traffic and restarting a process are different outcomes.'),[L('İstenen sonucu seçtim.','I identified the intended outcome.'),L('Yeniden başlatma riskini açıkladım.','I explained the restart risk.')]),
 task('cors-2','api',L('İzin başlığı nerede?','Where is the permission header?'),L('Access-Control-Allow-Origin hangi taraftan gelmelidir?','Which side should send Access-Control-Allow-Origin?'),'', [L('Frontend’in request body alanından','The frontend request body'),L('API/sunucu yanıtından','The API/server response'),L('Yerel Git ayarından','Local Git configuration')],1,L('Bu bir yanıt başlığıdır. İstemcinin kendisine izin vermesi CORS politikasını çözmez. İzin verilen origin sunucu politikasında belirlenir.','This is a response header. A client cannot grant itself CORS access. The server policy determines allowed origins.'),L('İzni veren taraf kaynağın sahibi olmalı.','The resource owner grants permission.'),[L('Request ile response ayrımını yaptım.','I distinguished request and response.'),L('İzni veren tarafı söyledim.','I identified who grants access.')]),
 {...task('predicate-2','testing',L('Sınır değerleri','Boundary values'),L('0 dahil, 10 hariç aralıktaki sayıları tutan koşulu yaz. n sayıdır.','Write the condition that keeps numbers from 0 inclusive to 10 exclusive. n is a number.'),'numbers.filter(n => /* ifade / expression */)',[],null,L('Alt sınır dahil, üst sınır hariç: n >= 0 && n < 10. Özellikle 0 ve 10 beklenen sonucu ayırır.','Include the lower bound, exclude the upper: n >= 0 && n < 10. In particular, 0 and 10 distinguish expected behavior.'),L('Alt sınır için >=, üst sınır için < düşün.','Consider >= for the lower bound and < for the upper.'),[L('Alt sınırın dahil olduğunu kontrol ettim.','I checked inclusion of the lower bound.'),L('Üst sınırın hariç olduğunu kontrol ettim.','I checked exclusion of the upper bound.')]),kind:'expression',rule:'range'}
];
tasks.push(
 task('stack-1','structures',L('Stack: sıradaki eleman','Stack: the next element'),L('Aşağıdaki yığına 3 ve 7 ekleniyor. Kodun sonundaki pop() hangi değeri döndürür?','The stack below receives 3 and then 7. What does the final pop() return?'),'stack = []\nstack.append(3)\nstack.append(7)\nvalue = stack.pop()', [L('3','3'),L('7','7'),L('0','0')],1,L('Stack son giren ilk çıkar (LIFO) düzenindedir. Son eklenen 7 çıkar; yığında 3 kalır.','A stack uses last in, first out (LIFO). The last added value, 7, is removed; 3 remains.'),L('En son hangi değer eklendi?','Which value was added last?'),[L('LIFO kuralını söyledim.','I stated the LIFO rule.'),L('Çıkan ve kalan elemanı ayırdım.','I distinguished the removed and remaining items.')]),
 task('queue-1','structures',L('Queue: istek sırası','Queue: request order'),L('Kuyruğa A, sonra B ekleniyor. FIFO ile ilk hangisi işlenir?','A is enqueued, then B. Which is processed first under FIFO?'),'from collections import deque\nqueue = deque(["A", "B"])\nvalue = queue.popleft()', [L('B','B'),L('İkisi aynı anda','Both at once'),L('A','A')],2,L('Queue ilk giren ilk çıkar (FIFO) düzenini kullanır. A önce eklenir, önce işlenir. Stack’in LIFO sırasından farklıdır.','A queue uses first in, first out (FIFO). A was added first and is processed first. This differs from a stack’s LIFO order.'),L('Geliş sırasını koruyan bir bekleme kuyruğu düşün.','Think of a waiting line preserving arrival order.'),[L('FIFO kuralını açıkladım.','I explained the FIFO rule.'),L('Stack ile farkını belirttim.','I contrasted it with a stack.')]),
 task('dict-1','structures',L('Anahtar ile erişim','Access by key'),L('Kullanıcıyı benzersiz kimliğiyle ilişkilendirmek için hangi yapı daha doğrudan uygundur?','Which structure directly maps a user to a unique identifier?'),'', [L('Anahtar-değer sözlüğü (dict / Map)','A key-value dictionary (dict / Map)'),L('Yalnızca son gireni çıkaran stack','A stack that only removes the last item'),L('Yalnızca geliş sırasını tutan queue','A queue that only maintains arrival order')],0,L('Sözlük anahtarları değerlerle eşler. Benzersiz kullanıcı kimliğini anahtar olarak kullanarak ilgili kayda erişebilirsin.','A dictionary maps keys to values. A unique user identifier can be used as the key for its record.'),L('Kimlik ile kayıt arasında bir eşleme gerekiyor.','You need a mapping between identifier and record.'),[L('Anahtar ve değeri tanımladım.','I identified the key and value.'),L('Bu senaryoda neden eşleme gerektiğini açıkladım.','I explained why this scenario needs a mapping.')])
);
export const baselineIds=tasks.slice(0,8).map(t=>t.id);
export const goals = ['fullstack','frontend','ai','data','devops','mobile','game'];
export const goalLabels = {fullstack:L('Full stack','Full stack'),frontend:L('Frontend','Frontend'),ai:L('AI mühendisliği','AI engineering'),data:L('Veri ve veritabanı','Data and databases'),devops:L('DevOps','DevOps'),mobile:L('Mobil geliştirme','Mobile development'),game:L('Oyun geliştirme','Game development')};
export function publicTask(t){const {answer,explain,checks,rule,hint,...visible}=t;return visible;}
