// Original RealDev diagnostic scenarios. Linked documentation is a technical reference, not imported quiz content.
import {originalReference} from './content-policy.mjs';
const L=(tr,en)=>({tr,en});
const refs={
 push:['git','https://git-scm.com/docs/git-push'],rebase:['git','https://git-scm.com/docs/git-rebase'],
 effect:['react','https://react.dev/reference/react/useEffect'],js:['mdn','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type'],
 python:['python','https://docs.python.org/3/tutorial/errors.html'],ef:['dotnet','https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/'],
 di:['dotnet','https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection'],cancel:['dotnet','https://learn.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads'],
 destroy:['unity','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Object.Destroy.html'],coroutine:['unity','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/MonoBehaviour.StartCoroutine.html'],physics:['unity','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Rigidbody.MovePosition.html'],
 cors:['mdn','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS'],limit:['mdn','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/429'],gateway:['mdn','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/502'],
 constraint:['postgres','https://www.postgresql.org/docs/current/ddl-constraints.html'],lock:['postgres','https://www.postgresql.org/docs/current/explicit-locking.html'],schema:['postgres','https://www.postgresql.org/docs/current/ddl-schemas.html'],
 docker:['docker','https://docs.docker.com/engine/daemon/troubleshoot/'],port:['docker','https://docs.docker.com/engine/containers/run/'],image:['kubernetes','https://kubernetes.io/docs/concepts/containers/images/'],
 compose:['android','https://developer.android.com/develop/ui/compose/side-effects'],ml:['sklearn','https://scikit-learn.org/stable/common_pitfalls.html'],test:['python','https://docs.python.org/3/library/unittest.html']
};
export function createErrorTasks(){
 const rows=[];
 const add=(id,area,topic,level,title,code,prompt,correct,wrong,meaning,evidence,fix,verify,ref)=>rows.push({id,area,topic,level,title,code,prompt,correct,wrong,meaning,evidence,fix,verify,ref});
 add('git-nonff','git',L('Git · uzak geçmiş','Git · remote history'),'beginner',L('Push reddedildi: non-fast-forward','Push rejected: non-fast-forward'),
 'git push origin main\n! [rejected] main -> main (non-fast-forward)',
 L('Ekipten biri main’e yeni commit gönderdi. Yerel commitlerini ve ekip değişikliklerini koruyarak nasıl başlarsın?','A teammate pushed new commits to main. How do you start while preserving both histories?'),
 L('git status ve fetch sonrası geçmiş farkını incele; ekip akışına uygun merge/rebase seç.','Inspect status and fetched history; choose merge/rebase according to the team workflow.'),
 [L('Hemen --force ile main’i ez.','Immediately overwrite main with --force.'),L('Uzak depoyu silip aynı isimle yeniden aç.','Delete and recreate the remote repository.')],
 L('Uzak branch, yerel geçmişin atası değil; normal push geçmiş kaybını önlemek için reddedildi.','The remote branch is not an ancestor of the local tip; normal push refuses potential history loss.'),
 L('git status; git fetch origin; git log --oneline --graph --all ile ayrışmayı incele.','Inspect divergence with git status, git fetch origin and git log --oneline --graph --all.'),
 L('Çalışmanı koru; ekip politikasına göre birleştir veya yayımlanmamış commitleri rebase et. Force varsayılan çözüm değildir.','Preserve work; merge or rebase unpublished commits according to policy. Force is not the default repair.'),
 L('Çakışmaları çöz, testleri çalıştır; normal push sonrası uzak branch’in beklenen commitleri içerdiğini kontrol et.','Resolve conflicts, test, then verify the remote contains the intended commits after a normal push.'),'push');
 add('git-rebase-stop','git',L('Git · rebase çakışması','Git · rebase conflict'),'intermediate',L('Rebase bir committe durdu','Rebase stopped on a commit'),
 'CONFLICT (content): Merge conflict in src/price.js\nerror: could not apply 8c31d02... adjust discount',
 L('Rebase ortasında bu çıktı var. Commitleri sessizce kaybetmeden hangi adımı seçersin?','This appears during a rebase. Which step avoids silently losing commits?'),
 L('git status ile çatışan dosyaları bul; içeriği çöz, stage et ve rebase --continue kullan.','Locate conflicts with git status; resolve, stage, then use rebase --continue.'),
 [L('Hata veren her commit için --skip yap.','Use --skip for every failing commit.'),L('Çalışma ağacını reset --hard ile temizle.','Clear the working tree with reset --hard.')],
 L('Git bir commiti yeni tabana uygularken iki değişikliği otomatik uzlaştıramadı.','Git could not reconcile edits while replaying a commit on a new base.'),
 L('git status ve dosya farkını incele; hangi davranışların birlikte korunacağını belirle.','Inspect status and diffs; identify the behaviors that must both survive.'),
 L('İşaretleri anlamlı kodla değiştirip git add ve rebase --continue uygula. İptal kararı için --abort, commit atlamak için --skip farklıdır.','Resolve markers into meaningful code, then stage and continue. Abort and skipping a commit have different effects.'),
 L('İlgili indirim testlerini çalıştır; son geçmişte beklenen değişikliklerin bulunduğunu doğrula.','Run discount tests and verify the intended changes remain in the resulting history.'),'rebase');
 add('react-effect-loop','frontend',L('React · effect döngüsü','React · effect loop'),'intermediate',L('Effect sürekli yeniden çalışıyor','Effect keeps running'),
 'useEffect(() => {\n  setItems([...items]);\n}, [items]);\n// UI: repeated updates',
 L('Her effect çalışması yeni diziyle state’i güncelliyor. Döngünün nedenini nasıl teşhis edersin?','Each effect creates a new array and updates state. How do you diagnose the loop?'),
 L('State güncellemesinin items bağımlılığını her seferinde değiştirdiğini kontrol et.','Check that the state update changes the items dependency each time.'),
 [L('Bağımlılık uyarısını kapat; her effect için [] kullan.','Disable dependency warnings and use [] for every effect.'),L('Döngüyü setTimeout ile yavaşlatmak yeterlidir.','Slowing the loop with setTimeout is sufficient.')],
 L('Effect state’i değiştiriyor; değişen bağımlılık effect’i tekrar tetikliyor.','The effect updates state, whose changed dependency triggers the effect again.'),
 L('Hangi state’in yazıldığını ve bağımlılıkların kimlik değişimini izle.','Trace written state and dependency identity changes.'),
 L('Dış sistemle senkronizasyon yoksa gereksiz effect’i kaldır; hesaplanan veriyi render sırasında üret.','Remove an unnecessary effect if no external system is synchronized; derive values during rendering.'),
 L('Girdiyi değiştir; beklenen arayüz güncellensin, render/effect sayısı sınırsız büyümesin.','Change input; verify the UI updates and effect/render counts stay bounded.'),'effect');
 add('js-map-undefined','frontend',L('JavaScript · veri sözleşmesi','JavaScript · data contract'),'beginner',L('undefined üzerinde map çağrısı','Calling map on undefined'),
 'const payload = { results: [] };\nconst rows = payload.items;\nrows.map(renderRow);\n// TypeError',
 L('API yanıtı results içeriyor; kod items okuyor. Hangi düzeltme asıl sorunu ele alır?','The API returns results but the code reads items. Which fix addresses the actual issue?'),
 L('Yanıt şemasını doğrula; doğru alanı kullan ve yüklenme/hata durumlarını ayrı yönet.','Validate the response schema; use the right field and separate loading/error states.'),
 [L('Her hatayı yakalayıp boş dizi göster; sözleşmeyi inceleme.','Catch everything and show an empty array without checking the contract.'),L('Array.prototype.map metodunu yeniden yaz.','Rewrite Array.prototype.map.')],
 L('map alıcısı undefined; mesaj tek başına ağ isteğinin neden yanlış olduğunu söylemez.','The receiver of map is undefined; the error alone does not explain the response mismatch.'),
 L('Network yanıtında alan adını ve typeof/Array.isArray sonucunu kontrol et; kişisel veriyi loglama.','Check field names and Array.isArray in the response without logging private data.'),
 L('Doğru alanı doğrulanmış dizi olarak eşle; yüklenme ve bozuk yanıtı boş sonuçtan ayır.','Map the correct validated array field; distinguish loading and invalid responses from empty results.'),
 L('Boş, dolu, eksik alanlı ve başarısız yanıtlarla test et.','Test empty, populated, missing-field and failed responses.'),'js');
 add('python-value-error','frontend',L('IDE · Python girdi hatası','IDE · Python input error'),'beginner',L('Python: metni sayıya çeviremiyor','Python: invalid integer input'),
 'quantity = int("three")\n# ValueError',
 L('İstemci quantity alanına metin gönderdi. Güvenli yaklaşım hangisi?','The client sends text in quantity. What is a safe approach?'),
 L('Girdi sözleşmesini kontrol et; geçersiz sayıyı açık doğrulama hatasıyla reddet.','Check the input contract and reject invalid numbers with a clear validation error.'),
 [L('Tüm exception’ları yutup miktarı 0 yap.','Swallow every exception and set quantity to zero.'),L('Python’u yeniden kur; int her metni kabul etmelidir.','Reinstall Python; int should accept all text.')],
 L('Değer beklenen sayı biçiminde değil; yorumlayıcı kurulumunun bozuk olduğu sonucu çıkmaz.','The value is not in the required numeric format; this does not imply a broken interpreter.'),
 L('Kaynak girdinin türünü ve izin verilen aralığı doğrula.','Verify the input type and allowed range.'),
 L('Beklenen ValueError durumunu kontrollü ele al; iş kuralını bozan sessiz varsayılan kullanma.','Handle the expected ValueError explicitly instead of silently substituting a value that changes the business rule.'),
 L('Geçerli sayı, boş metin, harfli girdi ve aralık dışı değerleri dene.','Test valid, empty, alphabetic and out-of-range values.'),'python'); add('ef-parallel-context','dotnet',L('.NET · EF Core eşzamanlılık','.NET · EF Core concurrency'),'intermediate',L('DbContext üzerinde ikinci işlem','Second operation on DbContext'),
 'var a = db.Users.ToListAsync();\nvar b = db.Orders.ToListAsync();\nawait Task.WhenAll(a, b);\n// InvalidOperationException: concurrent context use',
 L('Aynı DbContext iki sorguyu eşzamanlı çalıştırıyor. Doğru yaklaşım?','Two queries run concurrently on one DbContext. What is the right approach?'),
 L('İşlemleri sırayla await et veya paralellik gerekiyorsa ayrı context kullan.','Await sequentially or use separate contexts when parallelism is required.'),
 [L('Task.WhenAll zaten aynı context’i thread-safe yapar.','Task.WhenAll already makes a context thread-safe.'),L('Exception’ı yut ve aynı context ile devam et.','Swallow the exception and continue with that context.')],
 L('DbContext aynı örnek üzerinde eşzamanlı işlemleri desteklemez.','DbContext does not support concurrent operations on one instance.'),
 L('İki sorgunun context kimliğini ve await sınırlarını karşılaştır.','Compare context identity and await boundaries for the queries.'),
 L('Ardışık await veya ayrı ömürlü context seç; bozulan context’i yeniden kullanma.','Choose sequential awaits or separate lifetimes; do not reuse a context in an unrecoverable state.'),
 L('Eşzamanlı istekleri dene; veri doğruluğunu ve hata loglarını kontrol et.','Exercise concurrent requests and check data correctness and error logs.'),'ef');
 add('dotnet-di-missing','dotnet',L('.NET · dependency injection','.NET · dependency injection'),'beginner',L('Servis oluşturulamıyor','Service cannot be constructed'),
 'Unable to resolve service for type IClock\nwhile activating ReportService',
 L('ReportService constructor’ı IClock istiyor. İlk inceleme nedir?','ReportService requires IClock in its constructor. What should you inspect first?'),
 L('IClock kaydını, implementation’ı ve servis ömrünü başlangıç yapılandırmasında kontrol et.','Check IClock registration, implementation and lifetime in startup configuration.'),
 [L('Constructor’dan parametreyi silip tüm kullanımları null yap.','Remove the parameter and replace its uses with null.'),L('Her bağımlılığı rastgele singleton kaydet.','Register every dependency as a singleton at random.')],
 L('Container gerekli bağımlılığı çözemiyor; eksik veya yanlış kayıt olasıdır.','The container cannot resolve a required dependency; registration may be missing or incorrect.'),
 L('Constructor türü ile AddScoped/AddTransient/AddSingleton kayıtlarının eşleşmesini incele.','Compare the constructor type with the registered service mappings.'),
 L('Uygun implementation ve ömür kaydet; scoped bağımlılığı uzun ömürlü servise yanlış taşımamaya dikkat et.','Register the appropriate implementation and lifetime; avoid incorrectly capturing scoped services in longer-lived services.'),
 L('Uygulamayı başlatıp gerçek scope içinde servisi çöz ve ilgili endpoint’i test et.','Start the app, resolve the service in a real scope and test the endpoint.'),'di');
 add('dotnet-cancellation','dotnet',L('.NET · async iptal','.NET · async cancellation'),'intermediate',L('İptal edilen görev başarısızlık mı?','Is cancellation a failure?'),
 'GET /report cancelled by client\nOperationCanceledException\ntoken.IsCancellationRequested == true',
 L('İstemci isteği iptal etti. Kontrolsüz retry yerine ne yaparsın?','The client cancelled the request. What should you do instead of retrying blindly?'),
 L('İlgili token’ı ve iptal nedenini doğrula; beklenen iptali hata ve timeout’tan ayır.','Verify the relevant token and reason; distinguish expected cancellation from failure and timeout.'),
 [L('Aynı iptal edilmiş token ile sonsuz retry yap.','Retry forever with the cancelled token.'),L('Tüm iptalleri başarı sayıp eksik raporu kaydet.','Treat all cancellations as success and save an incomplete report.')],
 L('Cooperative cancellation işin durmasını bildirir; her iptal uygulama hatası değildir.','Cooperative cancellation requests stopping work; cancellation is not always an application defect.'),
 L('Token’ın kaynağını, timeout politikasını ve tamamlanmış yan etkileri incele.','Inspect token origin, timeout policy and side effects that may already have completed.'),
 L('Token’ı alt işlemlere ilet, kaynakları finally/using ile temizle; kısmi yazmaları iş kuralına göre uzlaştır.','Propagate the token, clean up resources and reconcile partial writes according to the business rule.'),
 L('Normal bitiş, istemci iptali ve timeout yollarını ayrı test et.','Test normal completion, client cancellation and timeout separately.'),'cancel');
 add('unity-destroyed-reference','unity',L('Unity · nesne yaşam döngüsü','Unity · object lifetime'),'intermediate',L('Yok edilmiş nesneye geç callback','Late callback to a destroyed object'),
 'Scene A unloaded\nCallback: update previous EnemyView\nMissingReferenceException',
 L('Sahne değişince eski callback UI’ı güncelliyor. Kalıcı çözüm hangisi?','After a scene change, an old callback updates UI. What is a durable fix?'),
 L('Nesne ömrüyle callback’i ilişkilendir; aboneliği kaldır/iptal et ve geç yanıtı doğrula.','Tie callbacks to object lifetime; unsubscribe/cancel and validate late responses.'),
 [L('Hata mesajını Console’dan gizle.','Hide the error in the Console.'),L('Eski sahnenin tüm nesnelerini sınırsız yaşat.','Keep all objects from every old scene alive indefinitely.')],
 L('C# referansı kalmış olsa da Unity nesnesi Destroy ile kaldırılmış olabilir.','A C# reference may remain after the Unity object has been destroyed.'),
 L('İlk uygulama stack satırını, Destroy/sahne değişimi ve abonelik zamanını karşılaştır.','Compare the application stack line with destruction, scene change and subscription timing.'),
 L('Yaşam döngüsünde abonelikleri temizle; aktif nesne/istek kimliğini kontrol et. Sadece exception yutmak yeterli değildir.','Clean subscriptions at lifetime boundaries and check the active object/request identity. Swallowing exceptions is insufficient.'),
 L('İstek beklerken sahne değiştir; eski yanıtın yeni/kapalı nesneyi değiştirmediğini doğrula.','Switch scenes while a request is pending and verify the stale response cannot update inactive or replacement objects.'),'destroy');
 add('unity-inactive-coroutine','unity',L('Unity · coroutine','Unity · coroutine'),'beginner',L('Pasif nesnede coroutine başlatma','Starting a coroutine on an inactive object'),
 'Popup GameObject: inactive\nRequest: StartCoroutine(AnimatePopup())\nCoroutine could not be started',
 L('Popup kapalıyken animasyon coroutine’i başlatılıyor. İlk neyi kontrol edersin?','An animation coroutine starts while the popup is inactive. What do you check first?'),
 L('Coroutine’i başlatan GameObject’in aktifliğini ve yaşam döngüsündeki çağrı sırasını.','The active state of the hosting GameObject and lifecycle call order.'),
 [L('StartCoroutine yerine sonsuz while döngüsü yaz.','Replace StartCoroutine with an infinite while loop.'),L('Animasyonu her frame yeniden başlat.','Restart the animation every frame.')],
 L('Coroutine’in çalışması onu barındıran nesnenin yaşam döngüsüne bağlıdır.','Coroutine execution depends on the hosting object lifecycle.'),
 L('activeInHierarchy, açma/kapatma akışı ve coroutine sahibi hangi nesne kontrol et.','Inspect activeInHierarchy, open/close order and the actual coroutine host.'),
 L('Nesne etkinleştikten sonra başlat veya uygun aktif sahibi seç; kapanışta gerekli temizliği tasarla.','Start after activation or choose an appropriate active host; design cleanup when closing.'),
 L('Popup’ı art arda aç/kapat; fazladan coroutine ve kalmış animasyon olmadığını kontrol et.','Repeatedly open and close the popup; check for duplicate coroutines and leftover animation.'),'coroutine');
 add('unity-physics-motion','unity',L('Unity · fizik hareketi','Unity · physics motion'),'intermediate',L('Kinematik platform titriyor','Kinematic platform jitters'),
 'Kinematic Rigidbody platform\nUpdate(): transform.position += step;\nRider appears to jitter',
 L('Fizik tabanlı kinematik platform render döngüsünde taşınıyor. Hangi inceleme/düzeltme daha uygundur?','A physics-based kinematic platform moves in the render loop. What should you inspect and adjust?'),
 L('Fizik adımı ve Rigidbody.MovePosition kullanımını kontrol et; FixedUpdate ile uygun hareket planla.','Inspect physics steps and Rigidbody.MovePosition; plan appropriate movement in FixedUpdate.'),
 [L('Fizik saatini her Update içinde rastgele değiştir.','Randomly change the physics timestep inside Update.'),L('Tüm çarpışmaları kapat; titreme böyle çözülür.','Disable all collisions to fix the jitter.')],
 L('Render ve fizik adımları aynı ritimde olmayabilir; transform hareketi fizik akışıyla uyuşmayabilir.','Rendering and physics have different cadences; transform motion may conflict with the physics flow.'),
 L('Rigidbody’nin kinematik durumunu, hareketin nerede uygulandığını ve zaman adımını incele.','Inspect kinematic state, movement location and the timestep.'),
 L('Kinematik hareketi uygun fizik API’siyle uygula; interpolation görüntüyü yumuşatabilir ama iş kuralı hatasını çözmez.','Move through the appropriate physics API; interpolation can smooth visuals but does not repair incorrect movement logic.'),
 L('Farklı FPS ve fizik adımlarında aynı mesafe/zaman ve çarpışma davranışını karşılaştır.','Compare distance over time and collision behavior at different render and physics rates.'),'physics'); add('cors-credentials','api',L('HTTP · CORS ve cookie','HTTP · CORS and cookies'),'intermediate',L('Credential içeren CORS isteği engellendi','Credentialed CORS request blocked'),
 'fetch(url, {credentials: "include"})\nResponse: Access-Control-Allow-Origin: *\nBrowser: CORS blocked',
 L('Cookie ile istek gönderiliyor. Yanıttaki yıldız neden yeterli değil?','The request includes cookies. Why is the wildcard insufficient?'),
 L('İzinli origin’i açık doğrula; uygun origin ve Allow-Credentials başlıklarını sunucuda ayarla.','Validate an explicit allowed origin; configure appropriate origin and Allow-Credentials headers server-side.'),
 [L('mode: no-cors kullanınca JSON normal okunur.','Using no-cors makes the JSON readable normally.'),L('Tarayıcının güvenlik korumasını herkese kapattır.','Ask all users to disable browser security.')],
 L('Credential içeren CORS yanıtı Allow-Origin için wildcard kullanamaz.','A credentialed CORS response cannot use a wildcard Allow-Origin.'),
 L('Network’te origin, preflight ve gerçek yanıt başlıklarını incele; cookie politikasını ayrıca kontrol et.','Inspect origin, preflight and actual response headers; check cookie policy separately.'),
 L('Origin allowlist’i uygula; gerektiğinde Vary: Origin ve credential ayarlarını doğru kullan.','Apply an origin allowlist with appropriate Vary: Origin and credential settings.'),
 L('İzinli ve izinsiz origin’i dene. CORS’un kimlik doğrulama/yetkilendirme yerine geçmediğini koru.','Test allowed and disallowed origins; retain server authentication and authorization independently of CORS.'),'cors');
 add('http-retry-after','api',L('HTTP · istek sınırı','HTTP · request limits'),'beginner',L('429 sonrası tekrar fırtınası','Retry storm after 429'),
 'HTTP 429 Too Many Requests\nRetry-After: 30\nClient retries immediately in a loop',
 L('Sunucu 30 saniye bekleme bildirdi. Güvenli istemci davranışı hangisi?','The server asks for a 30-second wait. What is safe client behavior?'),
 L('Retry-After’ı değerlendir; sınırlı retry, backoff ve iptal ile istek hızını azalt.','Honor Retry-After where applicable; reduce request rate with bounded retry, backoff and cancellation.'),
 [L('Daha fazla paralel istek açarak limiti aş.','Open more parallel requests to bypass the limit.'),L('Aynı isteği beklemeden sonsuza kadar gönder.','Resend the request forever without waiting.')],
 L('429, belirli bir zaman aralığında fazla istek olduğunu bildirir; limitin kapsamı servise bağlıdır.','429 signals too many requests in a time window; the limit scope depends on the service.'),
 L('Durum kodunu, Retry-After’ı ve hangi hesap/işlemlerin limiti paylaştığını incele.','Inspect status, Retry-After and which accounts or operations share the limit.'),
 L('Beklemeyi zamanla, deneme sayısını sınırla. Yazma işlemlerinde retry güvenliğini ayrıca doğrula.','Schedule the wait and cap attempts. Independently verify retry safety for writes.'),
 L('Sahte saatle bekleme süresini, üst sınırı ve kullanıcı iptalini test et.','Use a fake clock to test wait duration, attempt caps and cancellation.'),'limit');
 add('http-gateway-502','api',L('HTTP · gateway ve upstream','HTTP · gateway and upstream'),'intermediate',L('API yerine 502 geliyor','502 instead of the API response'),
 'Browser -> reverse proxy -> API\nHTTP 502 Bad Gateway\nProxy log: upstream response invalid',
 L('Arayüz proxy üzerinden 502 alıyor. En yararlı ilk kontrol nedir?','The UI receives 502 through a proxy. What is the most useful first check?'),
 L('İstek kimliğiyle proxy ve upstream loglarını, hedef adres/port/protokolü karşılaştır.','Correlate proxy and upstream logs and verify target address, port and protocol.'),
 [L('Her 502 mutlaka CORS hatasıdır.','Every 502 is necessarily a CORS error.'),L('TLS doğrulamasını kalıcı kapat.','Permanently disable TLS verification.')],
 L('Gateway upstream’den geçerli yanıt alamadı; mesaj tek başına kesin kök nedeni vermez.','The gateway received an invalid upstream response; the status alone does not identify a root cause.'),
 L('Sağlık durumu, bağlantı ve yanıt biçimini güvenilir ortamda kontrol et; sırları loglama.','Check health, connectivity and response format in a trusted environment without logging secrets.'),
 L('Kanıta göre yanlış hedef, servis çökmesi veya protokol yapılandırmasını düzelt.','Repair the target, service failure or protocol configuration supported by the evidence.'),
 L('Proxy üzerinden gerçek isteği ve kontrollü upstream hatasını dene; beklenen yanıt/kayıtları doğrula.','Test through the proxy with normal and controlled upstream failures; verify responses and logs.'),'gateway');
 add('sql-foreign-key','sql',L('SQL · ilişkisel bütünlük','SQL · referential integrity'),'beginner',L('Var olmayan kullanıcıya sipariş','Order for a missing user'),
 'INSERT INTO orders(user_id) VALUES (42);\nERROR: foreign key constraint failed\nusers table has no id=42',
 L('Sipariş var olmayan kullanıcıya bağlanıyor. Doğru yaklaşım hangisi?','An order references a missing user. What is the correct approach?'),
 L('İlişkili kaydı ve işlem sırasını doğrula; geçerli kullanıcıyla atomik iş akışı kur.','Verify the referenced record and operation order; use an atomic flow with a valid user.'),
 [L('Foreign key kontrolünü kaldır.','Remove the foreign key constraint.'),L('Başka rastgele kullanıcının ID’sini kullan.','Use another random user ID.')],
 L('Foreign key, ilişkili anahtarın bulunmasını gerektirir; kısıt veri hatasını görünür kılar.','The foreign key requires the referenced key to exist; the constraint exposes inconsistent data.'),
 L('Constraint adı, parent kaydı ve insert/commit sırasını incele.','Inspect the constraint, parent record and insert/commit order.'),
 L('Doğru kullanıcıyı doğrula; gerekli kayıtları uygun transaction içinde oluştur. Kısıtı gizleme.','Validate the correct user and create related records in the appropriate transaction; retain the constraint.'),
 L('Var olan/olmayan kullanıcı ve eşzamanlı silme durumunu test et.','Test existing and missing users plus concurrent deletion.'),'constraint');
 add('sql-deadlock','sql',L('SQL · transaction kilitleri','SQL · transaction locks'),'intermediate',L('İki transfer birbirini bekliyor','Two transfers wait on each other'),
 'T1 locks account 1, waits for 2\nT2 locks account 2, waits for 1\nSQLSTATE 40P01: deadlock',
 L('İki işlem ters sırada hesapları kilitliyor. Kalıcı çözüm hangisi?','Two transactions lock accounts in opposite order. What is a durable fix?'),
 L('Kilit alma sırasını tutarlı yap; kısa transaction ve sınırlı tam işlem retry tasarla.','Use consistent lock order, short transactions and bounded whole-transaction retry.'),
 [L('Yalnızca başarısız son UPDATE’i aynı bozuk transaction’da tekrar et.','Retry only the last UPDATE in the failed transaction.'),L('Veritabanındaki tüm kilitleri kalıcı kapat.','Permanently disable all database locks.')],
 L('Döngüsel bekleme deadlock oluşturur; PostgreSQL işlemlerden birini sonlandırabilir.','A circular wait forms a deadlock; PostgreSQL can abort one transaction.'),
 L('Transaction sınırlarını ve edinilen kilitlerin sırasını loglarla karşılaştır.','Compare transaction boundaries and lock acquisition order in logs.'),
 L('Ortak sıralama uygula; başarısız transaction’ı rollback sonrası güvenli şekilde bütün olarak yeniden dene.','Apply a common order; after rollback, retry the entire transaction safely when appropriate.'),
 L('Eşzamanlı ters yönlü transferlerle bakiye toplamını ve retry üst sınırını doğrula.','Test concurrent transfers in opposite directions, balance invariants and retry limits.'),'lock');
 add('sql-search-path','sql',L('SQL · şema ve bağlantı','SQL · schema and connection'),'intermediate',L('Tablo var ama bulunamıyor','Table exists but is not found'),
 'Table exists as app.orders\nSELECT * FROM orders;\nERROR: relation "orders" does not exist',
 L('Tablo app şemasında; sorgu şemasız. İlk kontrol nedir?','The table is in schema app but the query is unqualified. What do you check first?'),
 L('Doğru veritabanını, search_path ve şema erişim yetkisini kontrol et.','Check the database, search_path and schema access privileges.'),
 [L('Aynı isimli boş tabloyu public altında hemen oluştur.','Immediately create an empty table with that name in public.'),L('Tüm kullanıcılara süper kullanıcı yetkisi ver.','Grant superuser privileges to everyone.')],
 L('Şemasız adlar search_path ile çözülür; tablo başka şemada veya bağlantı başka veritabanında olabilir.','Unqualified names resolve through search_path; the table may be in another schema or database.'),
 L('Bağlantı hedefini ve SHOW search_path çıktısını kontrol et.','Inspect the connection target and SHOW search_path.'),
 L('Gerekirse app.orders gibi şema nitelikli ad kullan; yalnızca gereken erişimi tanımla.','Use a schema-qualified name such as app.orders when appropriate and grant only necessary access.'),
 L('Uygulamanın gerçek kullanıcı/bağlantısıyla sorguyu yeniden çalıştır.','Rerun the query using the actual application role and connection.'),'schema'); add('docker-daemon','devops',L('Docker · engine bağlantısı','Docker · engine connection'),'beginner',L('Docker CLI engine’e ulaşamıyor','Docker CLI cannot reach the engine'),
 'docker ps\nCannot connect to the Docker daemon',
 L('Komut var ama engine yanıt vermiyor. Verileri silmeden nereden başlarsın?','The CLI exists but the engine does not respond. Where do you start without deleting data?'),
 L('Engine durumunu, seçili Docker context’i ve hedef endpoint’i kontrol et.','Check engine status, selected Docker context and target endpoint.'),
 [L('Factory reset yapıp tüm image/volume’leri temizle.','Factory-reset and remove all images and volumes.'),L('API’yi kimliksiz şekilde tüm ağa aç.','Expose an unauthenticated API to the entire network.')],
 L('CLI ve engine farklı bileşenlerdir; bağlantı hatası proje kodunun derlenmediğini göstermez.','CLI and engine are separate components; connectivity failure does not prove a compilation defect.'),
 L('docker context show, docker info ve engine uygulamasının durumunu incele.','Inspect docker context show, docker info and the engine application status.'),
 L('Doğru engine/context’i başlat veya seç; izin/endpoint sorununu kanıta göre düzelt.','Start or select the correct engine/context; repair permissions or endpoint configuration based on evidence.'),
 L('docker info ardından güvenilir mevcut container’ların durumunu kontrol et.','Verify docker info and then inspect trusted existing containers.'),'docker');
 add('docker-port-busy','devops',L('Docker · port eşleme','Docker · port mapping'),'beginner',L('Host portu zaten kullanılıyor','Host port already in use'),
 'docker run -p 8080:80 example-web\nBind for 0.0.0.0:8080 failed: port is already allocated',
 L('8080 host portu dolu. Güvenli teşhis nedir?','Host port 8080 is occupied. What is a safe diagnostic step?'),
 L('Portu kullanan süreç/container’ı belirle; uygun alternatif eşleme veya kontrollü durdurma seç.','Identify the owning process/container; choose an alternative mapping or a controlled stop.'),
 [L('Tüm süreçleri zorla sonlandır.','Force-terminate all processes.'),L('Container içindeki 80 portunu değiştirmek host çakışmasını her durumda çözer.','Changing only container port 80 always resolves the host conflict.')],
 L('Eşlemenin solundaki host portu başka bir dinleyiciyle çakışıyor.','The host port on the left side of the mapping conflicts with another listener.'),
 L('docker ps port listesini ve işletim sistemi dinleyicisini incele.','Inspect docker ps port mappings and the operating system listener.'),
 L('Gerekirse 127.0.0.1:8081:80 gibi uygun yerel eşleme seç; bağımlı istemci URL’sini güncelle.','Choose an appropriate local mapping such as 127.0.0.1:8081:80 when needed and update the client URL.'),
 L('Yeni host adresinden erişimi ve gereksiz ağ açılımı olmadığını doğrula.','Verify access on the new host address and that exposure is no broader than intended.'),'port');
 add('k8s-image-pull','devops',L('Kubernetes · image çekme','Kubernetes · image pull'),'intermediate',L('Pod: ImagePullBackOff','Pod: ImagePullBackOff'),
 'Pod api-7f9: Waiting\nReason: ImagePullBackOff\nEvents: failed to pull image registry.example/api:release-42',
 L('Uygulama logu yok; image çekilemiyor. İlk nereden kanıt toplarsın?','There are no application logs; the image cannot be pulled. Where do you collect evidence?'),
 L('Pod events içinde image adı/tag, registry erişimi ve imagePullSecrets’i kontrol et.','Inspect Pod events, image/tag, registry access and imagePullSecrets.'),
 [L('Uygulamanın business kodunu rastgele değiştir.','Randomly edit business logic.'),L('Tüm registry parolalarını public loga yaz.','Print every registry password into public logs.')],
 L('Container henüz başlatılamadı; image çekme denemeleri artan beklemeyle tekrarlanıyor.','The container has not started; image pull attempts are retried with increasing delay.'),
 L('kubectl describe pod çıktısındaki olayları ve deployment image tanımını incele.','Inspect events in kubectl describe pod and the deployment image specification.'),
 L('Yanlış tag, erişim veya ağ problemini düzelt; secret değerini teşhis çıktısında paylaşma.','Fix the evidenced tag, authorization or network issue without exposing secret values.'),
 L('Pod’un Running/Ready olmasını ve beklenen image sürümünün çalıştığını doğrula.','Verify the Pod becomes Running/Ready with the intended image version.'),'image');
 add('data-csv-conversion','data',L('Veri hattı · bozuk satır','Data pipeline · malformed row'),'intermediate',L('CSV batch bir satırda durdu','CSV batch stops on one row'),
 'row 814: price="N/A"\nfloat(row["price"])\nValueError',
 L('Bazı satırlar sayısal sözleşmeye uymuyor. Veri kaybetmeden nasıl ilerlersin?','Some rows violate the numeric contract. How do you proceed without losing data?'),
 L('Şemayı ve N/A anlamını doğrula; bozuk satırları kayda/karantinaya alıp kontrollü yeniden işleme tasarla.','Validate the schema and meaning of N/A; record/quarantine invalid rows and design controlled reprocessing.'),
 [L('Hatalı satırı sessizce at ve batch’i tam başarılı say.','Silently drop the row and mark the batch fully successful.'),L('Tüm bilinmeyen fiyatları 0 olarak kaydet.','Store every unknown price as zero.')],
 L('Dönüşüm hatası eksik/geçersiz veri olabilir; bilinmeyen fiyat sıfır fiyatla aynı değildir.','Conversion failure may represent missing or invalid data; unknown price is not the same as zero.'),
 L('Satır kimliğini, kaynak şemasını ve hata sayısını hassas veriyi açığa çıkarmadan kaydet.','Record row identity, source schema and error counts without exposing sensitive data.'),
 L('Eksik değer politikasını açık uygula; retry aynı geçerli kayıtları çoğaltmasın.','Apply an explicit missing-value policy and ensure retries do not duplicate valid records.'),
 L('Bozuk satırlı batch’i tekrar çalıştır; karantina sayısını ve tekil geçerli kayıtları doğrula.','Rerun a batch with invalid rows; verify quarantine counts and uniqueness of valid records.'),'python');
 add('mobile-effect-repeat','mobile',L('Android · Compose effect','Android · Compose effect'),'intermediate',L('Recomposition her seferinde istek başlatıyor','Every recomposition starts a request'),
 '@Composable fun Profile() {\n  scope.launch { loadProfile() }\n  // render ...\n}',
 L('Composable gövdesinde başlatılan iş tekrarlanıyor. Daha uygun tasarım hangisi?','Work launched in the composable body repeats. Which design is more appropriate?'),
 L('İşi state holder veya uygun anahtarlı LaunchedEffect içine taşı; yaşam döngüsü ve iptali tanımla.','Move work to a state holder or appropriately keyed LaunchedEffect; define lifecycle and cancellation.'),
 [L('Recomposition’ı tamamen engelle.','Prevent all recomposition.'),L('Her tekrar için ayrı global coroutine aç.','Create a new global coroutine for each repetition.')],
 L('Composable gövdesi birden fazla kez çalışabilir; yan etkiler kontrollü yürütülmelidir.','Composable bodies may execute repeatedly; side effects need controlled execution.'),
 L('Çağrı sayısını, effect anahtarını ve ekran ömrünü izle.','Trace call counts, effect keys and screen lifetime.'),
 L('Uygun effect/state sahibi seç; parametre değişince eski işi iptal edip yeni veriyi yükle.','Choose the correct effect/state owner; cancel stale work and reload when relevant parameters change.'),
 L('Ekranı yeniden çiz, parametreyi değiştir ve ekranı kapat; beklenen sayıda iş başlasın.','Recompose, change parameters and leave the screen; verify the expected work count.'),'compose');
 add('ai-preprocess-drift','ai',L('ML · eğitim ve servis farkı','ML · training/serving mismatch'),'intermediate',L('Model eğitimde iyi, serviste bozuluyor','Model degrades when served'),
 'Training: scaler.fit_transform(train)\nServing: raw features -> model.predict\nPrediction quality drops',
 L('Eğitimdeki dönüşüm serviste yok. İlk hangi hipotezi sınarsın?','Serving omits the training transformation. Which hypothesis do you test first?'),
 L('Aynı fit edilmiş preprocessing pipeline’ının tahminde de kullanıldığını kontrol et.','Check that prediction uses the same fitted preprocessing pipeline.'),
 [L('Her istekte scaler’ı tek örneğe yeniden fit et.','Refit the scaler on each individual request.'),L('Test verisine fit ederek kaliteyi yükselt.','Fit on test data to improve the reported quality.')],
 L('Modelin beklediği özellik uzayı ile servis girdisi farklı; veri sızıntısı olmadan tutarlılık gerekir.','The model expects a different feature space than serving provides; consistency must avoid data leakage.'),
 L('Feature sırası, dönüşüm parametreleri ve model/pipeline sürümünü karşılaştır.','Compare feature order, transformation parameters and model/pipeline versions.'),
 L('Eğitimde fit edilen pipeline’ı sürümleyip serviste transform/predict için kullan.','Version the pipeline fitted during training and use it for transform/predict in serving.'),
 L('Sabit bir örneğin yerel ve servis tahminini karşılaştır; bağımsız test setini fit işleminden ayır.','Compare local and served predictions for fixed inputs; keep the holdout set separate from fitting.'),'ml');
 add('test-order-leak','testing',L('Test · paylaşılan durum','Testing · shared state'),'intermediate',L('Test tek başına geçiyor, birlikte kalıyor','Test passes alone but fails in the suite'),
 'shared_items = []\nTest A appends to shared_items\nTest B expects shared_items == []\nB passes alone; fails after A',
 L('Test sırası sonucu değiştiriyor. Hangi düzeltme daha sağlam?','Test order changes the result. Which repair is more robust?'),
 L('Her test için bağımsız fixture kur; değiştirilen dış/paylaşılan durumu temizle.','Create an independent fixture for each test and clean up modified shared/external state.'),
 [L('Testleri her zaman B sonra A sırasına zorla.','Force the tests to always run B then A.'),L('B’nin assertion’ını kaldır.','Remove the assertion from B.')],
 L('Bir testin yan etkisi diğerine sızıyor; tek başına geçmek izolasyonu kanıtlamaz.','A test side effect leaks into another; passing alone does not prove isolation.'),
 L('Global değişken, veritabanı, dosya ve mock ömürlerini incele.','Inspect global variables, databases, files and mock lifetimes.'),
 L('setUp/tearDown veya eşdeğer fixture ile gerekli başlangıç ve temizliği tanımla.','Define setup and cleanup using setUp/tearDown or equivalent fixtures.'),
 L('Testleri ayrı, birlikte ve farklı sıralarda tekrar çalıştır; aynı sonuçları bekle.','Run tests separately, together and in different orders; expect identical results.'),'test');
 return rows.map((r,index)=>{
  const answer=index%3,options=[...r.wrong];options.splice(answer,0,r.correct);
  const explain=L(`Mesajın anlamı: ${r.meaning.tr}\n\nToplanacak kanıt: ${r.evidence.tr}\n\nGüvenli düzeltme: ${r.fix.tr}\n\nDoğrulama: ${r.verify.tr}`,`Meaning: ${r.meaning.en}\n\nEvidence to collect: ${r.evidence.en}\n\nSafe repair: ${r.fix.en}\n\nVerification: ${r.verify.en}`);
  return {id:`diagnostic-${r.id}-20261008`,version:'2026-10-08.3',kind:'error-diagnostic',format:'diagnosis',minutes:r.level==='beginner'?3:5,area:r.area,topic:r.topic,level:r.level,title:r.title,code:r.code,prompt:r.prompt,options,answer,explain,hint:r.evidence,checks:[L('Mesajın kanıtladığı durum ile hipotezi ayırdım.','I separated what the message proves from a hypothesis.'),L('Düzeltmeyi doğrulayacak test belirttim.','I specified a test to verify the repair.')],source:originalReference(...refs[r.ref])};
 });
}