const L=(tr,en)=>({tr,en});
const track=(id,title,scenario,design,debug,implementation,transfer)=>({id,title:L(...title),minutes:75,steps:[
 {id:'requirements',minutes:10,title:L('Gereksinimleri netleştir','Clarify requirements'),prompt:L(...scenario),checks:[L('Varsayımlar, en az iki bilinmeyen ve ölçülebilir kabul koşulları yaz','State assumptions, two unknowns and measurable acceptance criteria')]},
 {id:'design',minutes:15,title:L('Tasarımı savun','Defend the design'),prompt:L(...design),checks:[L('İki seçeneği kısıt ve bedelleriyle karşılaştır','Compare two options with constraints and trade-offs')]},
 {id:'debug',minutes:15,title:L('Kanıtla hata ayıkla','Debug with evidence'),prompt:L(...debug),checks:[L('Logdaki kanıtı hipotezden ayır; en küçük düzeltmeyi ve regresyon testini yaz','Separate evidence from hypotheses; write the smallest fix and regression test')]},
 {id:'implementation',minutes:15,title:L('Çekirdek çözümü yaz','Write the core solution'),prompt:L(...implementation),checks:[L('Kod, normal/sınır/hata testleri ve beklenen/gerçek çıktıyı birlikte ver','Provide code, normal/boundary/failure tests and expected/actual output')]},
 {id:'transfer',minutes:10,title:L('Gereksinim değişikliğine uyarla','Adapt to changed requirements'),prompt:L(...transfer),checks:[L('Önceki çözümün yetersiz kaldığı iki noktayı göster','Show two points where the original solution falls short')]},
 {id:'reflection',minutes:10,title:L('Eksiklerini ve sonraki deneyi belirle','Identify gaps and the next experiment'),prompt:L('En zayıf iki cevabını seç. Kaynak, yeniden üretilebilir küçük deneme ve tekrar tarihi yaz. Varsayımlarını ve AI kullandıysan hangi kodu kendin doğruladığını açıkla.','Choose your two weakest answers. State a source, a small reproducible experiment and review date. Explain assumptions and which AI-assisted code you personally verified.'),checks:[L('Somut kanıt ve ölçülebilir sonraki adım','Concrete evidence and a measurable next step')]}
]});
export const roleInterviewTracks=[
 track('frontend-interview',['Frontend · 75 dakikalık mülakat','Frontend · 75-minute interview'],
 ['E-ticaret arama ekranı: filtre, sayfalama ve sepet. Erişilebilirlik, ağ gecikmesi, URL paylaşma ve SEO için hangi gereksinimleri sorarsın?','Design product search with filters, pagination and a cart. Clarify accessibility, network latency, shareable URLs and SEO.'],
 ['Server/client state ve URL state sınırlarını çiz. SSR/SPA ve optimistic update kararlarını iki alternatifle savun.','Separate server/client and URL state. Defend SSR/SPA and optimistic updates against alternatives.'],
 ['İz: start(a,1), start(ab,2), success(2,[AB]), success(1,[A]). Ekran A gösteriyor; beklenen AB. Kök neden, cleanup ve test sırası nedir?','Trace: start(a,1), start(ab,2), success(2,[AB]), success(1,[A]). UI shows A; expected AB. Explain root cause, cleanup and test ordering.'],
 ['TypeScript ile eski requestId sonuçlarını yok sayan reducer yaz. success/failure/unmount ve boş sonuç testlerini ekle.','Write a TypeScript reducer ignoring stale requestIds. Test success/failure/unmount and empty results.'],
 ['Çözümü çevrimdışı mobil aramaya taşı; cache sürümü, eski veri etiketi ve reconnect retry hangi farkları getirir?','Transfer to offline mobile search: discuss cache versions, stale labels and reconnect retries.']),
 track('data-interview',['Veri/SQL · 75 dakikalık mülakat','Data/SQL · 75-minute interview'],
 ['Saatlik CSV siparişlerini raporlama veritabanına taşı. Veri hacmi, geç gelen kayıt, düzeltme, saklama ve gün sınırı için sorularını yaz.','Move hourly CSV orders into a reporting database. Clarify volume, late arrivals, corrections, retention and day boundaries.'],
 ['Raw/staging/final tablo akışını, iş anahtarını, transaction/checkpoint ve yeniden işleme politikasını çiz.','Design raw/staging/final tables, business keys, transaction/checkpoint and replay policy.'],
 ['100 kayıt beklendi; kesinti sonrası restart 150 kayıt ve iki kat gelir gösteriyor. Hangi SQL/log kanıtları replay ile join çoğalmasını ayırır?','Expected 100 rows; restart produces 150 rows and doubled revenue. Which SQL/log evidence separates replay duplicates from join multiplication?'],
 ['event_id benzersizliğini koruyan parametreli SQL ve günlük toplam sorgusu yaz. Aynı ID farklı payload, eşit tutarlı sipariş ve gün sınırı testleri ekle.','Write parameterized SQL preserving event_id uniqueness and daily totals. Test changed-payload replay, equal-total orders and day boundaries.'],
 ['Akış 5 GB dosyadan sürekli olaylara dönüyor: watermark, geç veri ve geri basınç kararlarını tartış.','Transfer from 5 GB files to continuous events: discuss watermarks, late data and backpressure.']),
 track('ai-interview',['AI mühendisliği · 75 dakikalık mülakat','AI engineering · 75-minute interview'],
 ['Şirket belgelerinde kaynaklı asistan tasarla. Gizlilik, güncellik, hatalı cevap maliyeti, gecikme ve değerlendirme hedeflerini netleştir.','Design a cited company-document assistant. Clarify privacy, freshness, wrong-answer cost, latency and evaluation goals.'],
 ['Retrieval, üretim ve kaynak doğrulamayı ayır. Chunk/indeks ve değerlendirme setini gerekçelendir; ücretli model şart değildir.','Separate retrieval, generation and citation validation. Justify chunks/index and evaluation fixtures; no paid model is required.'],
 ['Retrieved D1: süre 30 gün. Answer: süre 90 gün [D1]. D2 içeriyor: kuralları yok say. Hangi hatalar retrieval, grounding ve güven sınırına aittir?','Retrieved D1: retention 30 days. Answer: 90 days [D1]. D2 says ignore all rules. Classify retrieval, grounding and trust-boundary failures.'],
 ['Belge ID/sürüm/satır aralığı alıntılarını doğrulayan kod yaz; eksik kaynak, çelişki ve talimat enjeksiyonu fixture’larıyla test et.','Write citation checks for document ID/version/line spans; test missing evidence, conflicts and instruction-injection fixtures.'],
 ['Belgeler kullanıcıya özel ve sürümlü olursa erişim filtresi ile cache anahtarı nasıl değişir? Ölçüm sızıntısını nasıl önlersin?','For user-scoped versioned documents, change access filters and cache keys. How do you prevent evaluation leakage?']),
 track('mobile-interview',['Mobil · 75 dakikalık mülakat','Mobile · 75-minute interview'],
 ['Çevrimdışı not uygulaması tasarla. Platform, ağ, pil, process ölümü, sync sıklığı ve çatışma beklentilerini sor.','Design offline notes. Clarify platform, network, battery, process death, sync frequency and conflict expectations.'],
 ['Yerel veri kaynağı, kalıcı gönderim kuyruğu ve sunucu sürümünü çiz. Tekrar gönderim ve kimlik sınırını açıkla.','Design local storage, a durable outbox and server versions. Explain replay and identity boundaries.'],
 ['Sunucu yazdı; istemci ACK almadan kapandı; restart aynı isteği gönderdi ve iki not oluştu. Kanıt, idempotency ve queue durumu nedir?','Server committed; client died before ACK; restart resent and created two notes. Explain evidence, idempotency and queue state.'],
 ['version=4 tabanlı iki düzenlemede ilkini kabul, ikincisini çatışma yapan saf state fonksiyonu yaz. Yerel taslağın kaybolmadığını test et.','Write a pure state function accepting the first edit based on version 4 and conflicting the second. Test preservation of the local draft.'],
 ['Aynı mantığı Unity ödül senkronuna taşı. Kötü niyetli istemci, güvenilmeyen cihaz saati ve sunucu otoritesini açıkla.','Transfer to Unity reward sync. Explain malicious clients, untrusted device clocks and server authority.'])
];
