import {practicalCodeTasks} from '../sandbox/practical-tasks.mjs';
const L=(tr,en)=>({tr,en});
export const projects=[
 {id:'api-service',title:L('Güvenli görev ve sipariş API’si','Safe tasks and orders API'),areas:['api','sql','testing'],minutes:90,stages:['project-api-validation','project-api-idempotency','project-api-transfer'],brief:L('Sözleşme yaz, tekrar/yetki hatasını gider, aynı ilkeleri başka kaynağa taşı. Sonunda neden gerçek bir veritabanı transaction’ına ihtiyacın olduğunu açıkla.','Write a contract, fix retry/ownership bugs, then transfer the same rules to another resource. Explain why a real database transaction is still needed.')},
 {id:'search-ui',title:L('Arama ekranından çevrimdışı mobil senkrona','From search UI to offline mobile sync'),areas:['frontend','mobile','testing'],minutes:85,stages:['project-ui-reducer','project-ui-debug','project-ui-transfer'],brief:L('Durum makinesi kur, olay izindeki yarış hatasını yeniden üret ve mobil çakışma politikasını uygula.','Build a state machine, reproduce a race from an event trace and implement a mobile conflict policy.')},
 {id:'event-pipeline',title:L('Olay hattından AI retrieval’a','From event pipeline to AI retrieval'),areas:['data','ai','structures'],minutes:90,stages:['project-data-ingest','project-data-debug','project-data-transfer'],brief:L('İçe aktarma doğrulaması, tekrarları ayırma, toplama hatası ve kaynaklı belge sıralaması üzerinde çalış.','Practice ingestion validation, deduplication, aggregation debugging and grounded document ranking.')}
];
const review=(id,area,title,prompt,code,reference,criteria,url)=>({id,area,title:L(...title),prompt:L(...prompt),code,reference,criteria:criteria.map((text,i)=>({id:'c'+(i+1),text:L(...text)})),source:{label:'Resmi dokümantasyon / Official documentation',url},modality:'review',minutes:20});
export const reviewTasks=[
 review('review-sql-injection','sql',['SQL kod incelemesi','SQL code review'],['Bu endpoint’te güvenlik ve performans sorunlarını bul. Sömürü örneği, güvenli düzeltme ve regresyon testi yazılı olarak açıkla.','Find security and performance issues in this endpoint. Explain an exploit example, safe fix and regression test.'],`app.get('/users', async (req,res) => {\n const rows = await db.query("SELECT * FROM users WHERE name='" + req.query.name + "'");\n res.json(rows);\n});`,'SQL string concatenation permits SQL injection. Use parameterized queries, validate query length/type, return explicit fields, enforce authorization and limit result size.',[['Bir injection girdisi ve etkisini göster','Show an injection input and effect'],['Parametreli sorgu ve veri erişim sınırını anlat','Explain parameterized query and access boundaries'],['Güvenli girdi ile saldırı regresyon testini ayır','Distinguish valid-input and attack regression tests']],'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'),
 review('review-react-effect','frontend',['React effect incelemesi','React effect review'],['Eski yanıtın yeni aramayı ezmesini ve unmount durumunu teşhis et. Düzeltmeyi ve iki istek sırasını test etme planını açıkla.','Diagnose stale responses overwriting search and unmount behavior. Explain a fix and a test plan for two request orders.'],`useEffect(() => {\n fetch('/search?q=' + query).then(r=>r.json()).then(setItems);\n}, [query]);`,'Responses can arrive out of order. Encode query; check HTTP status; cleanup with AbortController or ignore flag/request generation; preserve error/loading semantics. A race test resolves request 2 before request 1.',[['Yarışın hangi sırada gerçekleştiğini açıkla','Explain the ordering that creates the race'],['Cleanup ve aktif istek kontrolünü gerekçelendir','Justify cleanup and active-request checks'],['HTTP hata, boş sonuç ve yarış testini ekle','Include HTTP failure, empty and race tests']],'https://react.dev/learn/synchronizing-with-effects'),
 review('review-dotnet-async','dotnet',['.NET kaynak ve iptal incelemesi','.NET resource and cancellation review'],['Bu kodun kilitlenme/kaynak tüketimi riskini açıkla; async ve iptal akışını nasıl değiştirirsin?','Explain blocking/resource risks; how would you change async and cancellation flow?'],`public IActionResult Get() {\n var client = new HttpClient();\n var text = client.GetStringAsync(url).Result;\n return Ok(text);\n}`,'Blocking .Result consumes request threads; ASP.NET Core does not generally have the classic synchronization-context deadlock. Use async Task<IActionResult>, await, injected HttpClient/IHttpClientFactory and propagate RequestAborted/CancellationToken; handle errors and timeout explicitly.',[['Blocking ile deadlock iddiasını ayır','Distinguish blocking from a deadlock claim'],['await, HttpClient yaşam döngüsü ve iptali açıkla','Explain await, HttpClient lifetime and cancellation'],['İptal ve timeout testlerini belirt','Specify cancellation and timeout tests']],'https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines'),
 review('review-k8s-probe','devops',['Kubernetes rollout incelemesi','Kubernetes rollout review'],['Bağımlılık kesilince container sürekli restart oluyor. Probe tasarımını, gözlemi ve geri alma koşulunu açıkla.','The container restarts repeatedly when a dependency fails. Explain probe design, observability and rollback conditions.'],`livenessProbe:\n  httpGet: {path: /ready, port: 8080}\n  initialDelaySeconds: 2\n  periodSeconds: 2`,'Readiness controls traffic, liveness restarts unhealthy containers, startup protects slow boot. A dependency outage should not automatically trigger process restarts. Define separate endpoints and measured thresholds; inspect events/logs and rollout metrics before rollback.',[['Readiness/liveness/startup görevlerini ayır','Distinguish readiness/liveness/startup roles'],['Restart döngüsünün nedenini ve düzeltmesini açıkla','Explain the restart loop and fix'],['Gözlem ve rollback ölçütü belirt','Specify observability and rollback criteria']],'https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/'),
 review('review-unity-lifetime','unity',['Unity olay ve yaşam döngüsü incelemesi','Unity event and lifetime review'],['Sahne tekrar açıldıkça aynı callback çoğalıyor. Kök nedeni, yaşam döngüsü düzeltmesini ve kanıtlayan deneyi yaz.','Each scene reload duplicates a callback. Explain the root cause, lifetime fix and an experiment that proves it.'],`void OnEnable() { GameEvents.ScoreChanged += UpdateScore; }\nvoid UpdateScore(int value) { label.text = value.ToString(); }`,'Subscriptions can retain disabled/destroyed subscribers or duplicate handlers. Pair OnEnable subscription with OnDisable unsubscription to the same handler; confirm publisher lifetime and initialization. Repeated enable/disable and scene reload should produce one callback, no missing reference.',[['Publisher/subscriber yaşam süresini açıkla','Explain publisher/subscriber lifetimes'],['Aynı handler ile unsubscribe eşlemesini yap','Pair unsubscribe with the same handler'],['Sahne tekrarları ve callback sayısını test et','Test scene reloads and callback counts']],'https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnDisable.html'),
 review('review-ai-injection','ai',['RAG güvenlik incelemesi','RAG security review'],['Belge içindeki talimat sistemi yanıltıyor. Güven sınırı, kaynaklı cevap ve değerlendirme planını açıkla.','Instructions in a document mislead the system. Explain trust boundaries, grounded answers and an evaluation plan.'],`prompt = systemRules + retrievedDocument + userQuestion;\nreturn model(prompt);`,'Retrieved content is untrusted evidence, not policy. Delimit roles and content, limit tools/permissions, require citations tied to retrieved spans and abstain without support. Prompt separation alone is not a guarantee; test injection, empty retrieval, conflicting evidence and tool misuse.',[['Güvenilmeyen belgeyi talimattan ayır','Separate untrusted documents from instructions'],['Kaynak doğrulama ve çekimser kalma koşulunu yaz','Define citation validation and abstention'],['Saldırgan ve boş/çelişkili örnekleri test et','Test adversarial and empty/conflicting evidence']],'https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html'),
 review('review-data-transaction','data',['Batch transaction incelemesi','Batch transaction review'],['Yarıda kesilen batch tekrar gönderildiğinde neler olur? Transaction ve idempotency çözümünü, veri kaybı testini açıkla.','What happens when a partially completed batch is retried? Explain transaction/idempotency design and data-loss tests.'],`for (const event of batch) {\n await db.insert(event);\n}\nawait markBatchComplete(batch.id);`,'Partial writes can survive failure. Decide atomic batch or per-event idempotency; use stable event keys with unique constraints and a transaction including status updates where atomicity is required. Test failure after N records, retries and concurrent duplicates. Avoid marking completion before durable data.',[['Kısmi yazma ve retry sonucunu göster','Show partial-write and retry outcomes'],['Unique anahtar ve transaction sınırını açıkla','Explain unique keys and transaction boundaries'],['Hata enjeksiyonu ve eşzamanlı tekrar testi belirt','Specify failure injection and concurrent retry tests']],'https://www.postgresql.org/docs/current/tutorial-transactions.html'),
 review('review-game-timestep','game',['Oyun fizik incelemesi','Game physics review'],['FPS artınca hareket değişiyor. Zaman adımı, input ve physics döngüsünü ayırarak düzeltmeyi ve testi açıkla.','Movement changes at higher FPS. Explain a fix separating timestep, input and physics loops, plus a test.'],`void Update() {\n rb.AddForce(Vector3.forward * speed);\n transform.position += Vector3.forward * speed;\n}`,'Physics forces belong in FixedUpdate with correct force mode/timestep semantics. Sample input appropriately; do not mix direct transform motion with Rigidbody physics. For transform motion use deltaTime; do not blindly multiply every force mode by deltaTime. Test different render FPS with fixed physics timestep.',[['Frame ile fizik zaman adımını ayır','Distinguish frame and physics timesteps'],['Rigidbody/transform ve force mode davranışını açıkla','Explain Rigidbody/transform and force-mode behavior'],['Farklı FPS ile karşılaştırmalı test belirt','Specify comparative tests at different FPS']],'https://docs.unity3d.com/ScriptReference/MonoBehaviour.FixedUpdate.html')
];
export const practicalTasks=[...practicalCodeTasks,...reviewTasks];
export function publicPractice(t){const {tests,reference,hint,...out}=t;return out;}
export function practiceProgress(records){
 return projects.map(p=>{const stageResults=p.stages.map(id=>{const latest=records.filter(r=>r.task_id===id).at(-1);let report;try{report=JSON.parse(latest?.result||'{}');}catch{report={};}return {id,passed:report.verification==='server-verified'&&report.total>0&&report.passed===report.total,lastAt:latest?.created_at||null};});return {...p,stageResults,completed:stageResults.every(s=>s.passed),completedStages:stageResults.filter(s=>s.passed).length};});
}
