// Original RealDev assessment items grounded in primary references.
// Source exercise wording has not been copied.
const bi = (tr,en) => ({tr,en});
const sourceLabels={frontend:'MDN / React Docs',dotnet:'Microsoft Learn',git:'GitHub Skills / Git Docs',sql:'Chinook / PostgreSQL',unity:'Unity Documentation',devops:'Kubernetes Documentation',api:'MDN HTTP',testing:'Microsoft .NET Testing Docs',ai:'AI Engineering Course',data:'Apache Airflow Docs',mobile:'Android Developers',game:'Unity Documentation'};
const rows = [
  ['source-js-fetch-20261005','frontend','Fetch: HTTP yanıtı','Fetch: HTTP responses','fetch("/api/items") 404 Response ile tamamlandı. catch çalışmadı. İlk neyi kontrol edersin?','fetch("/api/items") completed with a 404 Response. catch did not run. What do you check first?','response.ok/status değerini; HTTP başarısızlığı her zaman Promise rejection değildir.','response.ok/status; an unsuccessful HTTP response is not always a Promise rejection.','HTTP durum kodunu ayrıca denetle.','Check the HTTP status explicitly.','https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch',['catch zorla çağırmayı.','Force catch to run.','response.ok/status kontrol etmeyi.','Check response.ok/status.','CORS’u tamamen kapatmayı.','Disable CORS completely.'],1],
  ['source-dotnet-async-20261005','dotnet','I/O-bound async akış','I/O-bound async flow','Ağ çağrısını yapan C# metodunu asenkron biçimde beklemek için en uygun yaklaşım hangisidir?','What is the appropriate way to await a C# network call asynchronously?','Async API’yi await etmek ve asenkronluğu çağrı zincirinde korumak.','Await the async API and preserve asynchronous flow through the call chain.','Async I/O bekleme ile CPU-bound paralelliği ayır.','Distinguish async I/O waiting from CPU-bound parallelism.','https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/',['Görevi .Result ile senkron bloklamak.','Block synchronously with .Result.','Async API’yi await etmek.','Await the async API.','Beklemek için Thread.Sleep kullanmak.','Use Thread.Sleep to wait.'],1],
  ['source-git-pr-review-20261005','git','İncelenebilir PR','A reviewable PR','Bir PR refactor, ürün davranışı ve biçim düzenlemesini karıştırıyor. Ekip incelemesini nasıl iyileştirirsin?','A PR mixes refactoring, product behavior and formatting. How do you improve review?','Mümkünse değişiklikleri dar amaçlı parçalara ayırıp davranışı ve testleri açıkça belirtmek.','Split the changes into focused units where practical, and state behavior and tests clearly.','Reviewer’ın risk ve test kanıtını görebileceği kapsam seç.','Choose a scope that lets reviewers see risk and test evidence.','https://github.com/skills/introduction-to-github',['İnceleme açıklamasını boş bırakmak.','Leave the review description empty.','Değişiklikleri odaklı parçalara bölüp test kanıtı eklemek.','Split changes into focused parts and include test evidence.','Tüm değişiklikleri tek minified çıktıda saklamak.','Hide all changes in one minified output.'],1],
  ['source-sql-fk-20261005','sql','Foreign key ile ilişki','Model a relation with a foreign key','Bir invoice geçersiz customer_id ile kaydedilmemeli. Hangi veritabanı kısıtı uygundur?','An invoice must not save an invalid customer_id. Which database constraint fits?','Invoice.customer_id için Customer tablosuna foreign key tanımlamak.','Define a foreign key from Invoice.customer_id to Customer.','İlişki geçerliliğini uygulama dışında da koru.','Enforce relationship integrity beyond the application layer.','https://github.com/lerocha/chinook-database',['Sadece UI’da açılır liste doğrulaması.','Only a UI dropdown check.','Foreign key constraint.','A foreign key constraint.','Invoice tablosunu her istekte silmek.','Drop the Invoice table on each request.'],1],
  ['source-unity-lifecycle-20261005','unity','Fizik ve render döngüsü','Physics and render loops','Rigidbody’ye uygulanan fizik kuvvetinin render FPS’e bağlı olmaması için hangi callback kullanılır?','Which callback applies Rigidbody physics independent of render FPS?','FixedUpdate; girdi gerekiyorsa uygun değeri ayrıca yakalayıp aktarmak.','FixedUpdate, carrying captured input deliberately when needed.','Fizik timestep’i ile render frame’ini ayır.','Separate the physics timestep from rendered frames.','https://docs.unity3d.com/6000.0/Documentation/Manual/fixed-updates.html',['OnGUI.','OnGUI.','FixedUpdate.','FixedUpdate.','Her render frame’inde sabit kuvvet uygulamak.','Apply a fixed force on every render frame.'],1],
  ['source-devops-readiness-20261005','devops','Hazır olma probe’u','Readiness probe','Uygulama process’i yaşıyor ama başlangıç verisini henüz yüklemedi. Hangi probe trafiği bekletmeye yardımcı olur?','The process is alive but has not loaded startup data. Which probe can withhold traffic?','Readiness probe.','Readiness probe.','Trafiğe hazır olma ile yeniden başlatma gereğini ayır.','Separate traffic readiness from restart needs.','https://kubernetes.io/docs/concepts/workloads/pods/probes/',['Liveness her geçici durumda başarısız olmalı.','Liveness should fail for every transient condition.','Readiness.','Readiness.','Kubernetes probe kullanmamak.','Use no Kubernetes probe.'],1],
  ['source-api-retry-20261005','api','Timeout ve çift işlem','Timeout and duplicate operation','POST /payments zaman aşımı aldı; sunucu çekimi tamamlamış olabilir. Güvenli tekrar nasıl tasarlanır?','POST /payments timed out; the server may have charged the card. How should retry be designed?','Aynı kararlı idempotency key ile sunucu tarafındaki sonucu uzlaştırmak.','Reconcile the server result with the same stable idempotency key.','Timeout, sunucudaki sonucu göstermez.','A timeout does not reveal the server result.','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Methods/POST',['Her denemede yeni işlem kimliği yaratmak.','Create a new operation ID each attempt.','Kararlı anahtar ve sunucu tarafı idempotency kaydı kullanmak.','Use a stable key and server-side idempotency record.','İlk denemede hata varsa retry’ı sonsuz yapmak.','Retry infinitely after any first-attempt error.'],1],
  ['source-test-isolation-20261005','testing','Sıra bağımlı test','Order-dependent test','Bir test sadece kendinden önce başka bir test çalışınca geçiyor. İlk hangi kusuru araştırırsın?','A test only passes after another test runs. What do you investigate first?','Paylaşılan mutable state, test sırası ve temizlenmeyen test verisini.','Shared mutable state, execution order and uncleaned test data.','Testi bağımsız çalıştır ve önkoşullarını denetle.','Run the test alone and inspect its preconditions.','https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices',['Test sırasını sabitleyip sorunu gizlemeyi.','Pin test order to hide the issue.','Paylaşılan durum ve temizleme eksikliğini.','Shared state and missing cleanup.','Başarısız assertion’ı silmeyi.','Delete the failing assertion.'],1],
  ['source-ai-grounding-20261005','ai','Kaynağa dayalı RAG','Grounded RAG answer','Retriever birbiriyle çelişen iki sürüm belgesi getirdi. Yanıt üretirken ne yapmalısın?','The retriever returns two conflicting versions of a document. What should the answer do?','Sürüm ve tarih bağlamını karşılaştırıp hangi iddianın hangi kaynağa dayandığını göstermek; çözülemeyen çelişkiyi belirtmek.','Compare version/date context, tie each claim to its source, and disclose unresolved conflicts.','Getirilen parçalar otomatik olarak doğru veya güncel değildir.','Retrieved passages are not automatically correct or current.','https://github.com/amitshekhariitbhu/ai-engineering-course',['En yeni görünen pasajı kontrol etmeden kesin kabul etmek.','Treat the passage that looks newest as certainly correct without checking.','Kaynak sürümlerini karşılaştırıp kanıtı ve belirsizliği belirtmek.','Compare source versions and state evidence and uncertainty.','İki pasajı rastgele birleştirmek.','Combine both passages at random.'],1],
  ['source-data-etl-retry-20261005','data','ETL tekrar güvenliği','ETL retry safety','Batch’in bir bölümü yazıldıktan sonra iş başarısız oldu. Tekrar çalıştırmada yinelenen kayıt riskini nasıl azaltırsın?','A job failed after writing part of a batch. How do you reduce duplicates on retry?','Kararlı kayıt anahtarı ve idempotent upsert/checkpoint ile tekrar politikasını tasarlamak.','Design retries around stable record keys and idempotent upserts/checkpoints.','Kısmi commit ve tekrar uygulama etkisini incele.','Inspect partial commits and replay effects.','https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html',['Her retry’da yeni rastgele ID ile INSERT yapmak.','INSERT with a new random ID on every retry.','Kararlı anahtar ve idempotent yazma adımı kullanmak.','Use a stable key and idempotent write step.','Başarısızlığı görmezden gelip başarı işaretlemek.','Ignore the failure and mark success.'],1],
  ['source-mobile-state-20261005','mobile','Android geçici ekran state’i','Android transient screen state','Ekran döndükten sonra arama metni kayboluyor. En uygun ilk tasarım kararı hangisidir?','Search text disappears after rotation. What is a suitable first design choice?','Geçici UI state’ini uygun state holder/saved state mekanizmasıyla saklayıp restore etmek.','Save and restore transient UI state with an appropriate state holder/saved-state mechanism.','Activity’nin asla yeniden yaratılmayacağını varsayma.','Do not assume the Activity is never recreated.','https://developer.android.com/topic/libraries/architecture/saving-states',['Her tuşta değeri uzak veritabanına yazmak.','Write it to a remote database on every keystroke.','UI state’i lifecycle’a uygun biçimde korumak.','Preserve UI state in a lifecycle-appropriate way.','State’i yalnızca view çizim kodunda tutmak.','Keep state only in view drawing code.'],1],
  ['source-game-pooling-20261005','game','Oyun nesnesi pooling','Game object pooling','Sık create/destroy edilen mermiler GC takılmasına neden oluyor. Sonraki en iyi adım nedir?','Frequently created/destroyed bullets cause GC hitches. What is the next good step?','Profiler ile allocation’ı doğrulayıp sınırlı pool, state reset’i ve lifecycle temizliği ölçmek.','Verify allocations with a profiler, then measure a bounded pool with state resets and lifecycle cleanup.','Optimizasyondan sonra performansı tekrar ölç.','Measure performance again after the change.','https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Pool.ObjectPool_1.html',['Tüm nesneleri sahnede sınırsız etkin bırakmak.','Keep every object active in the scene without bounds.','Ölçerek pool boyutu ve reset lifecycle’ı tasarlamak.','Measure and design pool size and reset lifecycle.','Garbage collector’ı kapatmak.','Disable the garbage collector.'],1],
  ['source-git-fetch-20261005','git','Fetch sonrası ne değişti?','What changed after fetch?','git fetch origin tamamlandı. Bu komut mevcut çalışma dosyalarını otomatik birleştirdi mi?','git fetch origin completed. Did it automatically merge into working files?','Hayır. Uzak referansları güncelledi; farkı inceleyip merge/rebase ayrı yapılır.','No. It updated remote references; inspect differences and merge/rebase separately.','Fetch ve entegrasyon adımlarını ayır.','Separate fetching from integration.','https://git-scm.com/docs/git-fetch',['Evet, çalışma ağacındaki çatışmaları da çözdü.','Yes, it also resolved working-tree conflicts.','Hayır, fetch kendi başına merge/rebase yapmaz.','No, fetch alone does not merge/rebase.','Yerel commitleri sildi.','It deleted local commits.'],1],
  ['source-piston-hosting-20261006','devops','Piston’ı ücretsiz dene','Try Piston for free','Şimdilik sunucu satın almadan Python/C#/Java görevlerini kendi bilgisayarında denemek istiyorsun. Hangisi doğru kurulum ve canlıya geçiş bilgisidir?','You want to try Python/C#/Java tasks on your own PC without buying a server. Which setup and deployment statement is correct?','Docker’daki Piston ve RealDev yerel önizlemesini aynı bilgisayarda çalıştır; canlı Site’da 7/24 erişim gerekirse daha sonra sürekli açık makine veya kayıtlı özel tünel kur.','Run Docker Piston and the RealDev local preview on the same computer; if the live Site needs 24/7 access later, set up an always-on host or registered private tunnel.','Site’ın localhost adresi kullanıcının bilgisayarını değil, isteği yapan sunucuyu gösterir.','A Site’s localhost refers to the machine making the request, not the visitor’s computer.','https://github.com/engineer-man/piston',['Sadece alan adı satın alıp DNS kaydı oluşturmak.','Only buy a domain and add a DNS record.','Piston’ın 2000 portunu herkese açmak.','Expose Piston port 2000 to everyone.','Önce VPS satın almak; yerel deneme mümkün değildir.','Buy a VPS first; local practice is not possible.','Yerel deneme için Piston ve önizlemeyi aynı PC’de çalıştırmak; canlı 7/24 kullanım için sonradan host veya tünel seçmek.','Run Piston and preview on the same PC for local practice; choose a host or tunnel later for 24/7 live access.'],3,'Bu aşamada sunucu veya domain satın alman gerekmiyor. `scripts/start-piston.ps1` yerel Piston’ı 127.0.0.1:2000 üzerinde başlatır; aynı bilgisayarda `npm run dev` ile çalışan RealDev önizlemesi bu adrese erişebilir. Önizleme verileri ayrı `.local/preview-4317.sqlite` dosyasında tutulur ve canlı hesabına aktarılmaz. Bilgisayar kapalıyken yerel denemeler çalışmaz. Canlı Site’da herkese 7/24 hizmet etmek için daha sonra sürekli açık makine veya kayıtlı özel tünel gerekir; domain tek başına sunucu sağlamaz.','You do not need to buy a server or domain at this stage. `scripts/start-piston.ps1` starts local Piston at 127.0.0.1:2000; RealDev preview running on the same computer with `npm run dev` can reach it. Preview data stays in the separate `.local/preview-4317.sqlite` file and does not sync to your live account. Local practice stops when your computer is off. To serve everyone on the live Site 24/7, choose an always-on host or registered private tunnel later; a domain alone does not provide a server.','localhost isteği yapan makineyi gösterir: yerel önizlemede bilgisayarın, canlı Site’da ise Site sunucusu.','localhost means the requesting machine: your PC for local preview, the Site server for the live Site.','Gerçek bir hizmeti hangi makinenin çalıştırdığını ve önizleme verisinin nereye kaydedildiğini belirle.','Identify which machine runs the service and where preview data is stored.'],
];
export function createSourceTasks(version) {
  return rows.map(([id,area,titleTR,titleEN,promptTR,promptEN,explainTR,explainEN,hintTR,hintEN,url,optionPairs,answer,customExplainTR,customExplainEN,customHintTR,customHintEN]) => {
    const options = Array.from({length:optionPairs.length/2},(_,i)=>bi(optionPairs[i*2],optionPairs[i*2+1]));
    return {
      id, area, version, kind:'multiple-choice', minutes:3,
      title:bi(titleTR,titleEN), prompt:bi(promptTR,promptEN), code:'',
      options, answer, explain:bi(customExplainTR||explainTR,customExplainEN||explainEN),
      hint:bi(customHintTR||hintTR,customHintEN||hintEN),
      checks:[bi('Seçimimi teknik davranışa bağladım.','I related my choice to technical behavior.'),bi('Önemli hata veya güvenlik riskini belirttim.','I identified an important failure or safety risk.')],
      source:{label:area==='devops'&&id==='source-piston-hosting-20261006'?'Piston · official repository':sourceLabels[area]||'Official documentation',url,checkedAt:id==='source-piston-hosting-20261006'?'2026-10-06':'2026-10-05',note:'Original RealDev question based on this primary reference; source question text was not copied.'}
    };
  });
}
