(() => {
 const t=(tr,en)=>window.realdevLocale==='en'?en:tr,l=x=>x?.[window.realdevLocale==='en'?'en':'tr']||'',safe=x=>esc(x??'');
 let data=null,taskId='',trackId='',stepId='',busy=false,notice='',loading=false,drafts={},timer,saving=Promise.resolve();
 const button=(title,action,id='',disabled=false)=>`<button type="button" class="secondary-button" data-advanced="${action}" data-id="${id}" ${disabled?'disabled':''}>${title}</button>`;
 async function api(path,body,method='POST'){const r=await fetch('/api/'+path,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(55000)});const value=await r.json();if(!r.ok)throw Error(value.error||'request_failed');return value;}
 const errorText=e=>({project_stage_locked:t('Önce önceki aşamanın testlerini geçir.','Pass the previous stage tests first.'),piston_not_configured:t('Canlı kod servisi henüz bağlı değil. Başlangıcı indirip yerelde çalışabilirsin.','The hosted code runner is not connected yet. Download the starter and work locally.'),polyglot_rate_limited:t('15 dakikada en fazla 12 kod gönderimi. Biraz sonra yeniden dene.','Up to 12 code submissions per 15 minutes. Retry later.')})[e.message]||t('İşlem tamamlanamadı; taslağın korunuyor.','The operation failed; your draft is preserved.');
 async function load(){data=await api('advanced');try{const result=await api('piston/runtimes');data.runtimes=result.runtimes;}catch{data.runtimes=[];}}
 function remember(){const code=document.getElementById('advancedCode');if(code&&taskId)drafts[taskId]=code.value;}
 function taskView(task){
  if(!task)return '';const project=data.projects.find(p=>p.id===task.project),index=project.stages.indexOf(task.id),locked=project.stageResults.slice(0,index).some(s=>!s.passed),row=data.records.filter(r=>r.task_id===task.id).at(-1);let report;try{report=JSON.parse(row?.result||'null')?.report;}catch{}
  const code=drafts[task.id]??row?.code??task.starter,runner=data.runtimes.some(r=>r.language===task.language);
  return `<section class="rd-card" id="advancedActive"><h2>${safe(l(task.title))}</h2><p class="rd-note-text">${safe(l(task.prompt))}</p><p>${safe(l(project.setup))}</p><a href="${safe(task.source.url)}" target="_blank" rel="noopener noreferrer">${safe(task.source.label)} ↗</a><label class="rd-label" for="advancedCode">${task.language==='python'?'Python · JSON stdin/stdout':'C# · Console stdin/stdout'}</label><textarea class="rd-code" id="advancedCode" rows="16" maxlength="12000" spellcheck="false">${safe(code)}</textarea><div class="rd-actions">${button(t('Başlangıcı indir','Download starter'),'download',task.id)}${button(busy?t('Test ediliyor…','Testing…'):t('Bağımsız testleri çalıştır','Run independent tests'),'run',task.id,busy||locked||!runner)}</div>${locked?`<p class="rd-notice">${t('Aşama kilitli: önce önceki aşamanın tüm testlerini geçir.','Stage locked: pass all previous stage tests first.')}</p>`:''}${!runner?`<p class="rd-notice">${t('Bu dilin canlı sandbox servisi bağlı değil. Yerelde çalışabilirsin; doğrulanmış puan sunucu testleri tamamlanınca eklenir.','The hosted sandbox for this language is not connected. Work locally; verified points are added only after server tests finish.')}</p>`:''}${report?`<h3>${report.passed}/${report.total} ${t('test geçti','tests passed')}</h3><p>${t('Sonuç bu sözleşmeye aittir; gerçek dağıtım veya motor performansını kanıtlamaz.','This result establishes the tested contract, not real deployment or engine performance.')}</p>${report.cases.map(c=>`<details><summary>${c.pass?'✓':'×'} ${t('Test örneği','Test case')}</summary><strong>${t('Girdi','Input')}</strong><pre>${safe(typeof c.input==='string'?c.input:JSON.stringify(c.input,null,2))}</pre><strong>${t('Beklenen','Expected')}</strong><pre>${safe(typeof c.expected==='string'?c.expected:JSON.stringify(c.expected,null,2))}</pre><strong>${t('Senin sonucun','Your result')}</strong><pre>${safe(c.error||c.actual)}</pre></details>`).join('')}`:''}</section>`;
 }
 function interviewView(){
  const track=data.tracks.find(s=>s.id===trackId);if(!track)return '';const session=data.sessions.find(s=>s.track===track.id),step=track.steps.find(s=>s.id===stepId)||track.steps[0];
  if(!session)return `<section class="rd-card"><h2>${safe(l(track.title))}</h2><p>${t('Altı aşama: ihtiyacı netleştir, tasarla, hata ayıkla, kod yaz, aktar, değerlendir. Yanıtlar hesabında tutulur. Süre öneridir; ara verip devam edebilirsin.','Six phases: requirements, design, debugging, implementation, transfer and reflection. Answers are saved to your account. Time is a guideline; pause and resume.')}</p>${button(t('Provayı başlat','Start rehearsal'),'begin',track.id)}</section>`;
  const answer=session.answers[step.id]||'',answered=track.steps.filter(s=>session.answers[s.id]?.trim()).length;
  return `<section class="rd-card"><h2>${safe(l(track.title))}</h2><p>${answered}/${track.steps.length} ${t('yanıt kaydedildi','answers saved')} · ${t('Başlangıç:','Started:')} ${new Date(session.started_at).toLocaleString()}</p><div class="rd-actions">${track.steps.map(s=>button(`${s.id===step.id?'● ':''}${safe(l(s.title))}`,'step',s.id)).join('')}</div><h3>${safe(l(step.title))} · ${step.minutes} ${t('dk öneri','min suggested')}</h3><p class="rd-note-text">${safe(l(step.prompt))}</p><label class="rd-label" for="interviewAnswer">${t('Yanıt, kod ve gerekçen','Your answer, code and reasoning')}</label><textarea id="interviewAnswer" rows="12" maxlength="6000" data-track="${track.id}" data-step="${step.id}">${safe(answer)}</textarea>${window.realdevSpeechTools?.('interviewAnswer')||''}<p id="interviewStatus" role="status">${t('Yazdıkların otomatik kaydedilir.','Your answer is saved automatically.')}</p>${button(t('Kaydet ve sonraki aşama','Save and next phase'),'next',step.id)}<details><summary>${t('Yanıtından sonra ölçütlerle karşılaştır','Compare with the rubric after answering')}</summary><ul>${step.checks.map(c=>`<li>${safe(l(c))}</li>`).join('')}</ul><p>${t('Bu ölçütler öz değerlendirme içindir. Kaydedilen açıklama otomatik doğrulanmış beceri puanı değildir.','This rubric supports self-review. Saved explanations are not automatically verified skill points.')}</p></details>${answered===track.steps.length?`<p class="rd-notice">${t('Prova yanıtları tamamlandı. Zayıf kalan yanıtları son aşamada eksik listesine dönüştür ve tekrar çalış.','All rehearsal answers are saved. Turn weak answers into a gap list in the final phase, then practice again.')}</p>`:''}</section>`;
 }
 function view(){
  if(!data){if(!loading&&!notice)queueMicrotask(async()=>{loading=true;try{await load();notice='';}catch(e){notice=errorText(e);}finally{loading=false;render();}});return `<div class="rd"><h1>${t('İleri eğitim ve mülakat','Advanced practice and interviews')}</h1><p role="status">${notice||t('Yükleniyor…','Loading…')}</p>${notice?button(t('Yeniden dene','Retry'),'retry'):''}</div>`;}
  return `<div class="rd"><h1>${t('İleri eğitim ve mülakat','Advanced practice and interviews')}</h1><p>${t('Aşamalı projelerle kod yaz, hata ayıkla ve başka probleme aktar. Kod testleri ve mülakat açıklamaları ayrı kanıt türleridir.','Write code, debug and transfer learning through staged projects. Code tests and interview explanations are different evidence types.')}</p>${notice?`<p role="status" class="rd-notice">${safe(notice)}</p>`:''}<div class="rd-grid">${data.projects.map(p=>`<section class="rd-card"><h2>${safe(l(p.title))}</h2><p>${safe(l(p.brief))}</p><span class="rd-tag">${p.completedStages}/${p.stages.length} · ~${p.minutes} ${t('dk','min')}</span><ol>${p.stageResults.map(s=>`<li>${s.passed?'✓':'○'} ${button(safe(l(data.tasks.find(t=>t.id===s.id).title)),'task',s.id)}</li>`).join('')}</ol></section>`).join('')}</div>${taskView(data.tasks.find(s=>s.id===taskId))}<section class="rd-card"><h2>${t('Uzun mülakat provaları','Long interview rehearsals')}</h2><p>${t('Her prova altı bölüm ve 75 dakika önerilen çalışma içerir; metin, kod ve sesle yanıtlayabilirsin.','Each rehearsal has six phases and 75 minutes of suggested practice; answer with text, code or audio.')}</p><div class="rd-actions">${data.tracks.map(s=>button(safe(l(s.title)),'track',s.id)).join('')}</div></section>${interviewView()}</div>`;
 }
 renderers.advanced=view;
 const originalPractice=renderers.interview;renderers.interview=()=>`<div class="rd"><section class="rd-card"><h2>${t('İleri projeler ve uzun mülakat','Advanced projects and long interviews')}</h2><p>${t('API/SQLite, .NET ve Unity için dokuz aşama; üç kayıtlı mülakat rotası.','Nine API/SQLite, .NET and Unity stages; three saved interview tracks.')}</p>${button(t('İleri eğitimi aç →','Open advanced practice →'),'open')}</section></div>`+originalPractice();
 const originalRoute=renderers.route;renderers.route=()=>originalRoute()+`<div class="rd"><section class="rd-card"><h2>${t('Daha kapsamlı uygulama','Deeper practical work')}</h2>${button(t('API, .NET, Unity ve mülakat rotaları →','API, .NET, Unity and interview tracks →'),'open')}</section></div>`;
 async function saveAnswer(element){if(!element)return;const {track,step}=element.dataset,answer=element.value;const session=data.sessions.find(s=>s.track===track);session.answers[step]=answer;const operation=saving.catch(()=>{}).then(()=>api('interviews',{track,step,answer},'PUT'));saving=operation;try{await operation;const status=document.getElementById('interviewStatus');if(status&&element.isConnected&&element.value===answer)status.textContent=t('Yanıt hesabına kaydedildi.','Answer saved to your account.');}catch(e){const status=document.getElementById('interviewStatus');if(status)status.textContent=errorText(e);throw e;}}
 document.addEventListener('input',e=>{if(e.target.id==='advancedCode')remember();if(e.target.id==='interviewAnswer'){clearTimeout(timer);const element=e.target;data.sessions.find(s=>s.track===element.dataset.track).answers[element.dataset.step]=element.value;timer=setTimeout(()=>saveAnswer(element).catch(()=>{}),900);}});
 document.addEventListener('click',async e=>{
  const el=e.target.closest('[data-advanced]');if(!el)return;e.preventDefault();remember();const action=el.dataset.advanced,id=el.dataset.id;
  if(action==='retry'){notice='';render();return;}if(action==='open'){go('advanced');return;}if(action==='task'){taskId=id;render();document.getElementById('advancedActive')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
  if(action==='track'){trackId=id;stepId='';render();return;}if(action==='step'){clearTimeout(timer);try{await saveAnswer(document.getElementById('interviewAnswer'));stepId=id;render();}catch{}return;}
  if(action==='download'){const task=data.tasks.find(s=>s.id===id),blob=new Blob([task.starter],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=task.language==='python'?'main.py':'Program.cs';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
  if(busy)return;busy=true;notice='';
  try{
   if(action==='begin'){await api('interviews',{track:id});await load();}
   if(action==='next'){clearTimeout(timer);await saveAnswer(document.getElementById('interviewAnswer'));const track=data.tracks.find(s=>s.id===trackId),index=track.steps.findIndex(s=>s.id===id);stepId=track.steps[Math.min(index+1,track.steps.length-1)].id;}
   if(action==='run'){render();await api('advanced-runs',{id:crypto.randomUUID(),taskId:id,code:drafts[id]});await load();await window.realdevReload?.();}
  }catch(e){notice=errorText(e);}finally{busy=false;render();}
 },true);
 render();
})();
