(() => {
 'use strict';
 let data=null,run=null,result=null,busy=false,loadError=null,notice='',drafts={},recognition=null,topicQuery='',noteFilter='open',reviewAttemptId=null;
 const t=(tr,en)=>window.realdevLocale==='en'?en:tr;
 const local=x=>typeof x==='object'&&x?x[window.realdevLocale==='en'?'en':'tr']:x;
 const safe=x=>esc(x??'');
 const date=x=>new Date(x).toLocaleDateString(window.realdevLocale==='en'?'en-GB':'tr-TR',{day:'numeric',month:'short',year:'numeric'});
 const btn=(label,action,extra='',secondary=false)=>`<button type="button" class="${secondary?'secondary':'primary'}-button" data-rd="${action}" ${extra} ${busy?'disabled':''}>${label}</button>`;
 const nav=(label,view)=>`<button class="secondary-button" data-view="${view}">${label}</button>`;
 const title=(eyebrow,heading,desc)=>`<div class="eyebrow">${eyebrow}</div><h1>${heading}</h1><p class="muted">${desc}</p>`;
 const task=id=>data?.tasks.find(q=>q.id===id);
 const outcome=a=>a.skipped?t('Bilmiyorum','Not yet'):a.score===100?t('Doğru','Correct'):t('Tekrar çalış','Needs practice');
 const status=e=>({unmeasured:t('Henüz ölçülmedi','Not assessed'),initial:t('İlk olumlu kanıt','Initial positive evidence'),supported:t('İki örnekte doğrulandı','Supported in two examples'),practice:t('Pratik gerekiyor','Practice needed')}[e.status]);
 const reason=r=>({unmeasured:t('Henüz ölçülmedi; başlangıç kanıtı topla.','Not assessed yet; collect initial evidence.'),gap:t('Son yanıtlarda eksik veya ipucu ihtiyacı var.','Recent answers show a gap or need for a hint.'),transfer:t('Bilgini farklı bir örnekte kontrol et.','Check your understanding in a different example.'),review:t('Aralıklı tekrar zamanı geldi.','A spaced review is due.'),scheduled:t('Sonraki tekrar planlandı.','The next review is scheduled.')}[r]);
 function shell(content){return `<div class="rd" translate="no">${notice?`<div role="alert" class="rd-notice rd-error">${safe(notice)}</div>`:''}${content}</div>`;}
 function gate(){if(loadError)return `<section class="rd-card"><h2>${t('Hesabın yüklenemedi','Could not load your account')}</h2><p>${loadError===401?t('İlerlemeni kaydetmek için giriş yap.','Sign in to save your progress.'):t('Sunucuya ulaşılamadı. Kayıtların silinmedi; yeniden deneyebilirsin.','The server could not be reached. Your saved records have not been deleted; please retry.')}</p>${loadError===401?`<a href="/signin-with-chatgpt?return_to=%2F" target="_top">${t('ChatGPT ile giriş yap','Sign in with ChatGPT')}</a>`:btn(t('Yeniden dene','Retry'),'reload')}</section>`;if(!data)return `<section class="rd-card" role="status">${t('Hesabın ve çalışma geçmişin yükleniyor…','Loading your account and learning history…')}</section>`;return '';}
 function guarded(view){return ()=>shell(gate()||view());}
 async function request(path,body,method='POST'){
  const r=await fetch('/api/'+path,{method:body===undefined?'GET':method,credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});
  const response=await r.json();if(!r.ok){const error=new Error(response.error||'request_failed');error.status=r.status;error.feedback=response.feedback;throw error;}return response;
 }
 async function refresh(){data=await request('state');loadError=null;document.getElementById('goalSubtitle').textContent=data.profile.goals.map(g=>local(data.goals[g])).join(' · ');document.querySelectorAll('.avatar').forEach(el=>el.textContent=(data.user.email[0]||'U').toUpperCase());}
 async function load(){try{await refresh();if(!run)run=data.activeRun;}catch(e){loadError=e.status||503;}draw();}
 function syncLabels(){document.getElementById('libraryNav').textContent=t('Kütüphanem','My library');document.getElementById('topicsNav').textContent=t('Konu ara','Explore topics');document.getElementById('notesNav').textContent=t('Notlarım','My notes');document.getElementById('routeNav').textContent=t('Çalışma rotam','My learning route');document.getElementById('historyNav').textContent=t('Cevap geçmişim','Answer history');document.querySelector('.today-date').textContent=date(new Date());}
 function draw(){syncLabels();render();const names={quiz:t('Beceri taraması','Skill assessment'),route:t('Çalışma rotam','My learning route'),history:t('Cevap geçmişim','Answer history'),account:t('Kalıcı hesabım','My account'),topics:t('Konu ara','Explore topics'),notes:t('Notlarım','My notes'),library:t('Kütüphanem','My library'),review:t('Soruyu tekrar incele','Review the question')};if(names[state.view])document.getElementById('crumbCurrent').textContent=names[state.view];}
 function move(view){stopSpeech();state.view=view;document.getElementById('sidebar').classList.remove('open');draw();window.scrollTo(0,0);}
 function current(){return run&&task(run.taskIds.find(id=>!run.attempts.some(a=>a.task_id===id)));}
 function draft(){const q=current();if(!q)return {};const key=run.id+':'+q.id;return drafts[key]||(drafts[key]={answer:q.kind==='expression'?'':null,explanation:'',confidence:1,note:{id:crypto.randomUUID(),text:''}});}
 function remember(){const noteEl=document.getElementById('rd-note');if(noteEl){const nd=noteDraft();nd.text=noteEl.value;}if(!current())return;const d=draft();const form=document.getElementById('rd-form');if(!form)return;const q=current();if(q.kind==='expression')d.answer=form.querySelector('#rd-code')?.value||'';else{const radio=form.querySelector('input[name=answer]:checked');d.answer=radio?Number(radio.value):null;}d.explanation=form.querySelector('#rd-explanation')?.value||'';d.confidence=Number(form.querySelector('#rd-confidence')?.value||1);}
 function dashboard(){const covered=data.evidence.filter(e=>e.distinct).length;const planned=data.route.filter(r=>r.today);return `<div class="rd-welcome"><div><h1>${t('Merhaba, geliştirici','Hello, developer')}</h1><p class="muted">${t('Bugün küçük bir adım atalım. Önce düşün, sonra dene, en son açıkla.','Take a small step today. Think first, try next, then explain.')}</p></div><div class="rd-completed">${data.attempts.length} ${t('görev yanıtlandı','tasks answered')}</div></div>`+`<section class="rd-card"><div class="rd-row"><div><span class="eyebrow">${t('BECERİ TARAMASI','SKILL ASSESSMENT')}</span><h2>${data.activeRun?t('Kaldığın yerden devam et','Continue where you left off'):t('Sekiz alanda ilk kanıtını oluştur','Build your first evidence across eight areas')}</h2><p class="muted">${t('8 görev · yaklaşık 15–20 dakika · kod, teşhis ve açıklama','8 tasks · about 15–20 minutes · code, diagnosis and explanation')}</p></div>${btn(data.activeRun?t('Taramaya devam et →','Resume assessment →'):t('Taramayı başlat →','Start assessment →'),'start')}</div><div class="rd-metrics"><div><strong class="rd-number">${covered}/${Object.keys(data.areas).length}</strong>${t('Alan gözlemlendi','Areas observed')}</div><div><strong class="rd-number">${new Set(data.attempts.map(a=>a.task_id)).size}</strong>${t('Farklı görev','Distinct tasks')}</div><div><strong class="rd-number">${data.profile.dailyMinutes}</strong>${t('Dakika / gün','Minutes / day')}</div></div><p class="muted">${t('Bu sayılar uzmanlık puanı değildir. Harita yalnızca tamamladığın görevlerden kanıt içerir.','These are not expertise ratings. The map only uses evidence from tasks you completed.')}</p></section><div class="rd-grid"><section class="rd-card"><h2>${t('Bugünkü kişisel rotan','Your personal route today')}</h2>${planned.length?`<ul class="rd-list">${planned.map(routeItem).join('')}</ul>`:`<p>${t('Bugünkü tekrarların tamamlandı. Sonraki tarihleri rotanda görebilirsin.','Today’s reviews are complete. See your route for the next dates.')}</p>`}<div class="rd-actions">${nav(t('Tüm rotayı gör','See full route'),'route')}</div></section><aside class="rd-card"><h2>${t('Nasıl değerlendiriyoruz?','How we assess')}</h2><p>${t('Seçenekli görevlerde cevap anahtarı, kod koşullarında test sonuçları kullanılır. İpucu ve “bilmiyorum” yanıtı ayrıca kaydedilir.','Choice tasks use an answer key; code conditions use test results. Hints and “not yet” answers are recorded separately.')}</p><p>${t('Açıklamanı ölçütlerle kendin karşılaştırırsın. Serbest metne veya ses tonuna otomatik doğruluk puanı verilmez.','Compare your explanation against explicit criteria. Free text and tone of voice are not automatically graded for correctness.')}</p>${nav(t('Hesabım ve hedeflerim','My account and goals'),'account')}</aside></div>`;}
 function routeItem(r){return `<li><span class="rd-tag">${safe(local(data.areas[r.area]))} · ${r.minutes} ${t('dk','min')}</span><h3>${safe(local(r.title))}</h3><p class="muted">${reason(r.reason)}</p><p class="muted">${t('Tekrar hedefi:','Review target:')} ${date(r.dueAt)}</p>${btn(t('Görevi aç →','Open task →'),'practice',`data-task="${r.taskId}"`,true)}</li>`;}
 function routeView(){return title(t('SANA GÖRE','PERSONALIZED'),t('Çalışma rotam','My learning route'),t('Hedeflerin, günlük süren ve cevap kanıtların birlikte sıralamayı belirler.','Your goals, daily time and answer evidence determine the order.'))+`<div class="rd-notice">${data.profile.goals.map(g=>safe(local(data.goals[g]))).join(' · ')} · ${data.profile.dailyMinutes} ${t('dakika/gün. Eksikler önce gelir; olumlu kanıtları yeni örnek ve aralıklı tekrarla kontrol ederiz.','minutes/day. Gaps come first; positive evidence gets a new example and spaced review.')}</div><div class="rd-grid"><section class="rd-card"><h2>${t('Bugün','Today')}</h2><ul class="rd-list">${data.route.filter(r=>r.today).map(routeItem).join('')||`<li>${t('Bugün için planlanan çalışma yok.','No work scheduled for today.')}</li>`}</ul></section><section class="rd-card"><h2>${t('Sıradaki çalışmalar','Coming next')}</h2><ul class="rd-list">${data.route.filter(r=>!r.today).map(routeItem).join('')}</ul></section></div><div class="rd-notice">${t('Tekrar aralığı: pratik gereken alanlarda 1 gün, ilk olumlu kanıtta 3 gün, iki farklı bağımsız doğru örnekte 7 gün. Bu ilk sürümde AI, veri ve mobil hedefleri ortak temel görevlere yönlenir; uzmanlık modülleri henüz ölçülmez.','Review intervals: 1 day for areas needing practice, 3 days after initial positive evidence, 7 days after two distinct independent correct examples. In this version, AI, data and mobile goals use shared foundation tasks; specialist modules are not assessed yet.')}</div>`;}
 function map(){return title(t('KANITA DAYALI','EVIDENCE BASED'),t('Beceri haritam','My skill map'),t('Her durumun altında gözlemlenen görev sayısı var. Tek doğru yanıtla “uzman” etiketi vermiyoruz.','Each status shows the number of tasks observed. One correct answer does not earn an “expert” label.'))+`<section class="rd-card"><ul class="rd-list">${data.evidence.map(e=>`<li><div class="rd-row"><div><h3>${safe(local(data.areas[e.area]))}</h3><span class="rd-tag">${status(e)}</span></div><strong>${e.distinct} ${t('farklı görev','distinct tasks')}</strong></div><p class="muted">${e.independent} ${t('farklı görevde ipucusuz tam doğru yanıt','distinct tasks answered fully correctly without hints')}${e.lastAt?' · '+date(e.lastAt):''}</p>${btn(t('Yeni örnek çöz','Try another example'),'practice',`data-task="${data.route.find(r=>r.area===e.area).taskId}"`,true)}</li>`).join('')}</ul></section><p class="muted">${t('Aynı görevi tekrar çözmek yeni beceri kanıtı sayılmaz; her görev için son deneme kullanılır. Bu dar örnekler genel mesleki yetkinliği veya mülakat başarısını kanıtlamaz.','Repeating a task does not add distinct evidence; the latest attempt per task is used. These narrow examples do not establish overall professional competence or interview readiness.')}</p>${nav(t('Yanıt kanıtlarını incele','Inspect answer evidence'),'history')}`;}
 function assessment(){
  if(result)return feedbackView(result,true);
  if(!run)return title(t('İLK ADIM','FIRST STEP'),t('Kısa beceri taraması','Short skill assessment'),t('Önce kendi başına dene. Eminlik düzeyini seç ve düşünceni açıklamayı dene.','Try independently first. Choose your confidence and explain your reasoning.'))+`<section class="rd-card"><p>${t('Sekiz görev var. Her yanıt sunucuda kaydedilir; ara verirsen devam edebilirsin. İpucu alman sonuçlarda görünür.','There are eight tasks. Each answer is saved on the server, so you can pause and continue. Hints are visible in your results.')}</p>${btn(t('Başla →','Start →'),'start')}</section>`;
  if(run.complete)return summary();
  const q=current(),d=draft(),hint=run.hints.find(h=>h.taskId===q.id);
  return `<section class="rd-card"><div class="rd-row"><span class="eyebrow">${safe(local(data.areas[q.area]))}</span><span>${run.attempts.length+1} / ${run.taskIds.length}</span></div><div class="rd-progress" role="progressbar" aria-valuenow="${run.attempts.length}" aria-valuemin="0" aria-valuemax="${run.taskIds.length}" aria-label="${t('Tamamlanan görevler','Completed tasks')}"><span style="width:${run.attempts.length/run.taskIds.length*100}%"></span></div><h1>${safe(local(q.title))}</h1><p>${safe(local(q.prompt))}</p>${q.code?`<pre>${safe(q.code)}</pre>`:''}<form id="rd-form">${q.kind==='expression'?`<label class="rd-label" for="rd-code">${t('Kod koşulun','Your code condition')}</label><textarea id="rd-code" class="rd-code" maxlength="400" spellcheck="false" placeholder="n ...">${safe(d.answer)}</textarea><p class="muted">${t('Desteklenenler: n, sayılar, parantezler, aritmetik, karşılaştırma ve && / || / !. Koşul güvenli bir yorumlayıcıda sınanır.','Supported: n, numbers, parentheses, arithmetic, comparisons and && / || / !. The condition is tested in a restricted interpreter.')}</p>`:`<fieldset style="border:0;padding:0"><legend class="rd-sr">${t('Cevabını seç','Choose your answer')}</legend>${q.options.map((o,i)=>`<label class="rd-answer"><input type="radio" name="answer" value="${i}" ${d.answer===i?'checked':''}>${safe(local(o))}</label>`).join('')}</fieldset>`}<label class="rd-label" for="rd-confidence">${t('Cevabından ne kadar eminsin?','How confident are you?')}</label><select id="rd-confidence">${[t('Tahmin ediyorum','Guessing'),t('Kısmen eminim','Somewhat confident'),t('Eminim','Confident')].map((v,i)=>`<option value="${i}" ${d.confidence===i?'selected':''}>${v}</option>`).join('')}</select><label class="rd-label" for="rd-explanation">${t('Neden? Kendi cümlenle açıkla (isteğe bağlı)','Why? Explain in your own words (optional)')}</label><textarea id="rd-explanation" maxlength="6000" placeholder="${t('Sonuca hangi adımlarla ulaştın?','What steps led you to this conclusion?')}">${safe(d.explanation)}</textarea><p class="muted">${t('Açıklama kayıt edilir; teknik doğruluğu otomatik puanlanmaz. Sesli yazma tarayıcının ses tanıma hizmetini kullanabilir.','Your explanation is saved, but not automatically graded for technical accuracy. Voice input may use your browser’s speech recognition service.')}</p><div class="rd-actions">${btn(t('Sesle yaz','Dictate'),'voice','',true)}${btn(t('Yanıtı değerlendir →','Evaluate answer →'),'submit')}${btn(t('Bilmiyorum','Not yet'),'skip','',true)}${btn(t('İpucu al','Get a hint'),'hint','',true)}</div></form>${noteBox(q)}${hint?`<div class="rd-notice"><strong>${t('İpucu kullanıldı','Hint used')}</strong><p>${safe(local(hint.hint))}</p></div>`:''}<div class="rd-actions">${nav(t('Ara ver / bugüne dön','Pause / back to today'),'today')}</div></section>`;
 }
 function answerText(a){const q=task(a.task_id);return a.skipped?t('Bilmiyorum','Not yet'):q.kind==='expression'?String(a.answer):local(q.options[a.answer]);}
 function feedbackView(a,continuation=false){const q=task(a.task_id),f=a.feedback;return `<section class="rd-card"><span class="eyebrow">${t('YANIT KANITI','ANSWER EVIDENCE')}</span><h2>${safe(local(q.title))} · ${outcome(a)}</h2><div><span class="rd-tag">${a.hinted?t('İpucuyla','With hint'):t('İpucusuz','Without hint')}</span><span class="rd-tag">${t('Hesaba kaydedildi','Saved to account')}</span><span class="rd-tag">${date(a.created_at)}</span></div><label class="rd-label">${t('Senin yanıtın','Your answer')}</label><pre>${safe(answerText(a))}</pre>${a.confidence===2&&a.score<100?`<div class="rd-notice">${t('Emin olduğunu belirtmiştin. Bu fark, özellikle tekrar edilmesi gereken bir noktayı gösteriyor.','You reported high confidence. This mismatch highlights something worth revisiting.')}</div>`:''}${f.expected?`<p><strong>${t('Beklenen yanıt:','Expected answer:')}</strong> ${safe(local(f.expected))}</p>`:''}<p>${safe(local(f.explain))}</p>${f.cases?`<h3>${f.cases.filter(c=>c.pass).length}/${f.cases.length} ${t('test geçti','tests passed')}</h3><div class="rd-table"><table><thead><tr><th>n</th><th>${t('Beklenen','Expected')}</th><th>${t('Senin sonucun','Your result')}</th><th>${t('Test','Test')}</th></tr></thead><tbody>${f.cases.map(c=>`<tr><td>${c.input}</td><td>${c.expected}</td><td>${c.actual}</td><td>${c.pass?'✓':'×'}</td></tr>`).join('')}</tbody></table></div><p class="muted">${t('Geçen testler bu girdiler için kanıttır; tüm olası kodları doğruladığımız anlamına gelmez.','Passing tests is evidence for these inputs, not proof for all possible programs.')}</p>`:''}${a.explanation?`<details><summary>${t('Açıklamamı gözden geçir','Review my explanation')}</summary><p class="rd-explanation">${safe(a.explanation||t('Açıklama eklemedin.','No explanation was added.'))}</p><ul>${f.checks.map(c=>`<li>${safe(local(c))}</li>`).join('')}</ul><p class="muted">${t('Bunlar öz değerlendirme ölçütleridir; anlatımına otomatik doğruluk puanı verilmedi.','These are self-review criteria; your explanation was not automatically graded.')}</p></details>`:""}<a href="${safe(f.source.url)}" target="_blank" rel="noopener noreferrer">${safe(f.source.label)} ↗</a> <span class="muted">· ${t('Kontrol:','Checked:')} ${f.source.checkedAt}</span>${reviewActions(a)}${continuation?noteBox(q):''}${continuation?`<div class="rd-actions">${btn(run.complete?t('Sonuçları gör →','See results →'):t('Sonraki görev →','Next task →'),'next')}</div>`:''}</section>`;}
 function summary(){const independent=run.attempts.filter(a=>a.score===100&&!a.hinted&&!a.skipped).length;return title(t('TUR TAMAMLANDI','SESSION COMPLETE'),t('Kanıtların kaydedildi','Your evidence is saved'),t('Şimdi bu sonuçları küçük, uygulanabilir çalışma adımlarına dönüştürelim.','Turn these results into small, actionable learning steps.'))+`<section class="rd-card"><div class="rd-metrics"><div><strong class="rd-number">${run.attempts.length}</strong>${t('Görev','Tasks')}</div><div><strong class="rd-number">${independent}</strong>${t('İpucusuz tam doğru','Fully correct without hints')}</div><div><strong class="rd-number">${run.attempts.filter(a=>a.hinted).length}</strong>${t('İpucu kullanımı','Tasks with hints')}</div></div><p>${t('Bu tur başlangıç veya tekrar kanıtıdır. Genel seviyen olarak yorumlanmaz.','This session provides initial or review evidence. It is not an overall skill level.')}</p><div class="rd-actions">${nav(t('Kişisel rotama git →','Go to my route →'),'route')}${nav(t('Beceri haritam','My skill map'),'map')}${nav(t('Yanıt geçmişim','Answer history'),'history')}</div></section>`;}
 function history(){return title(t('KAYITLARIN','YOUR RECORDS'),t('Cevap geçmişim','Answer history'),t('Yanıtın, gerekçen, eminlik düzeyin ve kullandığın yardım aynı kayıtta saklanır.','Your answer, reasoning, confidence and hint use are saved together.'))+(data.attempts.length?[...data.attempts].reverse().map(a=>`<details><summary>${safe(local(task(a.task_id).title))} · ${outcome(a)} · ${date(a.created_at)}</summary>${feedbackView(a)}</details>`).join(''):`<section class="rd-card"><p>${t('Henüz kayıtlı yanıt yok. İlk tarama ile başlayabilirsin.','No saved answers yet. Start with your first assessment.')}</p>${btn(t('Taramayı başlat','Start assessment'),'start')}</section>`);}
 function account(){const preferences=profileDraft||data.profile;return title(t('KALICI HESAP','PERSISTENT ACCOUNT'),t('Hedeflerin ve hesabın','Your goals and account'),t('Profilin ve tarama yanıtların giriş yaptığın hesaba bağlı saklanır.','Your profile and assessment answers are stored under your signed-in account.'))+`<section class="rd-card"><h2>${safe(data.user.email||t('Giriş yapılmış hesap','Signed-in account'))}</h2><p>${t('Aynı hesapla başka cihazdan girdiğinde ilerlemen açılır. Bu site şu an özel erişimdedir.','Your progress is available on another device with the same account. This site currently has private access.')}</p><form id="rd-profile"><label class="rd-label">${t('Öğrenme hedeflerin','Learning goals')}</label><div class="rd-goals">${Object.entries(data.goals).map(([id,label])=>`<label><input type="checkbox" name="goals" value="${id}" ${preferences.goals.includes(id)?'checked':''}> ${safe(local(label))}</label>`).join('')}</div><label class="rd-label" for="rd-minutes">${t('Günlük çalışma süresi','Daily study time')}</label><select id="rd-minutes">${[10,15,25].map(n=>`<option value="${n}" ${preferences.dailyMinutes===n?'selected':''}>${n} ${t('dakika','minutes')}</option>`).join('')}</select><div class="rd-actions">${btn(t('Hesabıma kaydet','Save to my account'),'save-profile')}</div></form><div class="rd-notice">${data.profile.saved?t('Hedeflerin hesabında kayıtlı. Değiştirip kaydettiğinde rota yeniden hesaplanır.','Your goals are saved to your account. Saving changes recalculates the route.'):t('İlk başlangıç hedefleri Full stack ve Oyun geliştirme olarak seçildi. Tercihlerini kaydet.','Initial goals are Full stack and Game development. Save your preferences.')}</div><p class="muted">${t('Kaydedilenler: hedefler, günlük süre, görev yanıtları, açıklama metinleri, eminlik, ipucu ve tarihler. Ses kaydı saklanmaz. Eski prototipin cihazdaki puanları doğrulanmış kanıt sayılmadığı için aktarılmaz.','Stored: goals, daily time, task answers, explanation text, confidence, hints and dates. Audio is not stored. Old prototype device scores are not imported as verified evidence.')}</p><a href="/signout-with-chatgpt?return_to=%2F" target="_top">${t('Çıkış yap','Sign out')}</a></section>`;}
 function stopSpeech(){if(recognition){recognition.stop();recognition=null;}}
 function voice(){if(recognition){stopSpeech();return;}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){notice=t('Tarayıcın sesle yazmayı desteklemiyor; yazılı yanıt verebilirsin.','Your browser does not support dictation; type your answer instead.');draw();return;}recognition=new Speech();recognition.lang=window.realdevLocale==='en'?'en-US':'tr-TR';recognition.onresult=e=>{const el=document.getElementById('rd-explanation');if(el){el.value+=(el.value?' ':'')+e.results[0][0].transcript;remember();}};recognition.onerror=()=>{toast(t('Mikrofon iznini kontrol et veya yazılı yanıt kullan.','Check microphone permission or type your answer.'));};recognition.onend=()=>{recognition=null;};recognition.start();toast(t('Dinliyorum…','Listening…'));}
 async function action(name,element){
  if(busy)return;remember();notice='';
  if(name==='voice'){voice();return;}
  if(name==='inspect'){reviewAttemptId=element.dataset.attempt;state.view='review';draw();window.scrollTo(0,0);return;}
  if(name==='topic'){topicQuery=element.dataset.query;state.view='topics';draw();return;}
  if(name==='note-filter'){noteFilter=element.dataset.filter;draw();return;}
  if(name==='next'){result=null;draw();return;}
  busy=true;draw();
  try{
   if(name==='save-question'){await request('library',{attemptId:element.dataset.attempt});await refresh();toast(t('Soru kütüphanene kaydedildi.','Question saved to your library.'));}
   if(name==='save-note'){const q=result?task(result.task_id):current();const note=noteDraft();if(!note.text.trim())throw new Error('empty_note');await request('notes',{id:note.id,text:note.text,taskId:q.id});await refresh();toast(t('Notun hesabına kaydedildi.','Your note was saved to your account.'));}
   if(name==='resolve-note'){await request('notes',{id:element.dataset.id,resolved:element.dataset.resolved==='true'},'PUT');await refresh();}
   if(name==='reload'){await refresh();run=data.activeRun;}
   if(name==='start'||name==='practice'){result=null;run=await request('runs',{id:crypto.randomUUID(),kind:name==='start'?'baseline':'practice',taskId:element.dataset.task});state.view='quiz';}
   if(name==='hint'){const q=current();const h=await request('hint',{runId:run.id,taskId:q.id});run.hints=run.hints.filter(x=>x.taskId!==q.id);run.hints.push({taskId:q.id,hint:h.hint});}
   if(name==='submit'||name==='skip'){
    const q=current(),d=draft();if(name==='submit'&&(d.answer===null||d.answer===''))throw new Error('empty_answer');
    const response=await request('answer',{runId:run.id,taskId:q.id,...d,skipped:name==='skip'});run=response.run;result=response.attempt;
    try{await refresh();}catch{notice=t('Yanıtın kaydedildi; harita yenilenemedi. Yeniden yükleyebilirsin.','Your answer was saved; the map could not refresh. You can reload.');}
   }
   if(name==='save-profile'){
    // Form values were captured before draw to retain unsaved edits.
    const p=profileDraft;if(!p.goals.length)throw new Error('empty_goals');await request('profile',p,'PUT');await refresh();profileDraft=null;toast(t('Hedeflerin hesabına kaydedildi.','Your goals were saved to your account.'));
   }
  }catch(e){notice=e.feedback?local(e.feedback.message):e.message==='empty_note'?t('Önce kısa bir not yaz.','Write a short note first.'):e.message==='empty_answer'?t('Önce bir yanıt gir veya “Bilmiyorum” seç.','Enter an answer or choose “Not yet”.'):e.message==='empty_goals'?t('En az bir hedef seç.','Select at least one goal.'):e.status===401?t('Oturumun sona erdi. Hesabına tekrar giriş yap; yazdığın yanıt bu sayfada korunuyor.','Your session expired. Sign in again; your draft remains on this page.'):t('İşlem tamamlanamadı. Yanıtın bu sayfada korunuyor; tekrar deneyebilirsin.','The operation could not complete. Your draft remains on this page; please retry.');}
  finally{busy=false;draw();}
 }

 function noteDraft(){const q=result?task(result.task_id):current();if(!q)return {id:'',text:''};const key=run.id+':'+q.id;if(!drafts[key])drafts[key]={note:{id:crypto.randomUUID(),text:''}};return drafts[key].note||(drafts[key].note={id:crypto.randomUUID(),text:''});}
 function noteBox(q){const n=noteDraft();return '<details class="rd-note-box"><summary>'+t('Bu soruya not ekle','Add a note to this question')+'</summary><label for="rd-note" class="rd-label">'+t('Kendine not bırak','Leave yourself a note')+'</label><textarea id="rd-note" maxlength="3000" placeholder="'+t('Örneğin: API nedir? Request ile response farkını tekrar çalış.','For example: What is an API? Revisit request vs response.')+'">'+safe(n.text)+'</textarea><p class="muted">'+t('Notun bu sorunun konusuyla Notlarım sayfasında tutulur. Yanıtını gönderirken de kaydedilir.','Your note is kept with this topic in My notes. It is also saved when you submit your answer.')+'</p><div class="rd-actions">'+btn(t('Notu kaydet','Save note'),'save-note','',true)+nav(t('Notlarım','My notes'),'notes')+'</div></details>';}
 const aliases={structures:'veri yapilari data structures stack yigin queue kuyruk dictionary sozluk map',api:'api http cors endpoint request response istek yanit',frontend:'javascript typescript react frontend state render',dotnet:'c# csharp .net clr runtime backend',git:'git github branch merge fetch push',sql:'sql database veritabani ddl schema sema',testing:'test testing kod code kosul sinir boundary',unity:'unity oyun game c# mobile mobil',devops:'devops kubernetes cloud bulut readiness liveness'};
 const normalize=value=>value.toLocaleLowerCase('tr-TR').replaceAll('ı','i').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 function searchResults(){const terms=normalize(topicQuery).trim().split(/\s+/).filter(Boolean);const found=data.tasks.filter(q=>{const text=normalize([q.title.tr,q.title.en,q.prompt.tr,q.prompt.en,aliases[q.area],data.areas[q.area].tr,data.areas[q.area].en].join(' '));return terms.every(term=>text.includes(term));});return '<p role="status" class="muted">'+found.length+' '+t('soru bulundu','questions found')+'</p><ul class="rd-list">'+found.map(q=>'<li><span class="rd-tag">'+safe(local(data.areas[q.area]))+'</span><h3>'+safe(local(q.title))+'</h3><p>'+safe(local(q.prompt))+'</p>'+btn(t('Soruyu çöz →','Solve question →'),'practice','data-task="'+q.id+'"',true)+'</li>').join('')+'</ul>'+(!found.length?'<div class="rd-notice">'+t('Bu konuda henüz soru yok. API, Git, React veya veri yapıları arayabilirsin.','No questions for this topic yet. Try API, Git, React or data structures.')+'</div>':'');}
 function topicsView(){return title(t('SORU KÜTÜPHANESİ','QUESTION LIBRARY'),t('Konu ara, çalışmaya başla','Find a topic and practice'),t('Türkçe veya İngilizce ara. Bulduğun soruların sonuçları beceri haritana eklenir.','Search in Turkish or English. Results from these questions contribute to your skill map.'))+'<section class="rd-card"><label for="rd-search" class="rd-label">'+t('Hangi konuyu çalışmak istiyorsun?','What would you like to practice?')+'</label><input type="search" class="rd-search" id="rd-search" value="'+safe(topicQuery)+'" placeholder="'+t('Veri yapıları, API, React, C#…','Data structures, API, React, C#…')+'"><div class="rd-topic-chips">'+['API',t('Veri yapıları','Data structures'),'React','C#','Git'].map(v=>btn(v,'topic','data-query="'+v+'"',true)).join('')+'</div><div id="rd-search-results">'+searchResults()+'</div></section>';}
 function notesView(){const open=data.notes.filter(n=>!n.resolved);const list=data.notes.filter(n=>noteFilter==='all'||(noteFilter==='done'?n.resolved:!n.resolved));return title(t('KENDİ EKSİK LİSTEN','YOUR PERSONAL GAP LIST'),t('Notlarım','My notes'),t('Sorularda aklına takılanları burada topla. Konuyu çalışınca çözüldü olarak işaretle.','Collect questions that came to mind while practicing. Mark them resolved after studying.'))+'<div class="rd-notice">'+open.length+' '+t('açık not. Bu liste senin belirttiğin eksiklerdir; otomatik beceri puanı değildir.','open notes. These are self-identified gaps, not automatic skill scores.')+'</div><div class="rd-actions">'+[['open',t('Açık eksikler','Open gaps')],['done',t('Çözülenler','Resolved')],['all',t('Tümü','All')]].map(([id,label])=>btn(label,'note-filter','data-filter="'+id+'"',noteFilter!==id)).join('')+'</div>'+list.map(n=>{const q=task(n.task_id);return '<article class="rd-card '+(n.resolved?'rd-note-resolved':'')+'"><div class="rd-row"><span class="rd-tag">'+safe(local(data.areas[q.area]))+'</span><span class="muted">'+date(n.created_at)+'</span></div><h3>'+safe(local(q.title))+'</h3><p class="rd-note-text">'+safe(n.body)+'</p><div class="rd-actions">'+btn(n.resolved?t('Yeniden aç','Reopen'):t('Çözüldü olarak işaretle','Mark resolved'),'resolve-note','data-id="'+n.id+'" data-resolved="'+(!n.resolved)+'"',true)+btn(t('Bu konunun soruları','Questions on this topic'),'topic','data-query="'+safe(local(data.areas[q.area]))+'"',true)+'</div></article>';}).join('')+(!list.length?'<section class="rd-card"><p>'+t('Bu listede henüz not yok. Soru altındaki not kutusuyla başlayabilirsin.','No notes in this list yet. Start with the note box under a question.')+'</p>'+nav(t('Konu ara','Explore topics'),'topics')+'</section>':'');}


 function reviewActions(a){const saved=data.library.some(item=>item.task_id===a.task_id);return '<div class="rd-actions">'+(state.view!=='review'?btn(t('Soruyu tekrar incele','Review the question'),'inspect','data-attempt="'+a.id+'"',true):'')+(saved?nav(t('Kütüphanemde ✓','In my library ✓'),'library'):btn(t('Kütüphaneme ekle','Add to my library'),'save-question','data-attempt="'+a.id+'"',true))+btn(t('Tekrar çöz','Try again'),'practice','data-task="'+a.task_id+'"',true)+'</div>';}
 function reviewView(){const a=data.attempts.find(a=>a.id===reviewAttemptId)||(result?.id===reviewAttemptId?result:null);if(!a)return '<section class="rd-card">'+t('Bu yanıt bulunamadı. Cevap geçmişinden tekrar seçebilirsin.','This answer was not found. Select it again from your history.')+'</section>';const q=task(a.task_id);return title(t('GERİ DÖN VE ANLA','REVISIT AND UNDERSTAND'),t('Soruyu tekrar incele','Review the question'),t('Soruyu, verdiğin yanıtı ve beklenen sonucu yan yana düşün.','Compare the question, your answer and the expected result.'))+'<section class="rd-card"><span class="rd-tag">'+safe(local(data.areas[q.area]))+'</span><h2>'+safe(local(q.title))+'</h2><p>'+safe(local(q.prompt))+'</p>'+(q.code?'<pre>'+safe(q.code)+'</pre>':'')+(q.options.length?'<ol>'+q.options.map((o,i)=>'<li>'+safe(local(o))+(a.answer===i?' — '+t('Senin seçimin','Your choice'):'')+'</li>').join('')+'</ol>':'')+'</section>'+feedbackView(a)+'<div class="rd-actions">'+nav(t('Kütüphaneme dön','Back to my library'),'library')+nav(t('Cevap geçmişim','Answer history'),'history')+'</div>';}
 function libraryView(){return title(t('SAKLADIĞIN SORULAR','SAVED QUESTIONS'),t('Kütüphanem','My library'),t('Tekrar dönmek istediğin sorular ve önceki yanıtların burada. Tekrar çözmek aynı soruyu yeni bir beceri kanıtı yapmaz.','Questions you want to revisit and your previous answers live here. Retrying a question does not count as new distinct skill evidence.'))+(data.library.length?data.library.map(item=>{const q=task(item.task_id),a=data.attempts.find(a=>a.id===item.attempt_id);return '<article class="rd-card"><div class="rd-row"><span class="rd-tag">'+safe(local(data.areas[q.area]))+'</span><span class="muted">'+date(item.created_at)+'</span></div><h2>'+safe(local(q.title))+'</h2><p>'+safe(local(q.prompt))+'</p><span class="rd-tag">'+outcome(a)+'</span><div class="rd-actions">'+btn(t('Soruyu tekrar incele','Review the question'),'inspect','data-attempt="'+a.id+'"',true)+btn(t('Tekrar çöz','Try again'),'practice','data-task="'+q.id+'"')+'</div></article>';}).join(''):'<section class="rd-card"><p>'+t('Henüz soru eklemedin. Bir yanıtın ardından “Kütüphaneme ekle”yi kullanabilirsin.','No saved questions yet. Use “Add to my library” after answering a question.')+'</p>'+nav(t('Cevap geçmişime git','Go to my answer history'),'history')+'</section>');}

 let profileDraft=null;
 document.addEventListener('click',e=>{
  const el=e.target.closest('[data-rd]');if(el){e.preventDefault();e.stopImmediatePropagation();if(el.dataset.rd==='save-profile')profileDraft={goals:[...document.querySelectorAll('#rd-profile input:checked')].map(i=>i.value),dailyMinutes:Number(document.getElementById('rd-minutes').value)};action(el.dataset.rd,el);return;}
  if(e.target.closest('#profileOpen,#profileOpenTop')){e.preventDefault();e.stopImmediatePropagation();remember();move('account');return;}
  if(e.target.closest('[data-action="start-quiz"]')){e.preventDefault();e.stopImmediatePropagation();action('start',e.target);return;}
  if(e.target.closest('[data-view]')){remember();stopSpeech();notice='';}
  if(e.target.closest('#languageToggle')){remember();setTimeout(draw,0);}
 },true);
 document.addEventListener('submit',e=>{if(e.target.id==='rd-form'||e.target.id==='rd-profile')e.preventDefault();});
 document.addEventListener('input',e=>{if(e.target.closest('#rd-form')||e.target.id==='rd-note')remember();if(e.target.id==='rd-search'){topicQuery=e.target.value;document.getElementById('rd-search-results').innerHTML=searchResults();}if(e.target.closest('#rd-profile'))profileDraft={goals:[...document.querySelectorAll('#rd-profile input:checked')].map(i=>i.value),dailyMinutes:Number(document.getElementById('rd-minutes').value)};});
 window.addEventListener('pagehide',stopSpeech);
 renderers.today=guarded(dashboard);renderers.quiz=guarded(assessment);renderers.map=guarded(map);renderers.route=guarded(routeView);renderers.history=guarded(history);renderers.account=guarded(account);renderers.topics=guarded(topicsView);renderers.notes=guarded(notesView);renderers.library=guarded(libraryView);renderers.review=guarded(reviewView);
 draw();load();
})();
