(function(){
 const rawFetch=window.fetch.bind(window);const localPreview=location.protocol==='http:'&&['127.0.0.1','localhost'].includes(location.hostname)&&location.port==='4317';let client=null;let activeMode='sign-in';let resolveSessionReady;const previewUser=localPreview?{uid:'local-preview-user',email:'preview@local.test',emailVerified:true,localPreview:true}:null;window.realdevLocalPreview=localPreview;window.realdevCurrentUser=previewUser;window.realdevSessionReady=new Promise(resolve=>{resolveSessionReady=resolve;if(localPreview)resolve(previewUser);});
 const status=()=>document.getElementById('authStatus');
 const currentLanguage=()=>window.realdevLocale||localStorage.getItem('realdev-language')||'tr';
 const text=(tr,en)=>currentLanguage()==='en'?en:tr;
 function renderAuthLink(){const link=document.getElementById('authLink');if(!link)return;const signedIn=localPreview||Boolean(client?.currentUser);link.hidden=false;link.textContent=localPreview?text('Yerel deneme','Local preview'):signedIn?text('Çıkış yap','Sign out'):text('Giriş / Kayıt','Sign in / Create account');link.href=localPreview?'/#today':signedIn?'#sign-out':'/auth.html#/sign-in';link.setAttribute('aria-label',link.textContent);link.dataset.signedIn=String(signedIn);}
 function bindAuthLink(){const link=document.getElementById('authLink');if(link&&!link.dataset.logoutBound){link.dataset.logoutBound='true';link.addEventListener('click',async event=>{if(!client?.currentUser)return;event.preventDefault();if(link.dataset.signingOut==='true')return;link.dataset.signingOut='true';link.setAttribute('aria-disabled','true');link.textContent=text('Çıkış yapılıyor…','Signing out…');try{await client.signOut();location.assign('/#today');}catch{delete link.dataset.signingOut;link.removeAttribute('aria-disabled');renderAuthLink();}});}client.onAuthStateChanged(user=>{window.realdevCurrentUser=user?.emailVerified?user:null;renderAuthLink();resolveSessionReady(window.realdevCurrentUser);window.realdevAuthStateChanged?.(window.realdevCurrentUser);window.dispatchEvent(new CustomEvent('realdev-auth-state',{detail:{user:window.realdevCurrentUser}}));});renderAuthLink();}
 const applyLanguage=locale=>{document.documentElement.lang=locale;if(location.pathname.endsWith('/auth.html'))document.title=locale==='en'?'RealDeveloper · Sign in':'RealDeveloper · Hesap girişi';const en=locale==='en';const set=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value;};set('authHeading',en?'Sign in or create an account':'Giriş yap veya kayıt ol');set('authLanguageToggle',en?'TR':'EN');set('authSubmit',activeMode==='sign-in'?(en?'Sign in →':'Giriş yap →'):(en?'Create account →':'Hesap oluştur →'));set('signInTab',en?'Sign in':'Giriş yap');set('signUpTab',en?'Create account':'Kayıt ol');set('resendVerification',en?'Resend verification email':'Doğrulama e-postasını tekrar gönder');renderAuthLink();const heading=document.querySelector('.auth-intro h1');if(heading)heading.textContent=en?'continue with your account':'kendi hesabınla devam et';const intro=document.querySelector('.auth-intro p');if(intro)intro.textContent=en?'Your learning route, answers, notes and code practice are saved to your account.':'Öğrenme rotan, cevapların, notların ve kod çalışmaların hesabına kaydedilir.';const back=document.querySelector('.auth-back');if(back)back.textContent=en?'← Back to workspace':'← Çalışma alanına dön';const eyebrow=document.querySelector('.auth-form .eyebrow');if(eyebrow)eyebrow.textContent=en?'ACCOUNT':'HESAP';const email=document.querySelector('label[for=authEmail]');if(email)email.textContent=en?'Email':'E-posta';const password=document.querySelector('label[for=authPassword]');if(password)password.textContent=en?'Password':'Parola';};
 window.realdevAuthLocale=applyLanguage;
 const configPromise=(localPreview?Promise.resolve({configured:true,localPreview:true}):rawFetch('/api/auth/config',{headers:{Accept:'application/json'}}).then(r=>r.json())).then(async config=>{
  if(!config.configured)return config;
  await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://www.gstatic.com/firebasejs/12.19.0/firebase-app-compat.js';script.onload=()=>{const authScript=document.createElement('script');authScript.src='https://www.gstatic.com/firebasejs/12.19.0/firebase-auth-compat.js';authScript.onload=resolve;authScript.onerror=()=>reject(Error('auth_sdk_unavailable'));document.head.appendChild(authScript);};script.onerror=()=>reject(Error('auth_sdk_unavailable'));document.head.appendChild(script);});
  client=window.firebase.initializeApp({apiKey:config.apiKey,authDomain:config.projectId+'.firebaseapp.com',projectId:config.projectId}).auth();await client.setPersistence(window.firebase.auth.Auth.Persistence.SESSION);bindAuthLink();
  if(location.pathname.endsWith('/auth.html'))setupForm();
  return config;
 }).catch(()=>({configured:false,error:true}));
 window.realdevAuthReady=configPromise;
 configPromise.then(config=>{if(!config.configured){window.realdevCurrentUser=null;resolveSessionReady(null);}});
 window.fetch=async function(input,init={}){
  let url;try{url=new URL(typeof input==='string'?input:input.url,location.href);}catch{return rawFetch(input,init);}
  if(url.origin!==location.origin||!url.pathname.startsWith('/api/')||url.pathname==='/api/auth/config')return rawFetch(input,init);
  await configPromise;if(!client)return rawFetch(input,init);
  const token=client.currentUser?await client.currentUser.getIdToken():null;
  if(token){const headers=new Headers(input instanceof Request?input.headers:undefined);new Headers(init.headers).forEach((value,key)=>headers.set(key,value));headers.set('Authorization','Bearer '+token);init={...init,headers};}
  return rawFetch(input,init);
 };
 function setMode(mode){activeMode=mode;const signIn=mode==='sign-in';document.getElementById('signInTab').setAttribute('aria-selected',String(signIn));document.getElementById('signUpTab').setAttribute('aria-selected',String(!signIn));document.getElementById('resendVerification').hidden=true;applyLanguage(currentLanguage());status().textContent='';document.getElementById('authPassword').autocomplete=signIn?'current-password':'new-password';}
 function authErrorText(error,wasCreated=false){const code=error?.code||'';const messages={
  'auth/invalid-email':['E-posta adresinin biçimini kontrol et.','Check the email address format.'],
  'auth/weak-password':['Parola en az 8 karakter olmalı.','Password must be at least 8 characters.'],
  'auth/email-already-in-use':['Bu e-posta ile bir hesap zaten var. Giriş yapmayı dene.','An account already exists for this email. Try signing in.'],
  'auth/invalid-credential':['E-posta veya parola doğru değil.','Email or password is incorrect.'],
  'auth/user-not-found':['Bu e-posta ile hesap bulunamadı.','No account was found for this email.'],
  'auth/wrong-password':['E-posta veya parola doğru değil.','Email or password is incorrect.'],
  'auth/too-many-requests':['Çok fazla deneme yapıldı. Bir süre bekleyip tekrar dene.','Too many attempts. Wait a while and try again.'],
  'auth/network-request-failed':['Bağlantı kurulamadı. İnternetini kontrol edip tekrar dene.','Could not connect. Check your internet connection and try again.'],
  'auth/operation-not-allowed':['Firebase Authentication ayarlarında e-posta/parola girişini etkinleştir.','Enable email/password sign-in in Firebase Authentication settings.']
 };const pair=messages[code];if(pair)return text(pair[0],pair[1]);if(wasCreated)return text('Hesap oluşturuldu ancak doğrulama e-postası gönderilemedi. Aşağıdaki düğmeyle tekrar deneyebilirsin.','Your account was created, but the verification email could not be sent. Use the button below to retry.');return text('İşlem tamamlanamadı. Firebase Authentication ayarlarını ve bilgileri kontrol edip tekrar dene.','Could not complete the request. Check the Firebase Authentication settings and details, then try again.');}
 function setupForm(){
  const form=document.getElementById('authForm');if(!form)return;
  applyLanguage(localStorage.getItem('realdev-language')||'tr');
  if(location.hash.includes('sign-up'))setMode('sign-up');
  document.getElementById('signInTab').addEventListener('click',()=>setMode('sign-in'));document.getElementById('signUpTab').addEventListener('click',()=>setMode('sign-up'));
  const resend=document.getElementById('resendVerification');
  const showResend=()=>{resend.hidden=false;applyLanguage(currentLanguage());};
  resend.addEventListener('click',async()=>{const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;if(!email||!password){status().textContent=text('Yukarıya e-posta adresini ve parolanı gir. Bunlar Firebase’e gönderilir; bu sitede saklanmaz.','Enter your email and password above. They are sent to Firebase and are not stored by this site.');return;}resend.disabled=true;status().textContent=text('Doğrulama e-postası gönderiliyor…','Sending verification email…');let createdUser=false;try{const result=await client.signInWithEmailAndPassword(email,password);if(result.user.emailVerified){await client.signOut();resend.hidden=true;status().textContent=text('E-posta zaten doğrulanmış. Şimdi giriş yapabilirsin.','Email is already verified. You can sign in now.');return;}await result.user.sendEmailVerification();await client.signOut();status().textContent=text(`Doğrulama bağlantısı ${email} adresine gönderildi. Gelen kutusu ve spam klasörünü kontrol et.`,`A verification link was sent to ${email}. Check your inbox and spam folder.`);}catch(error){if(client.currentUser&&!client.currentUser.emailVerified)await client.signOut().catch(()=>{});status().textContent=authErrorText(error,createdUser);}finally{resend.disabled=false;}});
  form.addEventListener('submit',async e=>{e.preventDefault();const button=document.getElementById('authSubmit');const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;const mode=activeMode;let accountCreated=false;button.disabled=true;resend.hidden=true;status().textContent=text('İşleniyor…','Working…');
   try{const result=mode==='sign-up'?await client.createUserWithEmailAndPassword(email,password):await client.signInWithEmailAndPassword(email,password);if(mode==='sign-up'){accountCreated=true;await result.user.sendEmailVerification();await client.signOut();status().textContent=text(`Hesabın oluşturuldu. Doğrulama bağlantısı ${email} adresine gönderildi. Gelen kutusu ve spam klasörünü kontrol et.`,`Your account was created. A verification link was sent to ${email}. Check your inbox and spam folder.`);return;}if(!result.user.emailVerified){await client.signOut();status().textContent=text('Bu hesap henüz doğrulanmamış. Firebase Console’dan elle eklenen hesaplara otomatik e-posta gitmez; doğrulama bağlantısını almak için aşağıya tıkla.','This account is not verified yet. Accounts added manually in Firebase Console do not get an automatic email; use the button below to request a verification link.');showResend();return;}status().textContent=text('Giriş başarılı. Çalışma alanın açılıyor…','Signed in. Opening your workspace…');location.assign('/#today');}
   catch(error){if(client.currentUser&&!client.currentUser.emailVerified)await client.signOut().catch(()=>{});status().textContent=authErrorText(error,accountCreated);if(accountCreated)showResend();}
   finally{button.disabled=false;}
  });
 }
 document.addEventListener('DOMContentLoaded',async()=>{
  if(localPreview&&location.pathname.endsWith('/auth.html')){location.replace('/#today');return;}
  applyLanguage(localStorage.getItem('realdev-language')||'tr');document.getElementById('authLanguageToggle')?.addEventListener('click',()=>{const next=currentLanguage()==='tr'?'en':'tr';localStorage.setItem('realdev-language',next);applyLanguage(next);});const link=document.getElementById('authLink');if(link)link.hidden=false;
  if(location.pathname.endsWith('/auth.html')){const config=await configPromise;if(!config.configured){document.querySelectorAll('#authForm input,#authForm button,#signInTab,#signUpTab').forEach(el=>el.disabled=true);status().textContent=text('Kayıt ve giriş henüz bağlanmadı. Firebase proje ayarları gerekiyor; parolan bu sitede saklanmaz.','Sign-in is not connected yet. Firebase project settings are required first. This site never stores your password.');}}
 });
})();
