(() => {
 const t=(tr,en)=>window.realdevLocale==='en'?en:tr;
 let data=null;
 const supported=()=>window.isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;
 const dialog=document.createElement('dialog');dialog.className='reminder-dialog';dialog.id='reminderDialog';document.body.append(dialog);
 async function api(path,body,method='POST'){const response=await fetch('/api/reminders'+path,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error);return value;}
 const registration=()=>navigator.serviceWorker.register('/sw.js',{scope:'/'}).then(()=>navigator.serviceWorker.ready);
 const settings=()=>({enabled:dialog.querySelector('#reminderEnabled').checked,time:dialog.querySelector('#reminderTime').value,timezone:dialog.querySelector('#reminderZone').value,language:window.realdevLocale==='en'?'en':'tr'});
 const status=text=>{dialog.querySelector('[role=status]').textContent=text;};
 async function open(){
  dialog.innerHTML=`<h2>${t('Günlük hatırlatıcı','Daily reminder')}</h2><p role="status">${t('Yükleniyor…','Loading…')}</p><button type="button" data-reminder="close">${t('Kapat','Close')}</button>`;dialog.showModal();
  try{data=await api('');const s=data.settings;
   const zones=[...new Set([s.timezone,Intl.DateTimeFormat().resolvedOptions().timeZone,'Europe/Istanbul','Europe/London','Europe/Berlin','America/New_York','America/Los_Angeles','Asia/Tokyo','UTC'])];
   dialog.innerHTML=`<div class="rd"><h2>${t('Günlük hatırlatıcı','Daily reminder')}</h2><p>${t('Saat ve saat dilimi hesabında saklanır. Site kapalıyken bildirim almak için bu cihazda izin ver.','Time and timezone are saved to your account. Allow notifications on this device to receive reminders while the Site is closed.')}</p><label class="rd-answer"><input type="checkbox" id="reminderEnabled" ${s.enabled?'checked':''}>${t('Günlük hatırlatma açık','Enable daily reminders')}</label><label class="rd-label" for="reminderTime">${t('Hatırlatma saati','Reminder time')}</label><input type="time" id="reminderTime" value="${s.time}" required><label class="rd-label" for="reminderZone">${t('Saat dilimi','Timezone')}</label><select id="reminderZone">${zones.map(z=>`<option value="${esc(z)}" ${z===s.timezone?'selected':''}>${esc(z)}</option>`).join('')}</select><p>${t('Bağlı cihaz:','Connected devices:')} ${data.devices}</p><p>${!supported()?t('Bu tarayıcı Web Push desteklemiyor. Chrome, Edge, Firefox veya destekli Safari kullan. iPhone’da önce Safari’den ana ekrana ekle.','This browser does not support Web Push. Use Chrome, Edge, Firefox or supported Safari. On iPhone, add the Site to your home screen first.'):Notification.permission==='denied'?t('Bildirim izni engellenmiş. Tarayıcının site ayarlarından izin verebilirsin.','Notifications are blocked. Allow them in your browser’s Site settings.'):t('İzin yalnızca aşağıdaki cihaz düğmesine basınca istenir.','Permission is requested only when you choose the device button below.')}</p><p class="muted">${data.scheduled?t('Hatırlatmalar saatlik kontrol edilir. Seçtiğin saatten sonraki kontrolde gönderilir; yaklaşık bir saat gecikebilir. İnternet ve cihaz bildirim ayarları teslimatı etkileyebilir.','Reminders are checked hourly and sent at the next check after your chosen time; delivery can be about an hour later. Network and device notification settings can affect delivery.'):t('Arka plan gönderim zamanlayıcısı henüz etkin değil. Ayarını kaydedebilirsin; günlük teslimat başlamadı.','Background scheduling is not active yet. You can save settings; daily delivery has not started.')}</p><div class="rd-actions"><button class="primary-button" data-reminder="save">${t('Saati kaydet','Save time')}</button><button class="secondary-button" data-reminder="enable" ${!supported()||!data.configured?'disabled':''}>${t('Bu cihazda bildirim aç','Enable on this device')}</button><button class="secondary-button" data-reminder="test" ${!supported()||!data.configured?'disabled':''}>${t('Test bildirimi gönder','Send test notification')}</button><button class="secondary-button" data-reminder="remove" ${!supported()?'disabled':''}>${t('Bu cihazı kaldır','Remove this device')}</button><button class="secondary-button" data-reminder="close">${t('Kapat','Close')}</button></div><p role="status" aria-live="polite"></p></div>`;
  }catch{status(t('Ayarlar yüklenemedi. Hesabına giriş yapıp yeniden dene.','Settings could not load. Sign in and try again.'));}
 }
 window.realdevReminders=open;
 dialog.addEventListener('click',async event=>{
  const button=event.target.closest('[data-reminder]');if(!button)return;const action=button.dataset.reminder;if(action==='close'){dialog.close();return;}button.disabled=true;
  try{
   if(action==='save'){await api('',settings(),'PUT');status(t('Saat ve hatırlatma tercihin kaydedildi. Cihaz iznini ayrıca açmalısın.','Your time and reminder preference are saved. Enable device permission separately.'));}
   if(action==='enable'){
    const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('permission');
    const reg=await registration();let subscription=await reg.pushManager.getSubscription();
    if(!subscription){const b64=data.publicKey.replace(/-/g,'+').replace(/_/g,'/');const key=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));subscription=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});}
    await api('/subscription',{subscription:subscription.toJSON()});dialog.querySelector('#reminderEnabled').checked=true;await api('',settings(),'PUT');status(t('Bu cihaz bağlandı. Günlük hatırlatma açıldı.','This device is connected. Daily reminders are enabled.'));
   }
   if(action==='test'){const subscription=await (await registration()).pushManager.getSubscription();if(!subscription)throw Error('missing');await api('/test',{endpoint:subscription.endpoint,language:window.realdevLocale==='en'?'en':'tr'});status(t('Test bildirimi bildirim servisine iletildi. Cihazında kontrol et.','The push service accepted the test notification. Check your device.'));}
   if(action==='remove'){const subscription=await (await registration()).pushManager.getSubscription();if(subscription){await api('/subscription',{remove:true,endpoint:subscription.endpoint});await subscription.unsubscribe();}status(t('Bu cihazın bildirim bağlantısı kaldırıldı. Diğer cihazlar değişmedi.','This device is disconnected. Other devices are unchanged.'));}
  }catch(error){status(error.message==='push_test_cooldown'?t('Yeni test için bir dakika bekle.','Wait one minute before another test.'):error.message==='permission'?t('Bildirim izni verilmedi. Saat tercihin korunuyor.','Notification permission was not granted. Your time preference is preserved.'):error.message==='missing'?t('Önce bu cihazda bildirim aç.','Enable notifications on this device first.'):t('İşlem tamamlanamadı. Bildirim iznini ve internet bağlantını kontrol edip yeniden dene.','The operation failed. Check notification permission and network access, then retry.'));}finally{button.disabled=false;}
 });
 if(new URLSearchParams(location.search).has('practice'))setTimeout(()=>go('route'),600);
})();

